### PR TITLE
Fix and unit tests for #2532

### LINKED ISSUE #2532: -parallel -threadcount CLI switches has no effect on test jar
### Expected behavior
Tests run in multiple threads, given command like `CLASSPATH=[test_fat_jar] java org.testng.TestNG -testjar [test_fat_jar] -parallel classes -threadcount 3`, and no parallel and threadcount in testng.xml 

### Actual behavior
Tests run in single  thread,  given command like `CLASSPATH=[test_fat_jar] java org.testng.TestNG -testjar [test_fat_jar] -parallel classes -threadcount 3`

### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

https://github.com/dsankouski/GradleTestNgIssues/tree/parallel_cli_switches

### PR DESCRIPTION
**Pull request by dsankouski**
This closes #2532. Treat suites from jar same as suites, from filesystem.

Divide parseSuite method into 2 parts: reading suites from files, and processing it.
Apply processing part for suites in jar files, too.

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

`testExclusionOfPassedConfigsInvolvingGroups*` tests fails occasionally.  Failure occurs due to incorrect instance detection in upstreamConfigFailures in org.testng.reporters.FailedReporter#generateXmlTest method. That seems not related to this PR.
UPDATE: this should be fixed in #2620

#2532

### CODE REVIEW

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 1]
```diff
@@ -317,32 +317,13 @@ private OverrideProcessor getProcessor() {
     return new OverrideProcessor(m_includedGroups, m_excludedGroups);
   }
 
-  private void parseSuite(String suitePath) {
+  private Collection<XmlSuite> parseSuite(String suitePath) {
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:320]: Is it possible to make it static?

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 2]
```diff
@@ -317,32 +317,13 @@ private OverrideProcessor getProcessor() {
...
-        }
-        // If test names were specified, only run these test names
-        TestNamesMatcher testNamesMatcher = new TestNamesMatcher(s, m_testNames);
-        List<String> missMatchedTestname = testNamesMatcher.getMissMatchedTestNames();
-        if (!missMatchedTestname.isEmpty()) {
-          throw new TestNGException("The test(s) <" + missMatchedTestname + "> cannot be found.");
-        }
-        m_suites.addAll(testNamesMatcher.getSuitesMatchingTestNames());
-      }
+      allSuites = Parser.parse(suitePath, getProcessor());
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:326]: return directly here

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 3]
```diff
@@ -317,32 +317,13 @@ private OverrideProcessor getProcessor() {
     return new OverrideProcessor(m_includedGroups, m_excludedGroups);
   }
 
-  private void parseSuite(String suitePath) {
+  private Collection<XmlSuite> parseSuite(String suitePath) {
     if (LOGGER.isDebugEnabled()) {
       LOGGER.debug("suiteXmlPath: \"" + suitePath + "\"");
     }
+    Collection<XmlSuite> allSuites = null;
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:324]: `allSuites` is not supposed to be null in `processCommandLineArgs `

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 4]
```diff
@@ -374,7 +382,10 @@ public void initializeSuitesAndJarFile() {
     // Parse the suites that were passed on the command line
     //
     for (String suitePath : m_stringSuites) {
-      parseSuite(suitePath);
+      Collection<XmlSuite> allSuites;
+      allSuites = parseSuite(suitePath);
+      allSuites = processCommandLineArgs(allSuites);
+      m_suites.addAll(allSuites);
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:388]:
```java
Collection<XmlSuite> allSuites = parseSuite(suitePath);
m_suites.addAll(processCommandLineArgs(allSuites));
```

is maybe more readable

**Review by juherr — CHANGES_REQUESTED** [review]
Thanks for the fix.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (dsankouski) [reply testng-core/src/main/java/org/testng/TestNG.java:320]: No, it uses `getProcessor` method, which operates members.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 2 above)
Comment (dsankouski) [reply testng-core/src/main/java/org/testng/TestNG.java:326]: ok

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 3 above)
Comment (dsankouski) [reply testng-core/src/main/java/org/testng/TestNG.java:324]: return empty Set

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 4 above)
Comment (dsankouski) [reply testng-core/src/main/java/org/testng/TestNG.java:388]: ok

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 5]
```diff
@@ -374,7 +381,9 @@ public void initializeSuitesAndJarFile() {
     // Parse the suites that were passed on the command line
     //
     for (String suitePath : m_stringSuites) {
-      parseSuite(suitePath);
+      Collection<XmlSuite> allSuites;
+      allSuites = parseSuite(suitePath);
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:385]: Merge lines:

```java
Collection<XmlSuite> allSuites = parseSuite(suitePath);
```

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 6]
```diff
@@ -403,7 +412,10 @@ public void initializeSuitesAndJarFile() {
     JarFileUtils utils =
         new JarFileUtils(getProcessor(), m_xmlPathInJar, m_testNames, m_parallelMode);
 
-    m_suites.addAll(utils.extractSuitesFrom(jarFile));
+    Collection<XmlSuite> allSuites;
+    allSuites = utils.extractSuitesFrom(jarFile);
+    allSuites = processCommandLineArgs(allSuites);
+    m_suites.addAll(allSuites);
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:418]: Apply the same pattern here:

```java
Collection<XmlSuite> allSuites = utils.extractSuitesFrom(jarFile);
m_suites.addAll(processCommandLineArgs(allSuites));
```

**Review by juherr — CHANGES_REQUESTED** [review]

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 5 above)
Comment (dsankouski) [reply testng-core/src/main/java/org/testng/TestNG.java]: done

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 6 above)
Comment (dsankouski) [reply testng-core/src/main/java/org/testng/TestNG.java]: done

**Review by juherr — APPROVED** [review]
Thanks for your contribution 👍
