### PR TITLE
fix possibilty that AfterGroups method is invoked before all tests

### LINKED ISSUE #2754: @AfterGroups is executed for each "finished" group when it has multiple groups defined
### TestNG Version
7.5

### Expected behavior
a configuration method annotated with AfterGroups should be invoked once only after all tests with groups defined in configuration method are invoked

### Actual behavior
when @AfterGroups annotated method has multiple groups then it will be invoked after the last method of each of this group

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```
public class ATest {

    @AfterGroups(groups = {"group-1", "group-2", "not-defined"})
    public void afterGroup() {
        System.out.println("after-group");
    }

    @Test(groups = "group-1")
    public void test1() {
        System.out.println("test-1");
    }

    @Test(groups = "group-2")
    public void test2() {
        System.out.println("test-2");
    }
}
```

Output
```
test-1
after-group
test-2
after-group
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### PR DESCRIPTION
**Pull request by velma**
Fixes #2754
When AfterGroups method has multiple groups defined then situation was possible that it is invoked not after all tests for all its groups but after the last test of any group

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`
- [x] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: testng-core/src/main/java/org/testng/internal/ConfigurationGroupMethods.java [hunk 1]
```diff
@@ -121,9 +73,37 @@ public List<ITestNGMethod> getBeforeGroupMethodsForGroup(String[] groups) {
...
+      }
+
+      return methodGroups.stream()
+          .filter(t -> isLastMethodForGroup(t, testMethod))
+          .map(t -> retrieve(afterGroupsThatHaveAlreadyRun, m_afterGroupsMethods, t))
+          .filter(Objects::nonNull)
+          .flatMap(Collection::stream)
+          .filter(
+              afterGroupMethod -> {
+                String[] afterGroupMethodGroups = afterGroupMethod.getAfterGroups();
```
Comment (krmahadevan) [inline testng-core/src/main/java/org/testng/internal/ConfigurationGroupMethods.java:95]: For better readability, can we please extract out this lambda as a separate method which can then be invoked from within here?

File: CHANGES.txt [hunk 2]
```diff
@@ -11,6 +11,7 @@ Fixed: GITHUB-2637: Upgrade to JDK11 as the minimum JDK requirements (Krishnan M
 Fixed: GITHUB-2734: Keep the initial order of listeners (Andrei Solntsev)
 Fixed: GITHUB-2359: Testng @BeforeGroups is running in parallel with testcases in the group (Anton Velma)
 Fixed: Possible StringIndexOutOfBoundsException in XmlReporter (Anton Velma)
+Fixed: AfterGroups methods could be invoked before all tests for defined groups in case of multiple groups for AfterGroups method (Anton Velma)
```
Comment (krmahadevan) [inline CHANGES.txt:14]: For the sake of tracking, request you to please help file a bug and link it here so that we can have way to trace back the change, if required in the future.

Comment (krmahadevan) [reply CHANGES.txt:14]: @velma - Can you please update the `CHANGES.txt` to include a reference to the github issue https://github.com/cbeust/testng/issues/2754

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@juherr can you please help take a quick look ?

File: testng-core/src/main/java/org/testng/internal/ConfigurationGroupMethods.java [hunk 3]
```diff
@@ -121,10 +73,40 @@ public List<ITestNGMethod> getBeforeGroupMethodsForGroup(String[] groups) {
...
+          .filter(t -> isLastMethodForGroup(t, testMethod))
+          .map(t -> retrieve(afterGroupsThatHaveAlreadyRun, m_afterGroupsMethods, t))
+          .filter(Objects::nonNull)
+          .flatMap(Collection::stream)
+          .filter(t -> isAfterGroupAllowedToRunAfterTestMethod(t, methodGroups))
+          .collect(Collectors.toList());
+    }
+  }
+
+  private boolean isAfterGroupAllowedToRunAfterTestMethod(
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/internal/ConfigurationGroupMethods.java:98]: It looks the method has no dependency and it could be static

Comment (velma) [reply testng-core/src/main/java/org/testng/internal/ConfigurationGroupMethods.java:98]: it depends on m_afterGroupsMap

**Review by juherr — APPROVED** [review]
