### PR TITLE
Fixed #2327 by adding parameters for skipped methods explicitly

### LINKED ISSUE #2327: Parameters not present on skipped Test because of failing configuration method
### TestNG Version
7.2.0 and current master branch

### Description
For a better understanding I will provide some code samples, but at first I want to describe the error. 

When using the `Dataprovider` in mode `parallel=true` in combination with a `@BeforeMethod`, the configuration method will run for every dataset. This is intended behaviour. 
With a dataset-dependent configuration mehtod it could occur, that the `BeforeMethod` for dataset1 will pass, and for dataset 2 may will fail.
For a failing configuration method, the test method will be markes as skipped.

When providing an own listener implementing the `ITestListener` interface, and implementing the method `onTestSuccess` and 
`onTestSkipped` adressing the `ITestResult.getParameters()` method I encountered the issue, that for skipped test methods the parameters will be not set.

For reporting purposes and further handling I want to access the `parameters` for skipped methods in the same way as for passing or failing tests.

### Expected behavior
`ITestResult.getParameters()` for implementations of `onTestSkipped` in `ITestListener` interface returns parameters of data provider.

Output for appended test sample:
````
Success: [Dataset2]
Test ignored.
Skipped: [Dataset1]
````

### Actual behavior
`ITestResult.getParameters()` for implementations of `onTestSkipped` in `ITestListener` interface does not return parameters of data provider.

Output for appended test sample:
````
Success: [Dataset2]
Test ignored.
Skipped: []
````

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
.Listener Example
````java
public class SkipListener implements ITestListener {
  @Override
  public void onTestSuccess(ITestResult result) {
    System.out.println("Success: " + Arrays.toString(result.getParameters()));
  }

  @Override
  public void onTestSkipped(ITestResult result) {
    System.out.println("Skipped: " + Arrays.toString(result.getParameters()));
  }
}
````

.TestClass
````java
@Listeners(SkipListener.class)
public class ClassWithFailedBeforeMethod {

  static boolean fail = true;

  @BeforeMethod(alwaysRun = true)
  public void setupShouldFail(Method method, Object[] params) {

    if (fail) {
      fail = false;
      throw new RuntimeException("Failing in setUp");
    }
  }

  @DataProvider(parallel = true)
  public Iterator<Object> dummyData() {
    ArrayList<Object> objects = new ArrayList<>();
    objects.add("Dataset1");
    objects.add("Dataset2");
    return objects.iterator();
  }

  @Test(dataProvider = "dummyData")
  public void test1(String test) {}
}

````

If I should add any value to this issue, please let me know.
Further I will create a pull request for the bug fix, if you appreciate it.

Best regards,
Eric

### PR DESCRIPTION
**Pull request by erickubenka**
Fixes #2327  .

### Did you remember to?
- [x] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:
* Fix bugs in TestNG

### CODE REVIEW

**Comment by krmahadevan** [comment]
@erickubenka - There are test failures. Please see https://travis-ci.org/github/cbeust/testng/jobs/700774239

@cbeust @juherr - Any idea why the test results from travis ci is not getting populated in the PR as a comment ? It used to happen before, but now it doesn't happen for some reason.

**Comment by krmahadevan** [comment]
@cbeust - Can you please check this thread https://travis-ci.community/t/travis-ci-build-no-longer-showing-as-check-on-github-pull-request-page/6955/8 and see if you can revoke and grant travis ci access once again to fix this? Without this feedback coming back to the PR, its going to be hard to review and merge PRs and risk breaking the build.

File: src/test/java/test/dataprovider/issue2327/SampleTestCase.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import java.lang.reflect.Method;
+import java.util.Arrays;
+import java.util.Iterator;
+import java.util.LinkedList;
+import org.testng.annotations.BeforeMethod;
+import org.testng.annotations.DataProvider;
+import org.testng.annotations.Listeners;
+import org.testng.annotations.Test;
+
+@Listeners(CustomListener.class)
```
Comment (krmahadevan) [inline src/test/java/test/dataprovider/issue2327/SampleTestCase.java:12]: You don't need this listener because all this listener is doing is printing stuff.

File: src/test/java/test/dataprovider/issue2327/IssueTest.java [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+public class IssueTest extends SimpleBaseTest {
+
+  @Test(description = "GITHUB-2327")
+  public void runTest() {
+    TestNG testng = create(SampleTestCase.class);
+    TestListenerAdapter tla = new TestListenerAdapter();
+    testng.addListener(tla);
+    testng.run();
+
+    System.out.println("2327p:" + tla.getPassedTests().size());
```
Comment (krmahadevan) [inline src/test/java/test/dataprovider/issue2327/IssueTest.java:19]: Please remove these sys out statements.

**Review by krmahadevan — CHANGES_REQUESTED** [review]
There are test failures. Please run the tests from the command prompt by executing https://github.com/cbeust/testng/blob/master/build-with-gradle

File: src/test/java/test/dataprovider/issue2327/CustomListener.java [hunk 3]
```diff
@@ -0,0 +1,20 @@
+package test.dataprovider.issue2327;
+
+import java.util.Arrays;
+import org.testng.ITestListener;
+import org.testng.ITestResult;
+
+public class CustomListener implements ITestListener {
```
[the remark this answers is not in the document]
Comment (erickubenka) [reply src/test/java/test/dataprovider/issue2327/CustomListener.java]: Yeah, I swa that too. I just copied my sample for testing, but it's quite not necessary. 
Therefore I deleted / removed this Listener.

File: src/test/java/test/dataprovider/issue2327/IssueTest.java (hunk 2 above)
Comment (erickubenka) [reply src/test/java/test/dataprovider/issue2327/IssueTest.java]: It's out now. Sorry for that. Was just to debug some things on travis.
Test should be green now.

**Review by krmahadevan — APPROVED** [review]

**Review by juherr — APPROVED** [review]
