### PR TITLE
Fix issue #1380: Circular dependencies may fail in parallel

### LINKED ISSUE #1380: DynamicGraph should manage transitive dependencies
```java
@Test
public void test3() {
        DynamicGraph<Node> dg = new DynamicGraph<>();
        Node a = new Node("a");
        Node b = new Node("b");
        Node c = new Node("c");
        dg.addNode(a);
        dg.addNode(b);
        dg.addNode(c);
        dg.addEdge(1, a, b);
        dg.addEdge(0, c, b);
        dg.addEdge(0, b, a);

        assertFreeNodesEquals(dg, b);

        dg.setStatus(b, Status.RUNNING);
        assertFreeNodesEquals(dg);

        dg.setStatus(b, Status.FINISHED);
        assertFreeNodesEquals(dg, a, c);

        dg.setStatus(a, Status.FINISHED);
        dg.setStatus(c, Status.FINISHED);
        assertFreeNodesEquals(dg);
}
```

`a` and `c` should not be free at the same time: if `c -> b -> a` then an explicit edge should exist from `c` to `a`.
When `b` is finished then `a` should be free first and `c` only once `a` is finished.

From #1290

### PR DESCRIPTION
**Pull request by juherr**
Fixes #1380.

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

### CODE REVIEW

File: src/main/java/org/testng/internal/DynamicGraph.java [hunk 1]
```diff
@@ -158,17 +159,19 @@ private int getLowestEdgePriority(List<T> nodes) {
     return lowerPriority == null ? 0 : lowerPriority;
   }
 
-  private int getLowestOrder(List<T> nodes) {
+  private int getLowestOrder(List<T> nodes, int weight) {
```
Comment (cbeust) [inline src/main/java/org/testng/internal/DynamicGraph.java]: I'm confused by the naming and the semantics of this method. What is an order? Is it a weight? If yes, then call it `getLowestWeight()`, but then the passed parameter `weight` is confusing.

Can you add a comment explaining what this method does?

Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: `order` is the way to have a hierarchy between edges with the same weight. It was introduced by @krmahadevan with https://github.com/cbeust/testng/commit/55c3745502fd9d9e23e49f0bdafc577cacb1fc20
and has only sense with its associated weight.
If someone has better names, I agree to change them.

Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: I will double check. Maybe we don't need `order` at all.

File: src/test/java/test/dependent/github1380/GitHub1380Sample4.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
+package test.dependent.github1380;
```
Comment (krmahadevan) [inline src/test/java/test/dependent/github1380/GitHub1380Sample4.java]: @juherr - This test by itself doesn't look proper to me because of the scenario its testing. 
We are saying `testMethodA` has a priority of 1 but it depends on a method `testMethodB` which has a priority of 2. Don't you think that by itself is a confusing statement ? Why would someone do this ? (Apart from the fact that they want to do it for the sake of it). Can you please help me understand this part ?

Comment (juherr) [inline src/test/java/test/dependent/github1380/GitHub1380Sample4.java]: The behavior the same since the hierarchy of order features was introduced.

TestNG respect the most important feature feature first (dependsOnMethods here).

We must support circular dependency when many features because of the others priority features like group-by-instance which may produce circular dependencies.
Feel free to block it and tests, you'll see many errors.

Comment (krmahadevan) [inline src/test/java/test/dependent/github1380/GitHub1380Sample4.java]: @juherr - I was asking about the nature of the test and not the behavior. Is that test semantically correct ? Why would a person want to mix up `dependsOnMethods` and `priority` in a circular fashion (Visibly its like going around in circles). So I wanted to know, if that test case by itself is semantically correct.

Comment (juherr) [inline src/test/java/test/dependent/github1380/GitHub1380Sample4.java]: Oh, ok. I don't know if someone would to do it a day. But it was easier sample (and not a unit test of graph) which reproduces the issue.

File: src/main/java/org/testng/internal/DynamicGraph.java (hunk 1 above)
Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: @cbeust `order` is removed now. Is it better for you?

Comment (cbeust) [inline src/main/java/org/testng/internal/DynamicGraph.java]: Yes, thanks!

**Comment by juherr** [comment]
Ping @krmahadevan @cbeust

**Comment by krmahadevan** [comment]
@cbeust - Need your help in reviewing this.. :) The Graph part of TestNG is still something that I haven't yet gotten a full hang of.  The changes pertaining to removing the order (essentially it reverts my changes), looks good to me.  This part of TestNG is still on my agenda to learn and figure out.

**Comment by juherr** [comment]
Ping @cbeust
