### PR TITLE
Failed Configs to be included in failed reports

### LINKED ISSUE #2611: Config Failures not included in testng-failed.xml when its part of a different test class
7.4.0

### Expected behavior

The failed configuration should be included in the `testng-failed.xml`

### Actual behavior
The failed configuration is missing in the `testng-failed.xml`

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

**Test classes**

```java
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;

public class MasterOogwayTest {

  @BeforeTest(groups = {"dragon-warrior"})
  public void test1Method() {
    Assert.fail();
  }

  @AfterTest(groups = {"dragon-warrior"})
  public void test1AfterMethod() {
  }
}
```

```java
import org.testng.annotations.Test;

public class MasterShifuTest {

  @Test(groups = {"dragon-warrior"})
  public void test2Method() {
  }
}
```

TestNG suite xml file
```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="set-3" parallel="tests" thread-count="10" verbose="2">
  <test name="Kung-fu-panda-tests" verbose="2">
    <groups>
      <run>
        <include name="dragon-warrior"/>
      </run>
    </groups>
    <classes>
      <class name="com.rationaleemotions.stackoverflow.qn68292525.MasterOogwayTest"/>
      <class name="com.rationaleemotions.stackoverflow.qn68292525.MasterShifuTest"/>
    </classes>
  </test>
</suite>
```

Expected `testng-failed.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="10" guice-stage="DEVELOPMENT" verbose="2" name="Failed suite [set-3]" parallel="tests">
  <test thread-count="10" verbose="2" name="Kung-fu-panda-tests(failed)" parallel="tests">
    <groups>
      <run>
        <include name="dragon-warrior"/>
      </run>
    </groups>
    <classes>
      <class name="com.rationaleemotions.stackoverflow.qn68292525.MasterShifuTest">
        <methods>
          <include name="test2Method"/>
        </methods>
      </class> <!-- com.rationaleemotions.stackoverflow.qn68292525.MasterShifuTest -->
      <class name="com.rationaleemotions.stackoverflow.qn68292525.MasterOogwayTest">
        <methods>
          <include name="test1Method"/>
        </methods>
      </class> <!-- com.rationaleemotions.stackoverflow.qn68292525.MasterOogwayTest -->
    </classes>
  </test> <!-- Kung-fu-panda-tests(failed) -->
</suite> <!-- Failed suite [set-3] -->
```

Actual `testng-failed.xml` (Notice how reference to `MasterOogwayTest` is missing in the `testng-failed.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="10" guice-stage="DEVELOPMENT" verbose="2" name="Failed suite [set-3]" parallel="tests">
  <test thread-count="10" verbose="2" name="Kung-fu-panda-tests(failed)" parallel="tests">
    <groups>
      <run>
        <include name="dragon-warrior"/>
      </run>
    </groups>
    <classes>
      <class name="com.rationaleemotions.stackoverflow.qn68292525.MasterShifuTest">
        <methods>
          <include name="test2Method"/>
        </methods>
      </class> <!-- com.rationaleemotions.stackoverflow.qn68292525.MasterShifuTest -->
    </classes>
  </test> <!-- Kung-fu-panda-tests(failed) -->
</suite> <!-- Failed suite [set-3] -->

```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2611

Fixes #2611  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: testng-core/src/test/java/test/reports/FailedReporterTest.java [hunk 1]
```diff
@@ -81,4 +87,65 @@ public void testParameterPreservationWithFactory() throws IOException {
 
     assertThat(myDiff).matches((it) -> !it.hasDifferences(), "!it.hasDifferences()");
   }
+
+  @Test(dataProvider = "getTestData")
+  public void testToEnsureConfigFailuresAreIncluded(
+      Pair<Class<?>, String> pairA, Pair<Class<?>, String> pairB) throws IOException {
```
Comment (juherr) [inline testng-core/src/test/java/test/reports/FailedReporterTest.java:93]: Not sure that using `Pair` is more readable than 2 params well named.

**Review by juherr — CHANGES_REQUESTED** [review]
I commented on the related issue because I'm not sure about the expectations.

Please, suffix sample classes by `Sample`.

File: testng-core/src/test/java/test/reports/FailedReporterTest.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/test/java/test/reports/FailedReporterTest.java:93]: @juherr I need to be sending in 2 classes and 2 test method names. I had the choice of either creating a new Pojo for this and using that or using something that already exists. 

`Pair` sounded apt for me as well because it's a pair of class and a method.

Comment (juherr) [reply testng-core/src/test/java/test/reports/FailedReporterTest.java:93]: Sure `Pair` is the appropriate object to use but maybe a bit excessive in this specific case because `Class<?> testClassA` and `String testMethodA` are more expressive.

In some other languages, you are be able to do things like `(testClassA, testMethodA) = pairA`.

Comment (krmahadevan) [reply testng-core/src/test/java/test/reports/FailedReporterTest.java:93]: @juherr You want me to add `testClassA, testMethodA, testClassB, testMethodB` as my data driven method's parameter?

Comment (juherr) [reply testng-core/src/test/java/test/reports/FailedReporterTest.java:93]: That was just an open suggestion. Please, check the initial issue first.

**Comment by krmahadevan** [comment]
@juherr - I have altered the logic to include all the below configurations 

* `@BeforeGroups`
* `@AfterGroups`
* `@BeforeTest`
* `@AfterTest`
* `@BeforeSuite`
* `@AfterSuite`

when dealing with failures

File: testng-core/src/test/java/test/reports/FailedReporterTest.java [hunk 2]
```diff
@@ -81,4 +90,123 @@ public void testParameterPreservationWithFactory() throws IOException {
...
+    List<String> includedMethods =
+        xmlClass.getIncludedMethods().stream()
+            .map(XmlInclude::getName)
+            .collect(Collectors.toList());
+    assertThat(includedMethods)
+        .withFailMessage("Included methods test failed for " + cls.getName())
+        .containsExactlyInAnyOrder(methods);
+  }
+
+  public static class ClassMethodInfo {
```
Comment (juherr) [inline testng-core/src/test/java/test/reports/FailedReporterTest.java:190]: WDYT to use https://projectlombok.org/ in test to avoid boilerplate code?

**Review by juherr — CHANGES_REQUESTED** [review]
Could you add some tests with failing after configurations?

File: testng-core/src/test/java/test/reports/FailedReporterTest.java (hunk 2 above)
Comment (krmahadevan) [reply testng-core/src/test/java/test/reports/FailedReporterTest.java:190]: @juherr - Yes that's a very good option. But I dont know if we have enough number needs in tests to take this route.

**Comment by krmahadevan** [comment]
@juherr 

> Could you add some tests with failing after configurations?

I don't think failed configurations would matter here because they wont be failing the tests. The tests would have already run to completion and a failure in `@AfterTest|@AfterSuite|@AfterGroups` don't affect the outcome of the test execution no ?

**Review by juherr — APPROVED** [review]
