### PR TITLE
Favor runtime computation of test methods

### LINKED ISSUE #2096: 7.0.0-beta6 memory issues (regression)
A test task runs over 310,000 independent test executions. In `6.14.3` this completes in about 2.5 minutes. In `7.0.0-beta6` this slows down to a crawl at 200k tests, appearing to GC thrash as small batches of tests complete.

In the past, I've seen this occur due to reporting keeping parameters in-memory. The project uses a [workaround](https://github.com/ben-manes/caffeine/blob/c6264dad9b54eeff0193f9c6f77339d0c45f9141/caffeine/src/test/java/com/github/benmanes/caffeine/cache/testing/CacheValidationListener.java#L149-L161) to replace test parameters with their `toString` version, as these are too heavy for a large run. I suspect there is some similar per-test memory grab by the reporter.

The next step is probably to take a heap dump and determine what is held. Before running too far into this, do you know what changes were made that might hint at what to look for?

```gradle
./gradlew :caffeine:strongKeysAndStrongValuesAsyncCaffeineTest
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #2096

TestRunner currently remembers all test methods.
Refactored such that test methods are now 
computed on runtime.

### CODE REVIEW

**Review by juherr — COMMENTED** [review]
I'm not sure z computation every time is a good idea. Do you have another possible strategy?

**Comment by krmahadevan** [comment]
@juherr - No I couldn't find any other alternatives apart from the computation every time. But this shouldn't affect execution, because the computation is called before test method execution.

**Comment by juherr** [comment]
I'm not feeling it good for the moment: you save memory but lost CPU.

Could you share some perf metrics before and after the change?

**Comment by krmahadevan** [comment]
@juherr - Before i tread down the path of trying to extract some perf metrics.. here's a few facts

`org.testng.TestRunner#getAllTestMethods` is currently invoked under the following conditions

image

From the above screenshot.

* `SuiteRunner.getMethodsByGroups()` - This is invoked ONLY by reporting implementations. It will not impact test execution.
* `TestInvoker.invokeTestMethods()` - This is invoked for running tests.  We can actually refactor the code a bit more such that the context.getAllTestMethods() is NOT invoked unnecessarily (i.e., its called only when `alwaysRun=false` and test has group/method dependencies). That way the impact can be brought down. Now assuming that all of my tests have dependencies (worst case scenario), I need some help/guidance to creating a benchmark for getting perf metrics (I have never done these stuff and so I dont know how to do them). Any baby steps etc., that you can share, which will help me move forward in the right direction ?

The other calls are all involving Reports. Do we need to worry about that part, considering the fact that reports arent expected to be a realtime activity that can/will affect test execution ?

**Comment by juherr** [comment]
You got the point: the separation between the runtime part and the reporting part is not clear enough and I think more effort should be done on the architecture instead of some little improvements.

Removing `m_allTestMethods` is a good idea but I'm not feeling this specific PR good because some changes are done on the runtime part in order to improve the reporting part.

Could you try to go deeper with its usages and check if/how `getAllTestMethods` could be removed from the runtime part?

**Comment by krmahadevan** [comment]
@juherr 

Can you please take another look at the updated PR ? I have made some changes (most significant of it being there now exists a toggle which can be used by large projects to enable the memory friendly behavior)

Below is how the heap dump looks like (I basically used the same stress test project that @ben-manes had shared, and ran it with the below argument line via surefire plugin (I mavenised the project) Here LiteWeightTestNGMethod is the variant that I created which does not remember `ConstructorOrMethod` and can be triggered via the JVM argument 
`-Dtestng.memory.friendly=true`

```
-Xms256m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError -Dtestng.memory.friendly=true
```

image

I will share the micro benchmarking data as well soon. 

In a nutshell, i built a micro benchmarking test (contains 200 test classes, each of which contains 26 methods, wherein there is a multi level dependency chain i.e., `a()` is an independent method and `b()` depends on `a()`, and so on.  In the benchmark test I evaluate call to `context.getAllTestMethods()` (which is what gets evaluated for every call). I still dont know how to parse the results, so am hoping you could help me with it.

**Comment by krmahadevan** [comment]
Here's how each of the 200 classes look like 

```java
import org.testng.annotations.Test;

public class TestClass_1 {

  @Test
  public void test_1() {
  }

  @Test(dependsOnMethods = "test_1")
  public void test_2() {
  }

  @Test(dependsOnMethods = "test_2")
  public void test_3() {
  }

  @Test(dependsOnMethods = "test_3")
  public void test_4() {
  }

  @Test(dependsOnMethods = "test_4")
  public void test_5() {
  }

  @Test(dependsOnMethods = "test_5")
  public void test_6() {
  }

  @Test(dependsOnMethods = "test_6")
  public void test_7() {
  }

  @Test(dependsOnMethods = "test_7")
  public void test_8() {
  }

  @Test(dependsOnMethods = "test_8")
  public void test_9() {
  }

  @Test(dependsOnMethods = "test_9")
  public void test_10() {
  }

  @Test(dependsOnMethods = "test_10")
  public void test_11() {
  }

  @Test(dependsOnMethods = "test_11")
  public void test_12() {
  }

  @Test(dependsOnMethods = "test_12")
  public void test_13() {
  }

  @Test(dependsOnMethods = "test_13")
  public void test_14() {
  }

  @Test(dependsOnMethods = "test_14")
  public void test_15() {
  }

  @Test(dependsOnMethods = "test_15")
  public void test_16() {
  }

  @Test(dependsOnMethods = "test_16")
  public void test_17() {
  }

  @Test(dependsOnMethods = "test_17")
  public void test_18() {
  }

  @Test(dependsOnMethods = "test_18")
  public void test_19() {
  }

  @Test(dependsOnMethods = "test_19")
  public void test_20() {
  }

  @Test(dependsOnMethods = "test_20")
  public void test_21() {
  }

  @Test(dependsOnMethods = "test_21")
  public void test_22() {
  }

  @Test(dependsOnMethods = "test_22")
  public void test_23() {
  }

  @Test(dependsOnMethods = "test_23")
  public void test_24() {
  }

  @Test(dependsOnMethods = "test_24")
  public void test_25() {
  }

  @Test(dependsOnMethods = "test_25")
  public void test_26() {
  }
}

```

Here's how the benchmark tests look like 

```java
import java.util.Collections;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.TestNG;
import org.testng.xml.XmlPackage;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

@State(Scope.Benchmark)
public class BenchmarkState {

  public volatile ITestContext context;

  @Setup
  public void setup() {
    TestNG testng = new TestNG();
    ITestListener listener = new ITestListener() {
      @Override
      public void onFinish(ITestContext ctx) {
        context = ctx;
      }
    };
    XmlSuite xmlSuite = new XmlSuite();
    xmlSuite.setVerbose(2);
    xmlSuite.setName("sample_suite");
    XmlTest xmlTest = new XmlTest(xmlSuite);
    xmlTest.setName("sample_test");
    String pkg =  "com.rationaleemotions.samples.*";
    xmlTest.setXmlPackages(Collections.singletonList(new XmlPackage(pkg)));
    testng.setXmlSuites(Collections.singletonList(xmlSuite));
    testng.addListener(listener);
    System.err.println("Suite file " + xmlSuite.toXml());
    testng.run();
  }
}

```

```java
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.infra.Blackhole;

public class TestNGBenchmark {

  @Benchmark
  @BenchmarkMode(Mode.AverageTime)
  public void testMethod(BenchmarkState state, Blackhole blackhole) {
    blackhole.consume(state.context.getAllTestMethods());
  }
}
```

**Comment by krmahadevan** [comment]
Here's how the test results look like 

```
Result "com.rationaleemotions.TestNGBenchmark.testMethod":
  0.462 ±(99.9%) 0.014 s/op [Average]
  (min, avg, max) = (0.438, 0.462, 0.497), stdev = 0.019
  CI (99.9%): [0.448, 0.476] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.alloc.rate":
  116.213 ±(99.9%) 5.559 MB/sec [Average]
  (min, avg, max) = (101.637, 116.213, 123.661), stdev = 7.421
  CI (99.9%): [110.654, 121.772] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.alloc.rate.norm":
  58963227.444 ±(99.9%) 1340208.452 B/op [Average]
  (min, avg, max) = (55480116.190, 58963227.444, 60188035.826), stdev = 1789139.939
  CI (99.9%): [57623018.992, 60303435.895] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.churn.PS_Eden_Space":
  115.708 ±(99.9%) 18.002 MB/sec [Average]
  (min, avg, max) = (93.171, 115.708, 152.808), stdev = 24.032
  CI (99.9%): [97.706, 133.709] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.churn.PS_Eden_Space.norm":
  58759947.157 ±(99.9%) 8978010.001 B/op [Average]
  (min, avg, max) = (45909392.696, 58759947.157, 79092589.714), stdev = 11985386.488
  CI (99.9%): [49781937.156, 67737957.159] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.churn.PS_Survivor_Space":
  0.109 ±(99.9%) 0.069 MB/sec [Average]
  (min, avg, max) = (≈ 0, 0.109, 0.298), stdev = 0.092
  CI (99.9%): [0.040, 0.178] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.churn.PS_Survivor_Space.norm":
  55546.312 ±(99.9%) 35620.640 B/op [Average]
  (min, avg, max) = (≈ 0, 55546.312, 159159.619), stdev = 47552.536
  CI (99.9%): [19925.672, 91166.953] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.count":
  60.000 ±(99.9%) 0.001 counts [Sum]
  (min, avg, max) = (2.000, 2.400, 3.000), stdev = 0.500
  CI (99.9%): [60.000, 60.000] (assumes normal distribution)

Secondary result "com.rationaleemotions.TestNGBenchmark.testMethod:·gc.time":
  1221.000 ±(99.9%) 0.001 ms [Sum]
  (min, avg, max) = (13.000, 48.840, 124.000), stdev = 39.281
  CI (99.9%): [1221.000, 1221.000] (assumes normal distribution)


# Run complete. Total time: 00:17:52

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

Benchmark                                                    Mode  Cnt         Score         Error   Units
TestNGBenchmark.testMethod                                   avgt   25         0.462 ±       0.014    s/op
TestNGBenchmark.testMethod:·gc.alloc.rate                    avgt   25       116.213 ±       5.559  MB/sec
TestNGBenchmark.testMethod:·gc.alloc.rate.norm               avgt   25  58963227.444 ± 1340208.452    B/op
TestNGBenchmark.testMethod:·gc.churn.PS_Eden_Space           avgt   25       115.708 ±      18.002  MB/sec
TestNGBenchmark.testMethod:·gc.churn.PS_Eden_Space.norm      avgt   25  58759947.157 ± 8978010.001    B/op
TestNGBenchmark.testMethod:·gc.churn.PS_Survivor_Space       avgt   25         0.109 ±       0.069  MB/sec
TestNGBenchmark.testMethod:·gc.churn.PS_Survivor_Space.norm  avgt   25     55546.312 ±   35620.640    B/op
TestNGBenchmark.testMethod:·gc.count                         avgt   25        60.000                counts
TestNGBenchmark.testMethod:·gc.time                          avgt   25      1221.000                    ms

```

File: src/main/java/org/testng/TestRunner.java [hunk 1]
```diff
@@ -99,14 +100,6 @@
       Maps.newHashMap();
   private final DataProviderHolder holder = new DataProviderHolder();
 
-  /**
-   * All the test methods we found, associated with their respective classes. Note that these test
-   * methods might belong to different classes. We pick which ones to run at runtime.
-   */
-  private ITestNGMethod[] m_allTestMethods = new ITestNGMethod[0];
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:106]: I propose to keep the attribute as a cache for the moment and only skip it when `RuntimeBehavior.isMemoryFriendlyMode()` is used.
It will allow us to have feedbacks without taking the risk of regressions.

File: src/main/java/org/testng/TestRunner.java [hunk 2]
```diff
@@ -544,9 +531,22 @@ private void initMethods() {
             true /* unique */,
             m_excludedMethods,
             comparator);
-    // shared group methods
-    m_groupMethods =
-        new ConfigurationGroupMethods(m_allTestMethods, beforeGroupMethods, afterGroupMethods);
+  }
+
+  private ITestNGMethod[] computeAndGetAllTestMethods() {
+    List<ITestNGMethod> testMethods = Lists.newArrayList();
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:537]: Proposal:

```java
if (m_allTestMethods != null && !RuntimeBehavior.isMemoryFriendlyMode()) {
  return m_allTestMethods;
}
```

File: src/main/java/org/testng/TestRunner.java [hunk 3]
```diff
@@ -544,9 +531,22 @@ private void initMethods() {
...
+    for (ITestClass tc : m_classMap.values()) {
+      fixMethodsWithClass(tc.getTestMethods(), tc, testMethods);
+    }
+
+    return MethodHelper.collectAndOrderMethods(
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:542]: Proposal:

```java
ITestNGMethod[] result = MethodHelper.collectAndOrderMethods(testMethods,
        true /* forTest? */,
        m_runInfo,
        m_annotationFinder,
        false /* unique */,
        m_excludedMethods,
        comparator);
if (!RuntimeBehavior.isMemoryFriendlyMode()) {
   m_allTestMethods = result;
}
return result;
```

File: src/main/java/org/testng/TestRunner.java [hunk 4]
```diff
@@ -678,7 +680,6 @@ public int compareTo(@Nonnull IWorker<ITestNGMethod> other) {
         });
 
     runJUnitWorkers(workers);
-    m_allTestMethods = runMethods.toArray(new ITestNGMethod[0]);
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:681]: `runMethods` is no more used: it was useless before or a feature is now broken.

File: src/main/java/org/testng/TestRunner.java [hunk 5]
```diff
@@ -628,6 +629,7 @@ private void privateRunJUnit() {
     // may result in an class resolution exception under different JVMs
     // The resolution process is not specified in the JVM spec with a specific implementation,
     // so it can be eager => failure
+    ITestNGMethod[] m_allTestMethods = computeAndGetAllTestMethods();
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:632]: According to the current usage of `m_allTestMethods` here, I propose to drop it.

File: src/main/java/org/testng/TestRunner.java (hunk 4 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java:681]: Proposal: keep usage of `m_allTestMethods` as a cache when the JUnit feature is used.

**Comment by ben-manes** [comment]
fyi, I tried running the stress test with memory friendly enabled, and it was worse. I guess because it began tracking methods whereas the other setting does not any longer? Note that JProfiler defaults to sorting by instance count rather than memory usage.

**Comment by krmahadevan** [comment]
@ben-manes - I loaded up the hprof file after it dumped an OutOfMemoryError (i ran the stress test with 256 mb memory for xms and xmx). Can you please help me understand a bit more on your observation and where you are seeing the gap ? That will help me take another look

**Comment by krmahadevan** [comment]
@juherr - let me go through the review comments and revamp the implementation. I realise now that the current approach of driving via a flag is a lot more easier approach to manage than the earlier one. Guess incremental refactoring does that to the code and when the developer (me) doesnt apply any long sightedness to the approach (facepalm moment for me..sigh!)

**Comment by juherr** [comment]
@krmahadevan 
> I realise now that the current approach of driving via a flag is a lot more easier approach to manage than the earlier one. Guess incremental refactoring does that to the code and when the developer (me) doesnt apply any long sightedness to the approach (facepalm moment for me..sigh!)

I agree. Using a feature flag is a good idea most of the time and have a lot of benefits :)

BTW, you know the rule: 
> Think big, start small, act fast

**Comment by krmahadevan** [comment]
> Think big, start small, act fast

@juherr - That rule is where i kind of keep slipping.. I should learn to practice it consciously

**Comment by ben-manes** [comment]
> Can you please help me understand a bit more on your observation and where you are seeing the gap ?

@krmahadevan I ran your branch with and without this flag set on the gradle build.

```gradle
test {
  systemProperty 'testng.memory.friendly', 'true'
  jvmArgs'-XX:+HeapDumpOnOutOfMemoryError'
  maxHeapSize = '256m'
  useTestNG()
}
```

The OOME occurs at 328,858 with a memory profile of,
true

If the flag is disabled then the OOME occurs at 691,531 with a memory profile of,
false

Gradle's custom report doesn't retain the `TestNGMethod` so it is very light weight. Perhaps Maven uses the defaults, so the new `LiteWeightTestNGMethod` is helpful.

File: build.gradle.kts [hunk 6]
```diff
@@ -61,6 +61,7 @@ repositories {
 }
 
 plugins {
+    `maven`
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply build.gradle.kts:64]: Fixed. I added this only to facilitate local maven installations for testing purposes. Now moved over to using

```
id 'maven-publish'
```

File: src/main/java/org/testng/internal/TestInvoker.java [hunk 7]
```diff
@@ -259,15 +259,21 @@ private String checkDependencies(ITestNGMethod testMethod, ITestNGMethod[] allTe
...
+    if (!(context instanceof IConfigurationGroupMethodFetcher)) {
+      throw new TestNGException("context is not an instance of "
+          + IConfigurationGroupMethodFetcher.class.getName());
+    }
+
     // If this method depends on groups, collect all the methods that
     // belong to these groups and make sure they have been run successfully
     String[] groups = testMethod.getGroupsDependedUpon();
     if (null != groups && groups.length > 0) {
+    ITestNGMethod[] allTestMethods = ((IConfigurationGroupMethodFetcher) context).get().getAllTestMethods();
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestInvoker.java:271]: Refactored this and got rid of `IConfigurationGroupMethodFetcher` completely. We now just call `context.getAllTestMethods()` which internally would figure out how to honour the invocation.
While a `TestRunner` is still active (i.e., its still executing something), we always return back what we have already cached via a configuration object and outside of its execution, we always compute the test methods. 
The code path here is within the TestRunner being active, so it will now just retrieve values from the configuration object and so this implementation is no longer relevant or needed.

File: src/main/java/org/testng/internal/Utils.java [hunk 8]
```diff
@@ -600,4 +601,23 @@ public static String toString(Object obj) {
...
+        .map(Object::getClass)
+        .toArray(Class<?>[]::new);
+  }
+
+  public static String stringifyTypes(Class<?>[] parameterTypes) {
+    StringBuilder result = new StringBuilder();
+    int i = 0;
+    for (Class<?> p : parameterTypes) {
+      if (i++ > 0) {
+        result.append(", ");
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/Utils.java:616]: I refactored this to use streams

```
Arrays.stream(parameterTypes)
        .map(Class::getName)
        .collect(Collectors.joining(","));
```

File: src/main/java/org/testng/TestRunner.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:106]: yes, but in either case, this variable is redundant and is now going to be relevant only when the user runs in JUnit mode.
In all other times, we will now query `m_groupMethods` to get the test methods because we instantiate this object by computing `m_allTestMethods` and so, we don't need `m_allTestMethods` anymore (All it does is cause two references to the same set of memory allocations).

So now all the logic of what to query, and return back resides within `getAllTestMethods()` method.

File: src/main/java/org/testng/TestRunner.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:537]: Fixed but we will refer to `m_allTestMethods` only when we are in `JUnit` mode.

File: src/main/java/org/testng/TestRunner.java (hunk 3 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:542]: This is not needed. Please have a look at the new changes that I pushed in and we can further discuss based on that.

File: src/main/java/org/testng/TestRunner.java (hunk 4 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:681]: Fixed

File: src/main/java/org/testng/TestRunner.java (hunk 5 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:632]: Fixed

File: src/main/java/org/testng/TestRunner.java (hunk 4 above)
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:681]: If you remove this line, you'll have to remove `runMethods` too.
I'm not feeling it good because I can't imagine it is useless.
It looks the `allTestMethods` computation is different in the case of JUnit.

File: src/main/java/org/testng/TestRunner.java [hunk 9]
```diff
@@ -706,7 +707,7 @@ private void privateRun(XmlTest xmlTest) {
     // Make sure we create a graph based on the intercepted methods, otherwise an interceptor
     // removing methods would cause the graph never to terminate (because it would expect
     // termination from methods that never get invoked).
-    ITestNGMethod[] interceptedOrder = intercept(m_allTestMethods);
+    ITestNGMethod[] interceptedOrder = intercept(m_groupMethods.getAllTestMethods());
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:710]: Why `m_groupMethods.getAllTestMethods()` instead of `getAllTestMethods()`?

File: src/main/java/org/testng/internal/Utils.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (juherr) [reply src/main/java/org/testng/internal/Utils.java:616]: It looks like you forgot to push some commits

**Comment by krmahadevan** [comment]
@juherr - I have now pushed in the commit. Can you please take a look now ? I was testing the changes locally before pushing. I responded to the comments first

File: build.gradle.kts [hunk 10]
```diff
@@ -61,6 +61,7 @@ repositories {
 }
 
 plugins {
+    id("maven-publish")
```
Comment (juherr) [inline build.gradle.kts:64]: it is already defined on line 67

File: src/main/java/org/testng/TestRunner.java [hunk 11]
```diff
@@ -514,16 +507,10 @@ private void initMethods() {
...
-        MethodHelper.collectAndOrderMethods(
-            testMethods,
-            true /* forTest? */,
-            m_runInfo,
-            m_annotationFinder,
-            false /* unique */,
-            m_excludedMethods,
-            comparator);
-    m_classMethodMap = new ClassMethodMap(Arrays.asList(m_allTestMethods), m_xmlMethodSelector);
+    ITestNGMethod[] allTestMethods = computeAndGetAllTestMethods();
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:510]: Use `getAllTestMethods()` instead of `computeAndGetAllTestMethods`

File: src/main/java/org/testng/internal/BaseInvoker.java [hunk 12]
```diff
@@ -50,7 +50,7 @@ protected void runInvokedMethodListeners(
     }
 
     InvokedMethodListenerInvoker invoker =
-        new InvokedMethodListenerInvoker(listenerMethod, testResult, m_testContext);
+        new InvokedMethodListenerInvoker(listenerMethod, testResult, testResult.getTestContext());
```
Comment (juherr) [inline src/main/java/org/testng/internal/BaseInvoker.java:53]: Are you sure `m_testContext` and `testResult.getTestContext()` are always the same?

File: src/main/java/org/testng/internal/TestInvoker.java [hunk 13]
```diff
@@ -262,12 +262,13 @@ private String checkDependencies(ITestNGMethod testMethod, ITestNGMethod[] allTe
...
     // belong to these groups and make sure they have been run successfully
     String[] groups = testMethod.getGroupsDependedUpon();
+    ITestNGMethod[] allTestMethods = context.getAllTestMethods();
     if (null != groups && groups.length > 0) {
       // Get all the methods that belong to the group depended upon
       for (String element : groups) {
         ITestNGMethod[] methods =
             MethodGroupsHelper.findMethodsThatBelongToGroup(
-                testMethod, m_testContext.getAllTestMethods(), element);
+                testMethod, allTestMethods, element);
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestInvoker.java:271]: If `m_testContext` and `context` are always the same, you don't need any `context` param

File: src/main/java/org/testng/internal/XmlTestUtils.java [hunk 14]
```diff
@@ -0,0 +1,33 @@
+package org.testng.internal;
+
+import java.util.Map;
+import java.util.stream.Collectors;
+import org.testng.xml.XmlClass;
+import org.testng.xml.XmlInclude;
+import org.testng.xml.XmlTest;
+
+class XmlTestUtils {
```
[the remark this answers is not in the document]
Comment (juherr) [reply src/main/java/org/testng/internal/XmlTestUtils.java:9]: up

File: src/main/java/org/testng/TestRunner.java [hunk 15]
```diff
@@ -961,7 +970,18 @@ public ISuite getSuite() {
 
   @Override
   public ITestNGMethod[] getAllTestMethods() {
-    return m_allTestMethods;
+    if (m_allTestMethods != null) {
+      //This is true only when we are running JUnit mode
+      return m_allTestMethods;
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:975]: Has it is only used for JUnit, rename it `m_allJunitTestMethods`

File: src/main/java/org/testng/TestRunner.java [hunk 16]
```diff
@@ -961,7 +970,18 @@ public ISuite getSuite() {
...
+    }
+    if (m_groupMethods != null) {
+      //Be it memory friendly mode or normal mode, we still have a
+      // configuration object that remembers all the test methods. So we always query it
+      return m_groupMethods.getAllTestMethods();
+    }
+    //If we are here, then it means that its ok to compute the methods every time
+    // Since we aren't being invoked from the core test execution code path.
+    return computeAndGetAllTestMethods();
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:984]: The last question is: if `m_groupMethods` is null here, why not creating one here with the `computeAndGetAllTestMethods`?
Or having another king of cache.

File: src/main/java/org/testng/internal/BaseInvoker.java (hunk 12 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/BaseInvoker.java:53]: Yep. They will always be the same. Every TestResult object is always bound to the `ITestContext` to which it belongs.

File: src/main/java/org/testng/internal/TestInvoker.java (hunk 13 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestInvoker.java:271]: There's a bit of clean-up that is needed to be done with respect to `ITestContext`. So I would want to handle this as a separate PR.

File: src/main/java/org/testng/TestRunner.java (hunk 15 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: fixed

File: src/main/java/org/testng/TestRunner.java (hunk 16 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:984]: It is going to be null only when a user turns on memory friendly mode and in that mode it has to be null.

File: build.gradle.kts (hunk 10 above)
Comment (krmahadevan) [reply build.gradle.kts]: Ah ok. My bad. I didnt realise this. Fixed

File: src/main/java/org/testng/TestRunner.java (hunk 11 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: fixed.

File: src/main/java/org/testng/internal/XmlTestUtils.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/XmlTestUtils.java]: fixed

**Comment by krmahadevan** [comment]
@juherr - I again addressed all the review comments and have pushed in the changes. Please take a look

**Comment by krmahadevan** [comment]
@juherr - Please let me know if there is anything outstanding that needs to be addressed before we can merge this.

File: src/main/java/org/testng/TestRunner.java [hunk 17]
```diff
@@ -664,8 +673,8 @@ public void run() {
 
           @Override
           public int getPriority() {
-            if (m_allTestMethods.length == 1) {
-              return m_allTestMethods[0].getPriority();
+            if (m_allJunitTestMethods.length == 1) {
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:676]: I think a NPE is possible here.

File: src/main/java/org/testng/TestRunner.java [hunk 18]
```diff
@@ -544,9 +531,22 @@ private void initMethods() {
             true /* unique */,
             m_excludedMethods,
             comparator);
-    // shared group methods
```
[the remark this answers is not in the document]
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java:547]: Could you confirm it is an unexpected change without any side effects?

File: src/main/java/org/testng/TestRunner.java [hunk 19]
```diff
@@ -961,7 +970,18 @@ public ISuite getSuite() {
 
   @Override
   public ITestNGMethod[] getAllTestMethods() {
-    return m_allTestMethods;
+    if (m_allJunitTestMethods != null) {
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:973]: What do you think if we use `m_xmlTest.isJUnit()` instead here?

File: src/main/java/org/testng/TestRunner.java [hunk 20]
```diff
@@ -961,7 +970,18 @@ public ISuite getSuite() {
...
+      //This is true only when we are running JUnit mode
+      return m_allJunitTestMethods;
+    }
+    if (m_groupMethods != null) {
+      //Be it memory friendly mode or normal mode, we still have a
+      // configuration object that remembers all the test methods. So we always query it
+      return m_groupMethods.getAllTestMethods();
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:980]: It is working but the design smells a bit here because there are 2 different purposes: 

1. The TestRunner "cache" should work with or without `m_groupMethods` (imagine we want to drop `getAllTestMethods` from `m_groupMethods`) ;
2. If the "cache" notion is shared between different objects, we can share it by a holder object and manage it in a single point. (it will be easier to follow the cache management)

**Review by juherr — COMMENTED** [review]
Sorry if this PR is taking time but the changes are more risky than usual.

File: src/main/java/org/testng/TestRunner.java (hunk 20 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:980]: @juherr - So you are basically suggesting that we refactor both `TestRunner` and `ConfigurationGroupMethods` so that it uses a test method cache ? I can give that a try.

**Comment by juherr** [comment]
@ben-manes Could you check the latest changes from the branch and tell us what is your opinion about the result?

File: src/main/java/org/testng/TestRunner.java (hunk 20 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:980]: @juherr - Just for the sake of argument, why cant we treat `ConfigurationGroupMethods ` as that cache ? This class will not go away for sure unless and until we have drastically changed TestNG behavior, and it needs all the test methods references. So why not just have it also play an additional role of being the cache without it being the cache ? Something like a side effect of its original working ? I am not quite sure as to why that would not make sense ? What additional benefit is the holder object going to give us (Apart from it being just a POJO) ?

Comment (juherr) [reply src/main/java/org/testng/TestRunner.java:980]: Your solution is working and it is just a naming issue: I'm not sure to understand what is the purpose of `ConfigurationGroupMethods`.
I mean `ConfigurationGroup` methods don't match well with `all` methods.

Then I've just checked and according to the documentation:
> This class wraps access to beforeGroups and afterGroups methods, since they are passed around the
> various invokers and potentially modified in different threads.

Clearly, its responsibility cannot be a cache. 
But a cache can be easily shared between classes without any problem.

File: src/main/java/org/testng/TestRunner.java (hunk 17 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:681]: Fixed

File: src/main/java/org/testng/TestRunner.java (hunk 19 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: Fixed as recommended

File: src/main/java/org/testng/TestRunner.java (hunk 20 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: Fixed

**Comment by krmahadevan** [comment]
@juherr - I have fixed the review comments that you shared and pushed in the changes again as a new commit this time. Please help take a look.

File: src/main/java/org/testng/TestRunner.java [hunk 21]
```diff
@@ -514,16 +511,9 @@ private void initMethods() {
...
-            testMethods,
-            true /* forTest? */,
-            m_runInfo,
-            m_annotationFinder,
-            false /* unique */,
-            m_excludedMethods,
-            comparator);
-    m_classMethodMap = new ClassMethodMap(Arrays.asList(m_allTestMethods), m_xmlMethodSelector);
+    testMethodsContainer = new TestMethodContainer(getAllTestMethods());
+    m_classMethodMap = new ClassMethodMap(Arrays.asList(testMethodsContainer.getItems()), m_xmlMethodSelector);
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:515]: Note for later: use TestMethodContainer in ClassMethodMap too

File: src/main/java/org/testng/TestRunner.java [hunk 22]
```diff
@@ -514,16 +511,9 @@ private void initMethods() {
...
-        MethodHelper.collectAndOrderMethods(
-            testMethods,
-            true /* forTest? */,
-            m_runInfo,
-            m_annotationFinder,
-            false /* unique */,
-            m_excludedMethods,
-            comparator);
-    m_classMethodMap = new ClassMethodMap(Arrays.asList(m_allTestMethods), m_xmlMethodSelector);
+    testMethodsContainer = new TestMethodContainer(getAllTestMethods());
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:514]: Tips: Could be lazy-loaded with a Function: `() -> getAllTestMethods()`

File: src/main/java/org/testng/TestRunner.java [hunk 23]
```diff
@@ -792,10 +806,10 @@ private void privateRun(XmlTest xmlTest) {
 
     // Check if an interceptor had altered the effective test method count. If yes, then we need to
     // update our configurationGroupMethod object with that information.
-    if (resultArray.length != m_groupMethods.getAllTestMethods().length) {
+    if (resultArray.length != testMethodsContainer.getItems().length) {
       m_groupMethods =
           new ConfigurationGroupMethods(
-              resultArray,
+              new TestMethodContainer(resultArray),
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:812]: I see a potential issue because our previous assumption was: TestRunner and ConfigurationGroupMethods share the same method cache.
But here, we see it is not the case because we are creating a new ConfigurationGroupMethods with another cache.

File: src/main/java/org/testng/TestRunner.java [hunk 24]
```diff
@@ -961,7 +975,16 @@ public ISuite getSuite() {
 
   @Override
   public ITestNGMethod[] getAllTestMethods() {
-    return m_allTestMethods;
+    if (getTest().isJUnit()) {
+      //This is true only when we are running JUnit mode
+      return m_allJunitTestMethods;
+    }
+    if (Objects.nonNull(testMethodsContainer) && testMethodsContainer.hasItems()) {
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:982]: If testMethodsContainer is null or has no items, why not creating/updating here with computed methods?

File: src/main/java/org/testng/internal/ConfigurationGroupMethods.java [hunk 25]
```diff
@@ -37,18 +37,14 @@
   private volatile Map<String, List<ITestNGMethod>> m_afterGroupsMap = null;
 
   public ConfigurationGroupMethods(
-      ITestNGMethod[] allMethods,
+      IContainer<ITestNGMethod> container,
       Map<String, List<ITestNGMethod>> beforeGroupsMethods,
       Map<String, List<ITestNGMethod>> afterGroupsMethods) {
-    m_allMethods = allMethods;
+    m_allMethods = container.getItems();
```
Comment (juherr) [inline src/main/java/org/testng/internal/ConfigurationGroupMethods.java:43]: For now, ok but the cache modification won't be triggered here.
`m_allMethods` should be replaced by `container`

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java:812]: In fact, it only shows that m_groupMethods was not a good object for the cache.

So now, `TestMethodContainer` is just another way to restore `m_allTestMethods` and a wrapper object is no more a big help.
We can keep it or not, I let you the choice.

File: src/main/java/org/testng/internal/BaseInvoker.java (hunk 12 above)
Comment (juherr) [reply src/main/java/org/testng/internal/BaseInvoker.java:53]: I could be nice to assert it: `assert m_testContext == testResult.getTestContext()`

File: src/main/java/org/testng/internal/IContainer.java [hunk 26]
```diff
@@ -0,0 +1,22 @@
...
+
+/**
+ * Represents the capabilities of a simple container to hold data
+ */
+public interface IContainer<M> {
+
+  /**
+   * @return - Retrieves data from the container
+   */
+  M[] getItems();
```
Comment (juherr) [inline src/main/java/org/testng/internal/IContainer.java:11]: Note for later: prefer to use a `Collection` because the modifications of the cache will be triggered in references.

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:812]: @juherr - True that. But I dont get as to what the potential issue now you are talking about because we now have gotten rid of the side effect of relying on `ConfigurationGroupMethods`. So I didnt quite understand what should I be fixing here ?

File: src/main/java/org/testng/TestRunner.java (hunk 24 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:982]: @juherr - No that is not the intent. Cache should not be re-created in this case.

When running in memory friendly mode and within the context of test execution, the cache will always be valid and it gets explicitly nullified after the test execution is complete. So all invokers of `ITestContext.getAllTestMethods()` will resort to explicit computation (the only situation when this would be invoked is during reporting phase and I think its ok to calculate all the methods.
in the usual mode (ie., no memory friendly mode) the cache is never null (or) empty. So this is not needed

File: src/main/java/org/testng/internal/ConfigurationGroupMethods.java (hunk 25 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ConfigurationGroupMethods.java:43]: The cache is never meant to be modified so this is fine.

File: src/main/java/org/testng/internal/IContainer.java (hunk 26 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/IContainer.java:11]: The cache has only 1 utilisation right now which is within TestRunner and in that context, the cache is never meant to be updated.

File: src/main/java/org/testng/TestRunner.java (hunk 22 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:514]: I am not sure if we are going to be getting a lot of help with lazy loading.

**Comment by ben-manes** [comment]
@juherr Unfortunately these changes do not fix the problem yet, but may be close. It appears that the remaining hold is from ResultMap.

Screen Shot 2020-10-26 at 9 44 11 AM
Screen Shot 2020-10-26 at 9 47 18 AM

File: src/main/java/org/testng/TestRunner.java (hunk 24 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java:982]: The code is not as clear as your explanations ;)
My point is the cache management should be the easiest possible and be understandable without the knowledge of the assumption you mentioned. That's why I'd like to apply here the default pattern of the cache management.

At least, I think you should add comments because they will help later.

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java:812]: There is nothing to change here.
The potential issue was if the expected method list had to be the same in both cases. It looks it is not the case.

As it is not the case, `TestMethodContainer` is no more useful.

File: src/main/java/org/testng/TestRunner.java (hunk 22 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java:514]: You are right. It was just for fun ;)

**Comment by juherr** [comment]
@ben-manes Thanks for the feedback. `ResultMap` will be more difficult to manage: as I remember, it should be optional only used in the report context. But it is currently not the case because the run part is too highly coupled with the report part.

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:812]: Ok. So I guess this was an observation behind the ask for creating a separate cache/container for holding test methods so that we rule out all side effects and we stick to single responsibility principle. Point taken. Resolving this conversation

**Comment by krmahadevan** [comment]
@juherr - I have added some more refactoring (That hint of using a function for the cache, turned out to be relevant after all.. so thanks for that). Now all of the logic for managing the cache vs going on-demand is hidden behind the newly introduced `TestMethodContainer`. Please help take another look.

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java]: I asked for a distinct object cache because my understanding at this moment was that the cache was a shared thing.
Your previous commit highlighted that it was not the case and my ask was less pertinent.

My current conclusion is: there are 2 different methods cache at 2 different places and we cannot merge their usage into a single place.

File: src/main/java/org/testng/TestRunner.java [hunk 27]
```diff
@@ -99,16 +102,10 @@
...
-   * methods might belong to different classes. We pick which ones to run at runtime.
-   */
-  private ITestNGMethod[] m_allTestMethods = new ITestNGMethod[0];
-
-  // Information about this test run
-
   private Date m_startDate = new Date();
   private Date m_endDate = null;
+  private final IContainer<ITestNGMethod> testMethodsContainer =
+      new TestMethodContainer(this::computeAndGetAllTestMethods);
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:108]: Awesome, you did it :D

File: src/main/java/org/testng/TestRunner.java [hunk 28]
```diff
@@ -792,10 +805,10 @@ private void privateRun(XmlTest xmlTest) {
 
     // Check if an interceptor had altered the effective test method count. If yes, then we need to
     // update our configurationGroupMethod object with that information.
-    if (resultArray.length != m_groupMethods.getAllTestMethods().length) {
+    if (resultArray.length != testMethodsContainer.getItems().length) {
       m_groupMethods =
           new ConfigurationGroupMethods(
-              resultArray,
+              new TestMethodContainer(()-> resultArray),
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java:811]: Typo: space missing

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: @juherr - yes that is correct. I guess I may have opened up the pandora's box for all the wrong reasons :) But that's fine. We can iterate on this to streamline and make things better. In the meantime, please do take another look at the latest changes that I now added as an additional commit.

File: src/main/java/org/testng/internal/TestMethodWorker.java [hunk 29]
```diff
@@ -277,7 +277,7 @@ public boolean completed() {
 /** Extends {@code TestMethodWorker} and is used to work on only a single method instance */
 class SingleTestMethodWorker extends TestMethodWorker {
   private static final ConfigurationGroupMethods EMPTY_GROUP_METHODS =
-      new ConfigurationGroupMethods(new ITestNGMethod[0], new HashMap<>(), new HashMap<>());
+      new ConfigurationGroupMethods(new TestMethodContainer(()->new ITestNGMethod[0]), new HashMap<>(), new HashMap<>());
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestMethodWorker.java:280]: Typo: spaces missing

File: src/main/java/org/testng/internal/TestMethodContainer.java [hunk 30]
```diff
@@ -0,0 +1,50 @@
...
+    }
+    if (methods == null) {
+      //The first time we are here, methods would be null. So lets lazily initialise it.
+      methods = supplier.get();
+    }
+    return methods;
+  }
+
+  @Override
+  public boolean isCleared() {
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestMethodContainer.java:38]: It looks like the method is never used and I'm sure about the logic behind it. Could you remove it?

Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestMethodContainer.java:38]: Its currently used internally. Semantically I felt it would be correct ONLY if there was that method that would tell the consumer if the container was cleared or not.

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java]: There are many pandora boxes everywhere. :D And my objective is always to limit the little workarounds which are making more complexity on the whole picture! ;)

File: src/main/java/org/testng/TestRunner.java (hunk 27 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java:108]: yeah, the hint that you shared helped :) and once I added it, it became more easy to toggle between cache and on-demand evaluation.

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: True that and completely agree with you on that. Apart from the formatting changes, are there any other things that need to be taken care of ?

File: src/main/java/org/testng/internal/TestMethodContainer.java (hunk 30 above)
Comment (juherr) [reply src/main/java/org/testng/internal/TestMethodContainer.java:38]: It's a pattern I've never met but keep it if you think it is important.

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (juherr) [reply src/main/java/org/testng/TestRunner.java]: > are there any other things that need to be taken care of?

No. Feel free to merge :)

File: src/main/java/org/testng/internal/TestMethodWorker.java (hunk 29 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestMethodWorker.java]: Fixed

File: src/main/java/org/testng/TestRunner.java (hunk 28 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: Fixed

File: src/main/java/org/testng/TestRunner.java (hunk 23 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: I have merged the changes. Thanks for helping me out with reviewing this PR @juherr
