### PR TITLE
Prevent duplicate instances of Reporter from being wired in.

### LINKED ISSUE #1227: Issue in org.testng.TestNG.generateReports method
```java
private void generateReports(List<ISuite> suiteRunners) {
    for (IReporter reporter : m_reporters) {
      try {
        long start = System.currentTimeMillis();
        reporter.generateReport(m_suites, suiteRunners, m_outputDir);
        Utils.log("TestNG", 2, "Time taken by " + reporter + ": "
            + (System.currentTimeMillis() - start) + " ms");
      }
      catch(Exception ex) {
        System.err.println("[TestNG] Reporter " + reporter + " failed");
        ex.printStackTrace(System.err);
      }
    }
  }
```

I am executing multiple Test classes. When I use `@Listeners(EmailableReporter.class)` at Test class level, this method invokes the reporter.generateReport as many times as the number of Test classes I have. The actual report with all the suites and test cases is generated at first invocation of the report itself.

Need to add a check to invoke generateReport method of an IReporter only once.

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes # .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

Fixes #1227

* Added checks to ensure that duplicate instances of a reporter
are not being injected into TestNG.
* Also added unit tests.

### CODE REVIEW

File: src/main/java/org/testng/TestNG.java [hunk 1]
```diff
@@ -821,7 +822,9 @@ public void addInvokedMethodListener(IInvokedMethodListener listener) {
   }
 
   public Set<IReporter> getReporters() {
-    return m_reporters;
+    //This will now cause a different behavior for consumers of this method because unlike before they are no longer
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: I'm not sure the comment has some added value because once merged, it is done. But the information could be place in the commit message instead.

File: src/test/java/test/reports/UniqueReporterInjectionTest.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    public void testPruningOfDuplicateReporter() {
+        XmlSuite xmlSuite = createXmlSuite("Suite");
+        XmlTest xmlTest = createXmlTest(xmlSuite, "Test");
+        createXmlClass(xmlTest, UniqueReporterInjectionSample1.class);
+        createXmlClass(xmlTest, UniqueReporterInjectionSample2.class);
+        TestNG tng = create(xmlSuite);
+        tng.setUseDefaultListeners(false);
+        tng.addListener((ITestNGListener) new ReporterListenerForIssue1227());
+        tng.run();
+        Assert.assertTrue(tng.getReporters().size() == 1);
```
Comment (juherr) [inline src/test/java/test/reports/UniqueReporterInjectionTest.java]: Why not `Assert.assertEquals(tng.getReporters().size(), 1)`?

File: src/main/java/org/testng/TestNG.java [hunk 3]
```diff
@@ -927,7 +930,7 @@ private void initializeCommandLineSuitesGroups() {
     }
   }
   private void addReporter(Class<? extends IReporter> r) {
-    m_reporters.add(ClassHelper.newInstance(r));
+    m_reporters.put(r, ClassHelper.newInstance(r));
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: We can avoid the instance creation if the reporter already exist

File: src/test/java/test/reports/UniqueReporterInjectionTest.java [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+    }
+
+    public static class ReporterListenerForIssue1227 implements IReporter {
+        @Override
```
Comment (juherr) [inline src/test/java/test/reports/UniqueReporterInjectionTest.java]: We can count the number of instances created and check it.

**Review by juherr — CHANGES_REQUESTED** [review]
Good job, only few improvements are needed :)

File: src/main/java/org/testng/TestNG.java [hunk 5]
```diff
@@ -137,7 +137,7 @@
   private List<IClassListener> m_classListeners = Lists.newArrayList();
   private List<ITestListener> m_testListeners = Lists.newArrayList();
   private List<ISuiteListener> m_suiteListeners = Lists.newArrayList();
-  private Set<IReporter> m_reporters = Sets.newHashSet();
+  private Map<Class< ? extends IReporter>,IReporter> m_reporters = Maps.newHashMap();
```
Comment (krmahadevan) [inline src/main/java/org/testng/TestNG.java]: I am guessing you meant `bad formatting` when you said `typo`. Correct ? Fixed the formatting.

File: src/main/java/org/testng/TestNG.java [hunk 6]
```diff
@@ -804,7 +805,7 @@ public void addListener(IClassListener listener) {
   // TODO remove later
   @Deprecated
   public void addListener(IReporter listener) {
-    if (!m_reporters.contains(listener)) {
+    if (!m_reporters.values().contains(listener)) {
```
Comment (krmahadevan) [inline src/main/java/org/testng/TestNG.java]: Thanks for pointing it out. Fixed it.

File: src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [inline src/main/java/org/testng/TestNG.java]: If you would want, I can add this at the comments also, but I thought that this comment would add value in the code, because the moment someone experiences a different behaviour (as documented by the comment), they would be looking at the code and then read this comment. If anyone would want to tie this change back to a commit, then a `git blame` would also do the trick. But I will add this to the comment message as well.

File: src/main/java/org/testng/TestNG.java (hunk 3 above)
Comment (krmahadevan) [inline src/main/java/org/testng/TestNG.java]: Took care of this.

File: src/test/java/test/reports/UniqueReporterInjectionTest.java (hunk 2 above)
Comment (krmahadevan) [inline src/test/java/test/reports/UniqueReporterInjectionTest.java]: Please let me know if there are any reasons as to if there can be any problems with using `assertTrue` over `assertEquals`

**Comment by krmahadevan** [comment]
@juherr - I have addressed the review comments and also responded to the review callouts with my response, in places where I haven't fixed review comments. Please let me know if there is anything more needed from my side.

File: src/main/java/org/testng/TestNG.java (hunk 5 above)
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Yes 👍

File: src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Ok why not :)

File: src/test/java/test/reports/UniqueReporterInjectionTest.java (hunk 2 above)
Comment (juherr) [inline src/test/java/test/reports/UniqueReporterInjectionTest.java]: `assertTrue` is working too but I think `assertEquals` is providing more feedback in reports ("true/false" vs "x/1"). (x can be an important clue)

File: src/test/java/test/reports/UniqueReporterInjectionTest.java (hunk 4 above)
Comment (juherr) [inline src/test/java/test/reports/UniqueReporterInjectionTest.java]: We expect only one instance creation of the reporter:

```java
public static class ReporterListenerForIssue1227 implements IReporter {
  public static int INSTANCE_COUNT = 0;

  public ReporterListenerForIssue1227() {
    INSTANCE_COUNT++;
  }
  ...
}
```
and
```java
Assert.assertEquals(ReporterListenerForIssue1227.INSTANCE_COUNT, 1);
```

File: src/test/java/test/reports/UniqueReporterInjectionTest.java (hunk 2 above)
Comment (krmahadevan) [inline src/test/java/test/reports/UniqueReporterInjectionTest.java]: Changed the assertion to use `assertEquals`

**Comment by krmahadevan** [comment]
@juherr - I have addressed the review comments related to the tests and also rebased the branch to fix merge conflicts. Please help take a look

**Review by juherr — APPROVED** [review]

**Comment by juherr** [comment]
LGTM (if travis passes) 👍 Ping @cbeust

**Comment by cbeust** [comment]
`CHANGES.txt` has conflicts, will merge once @krmahadevan has resolved them.

**Comment by krmahadevan** [comment]
@cbeust - I have resolved the merge conflicts with `CHANGES.txt`
