### PR TITLE
Stream Retry analyzer usage

### LINKED ISSUE #1241: IRetryAnalyzer : Not able to re-run failed tests when same tests are being run multiple times
When the retry count is set to 1 from retry listener, From the below sample test, test2() method is run for the second time for Test with <test name="Test One"> (refer testng.xml below) where as when i invoke the same set of tests for the second time with <test name="Test Two">, test2() method is not run for the second time though it has failed.

### Expected behavior
Listeners are used to retry test failed tests.
Since test2() fails in first attempt, it should re-run test2() for <test name="Test One"> and <test name="Test Two">

### Actual behavior
Listeners are used to retry test failed tests.
test2() is re-runs for <test name="Test One"> where as for <test name="Test Two"> test2() fails the first time and it is not re-run for second time

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

I have implemented listener class as following : http://stackoverflow.com/questions/28208202/retry-failed-test-case-in-testng/36320794#36320794

Below is my test case

```java
import org.testng.Assert;
import org.testng.annotations.Test;
public class SampleTest {
	@BeforeTest
	public void setup(ITestContext context){
		System.out.println("inside setup.."+context.getCurrentXmlTest().getName());
	}
	
	@Test(priority=1)
	public void test1(){
		System.out.println("inside test1()...");
		Assert.assertTrue(true);
	}
	
	@Test(priority=2)
	public void test2(){
		System.out.println("inside test2()...");
		Assert.assertTrue(false);
	}
}
```

Below is my XML
```xml
<suite name="Test Suite" verbose="1">
	<test name="Test One">
		<classes> <class name="com.example.SampleTest" > </classes>
	</test>
	<test name="Test Two">
		<classes> <class name="com.example.SampleTest" > </classes>
	</test>
        <listeners> <listener class-name="com.example.RetryListener"/> </listeners>
</suite>
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1241

Fixed a discrepancy wherein users are not able to 
re-run failed tests when same tests are being run 
multiple times using a retry analyzer.

Unrelated change:
* General code clean-up.
* Refactoring of code to use Lambdas

Fixes #1241  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/annotations/TestAnnotation.java [hunk 1]
```diff
@@ -168,21 +168,21 @@ public void setSequential(boolean sequential) {
 
   @Override
   public IRetryAnalyzer getRetryAnalyzer() {
```
Comment (juherr) [inline src/main/java/org/testng/internal/annotations/TestAnnotation.java]: I don't catch the change here: a new instance will be created for each get.
And set should throw an exception if the provided class is not a retry analyzer.

**Review by juherr — APPROVED** [review]

File: src/main/java/org/testng/internal/annotations/TestAnnotation.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/annotations/TestAnnotation.java]: @juherr - A new instance would be created for each get, but a `get` is invoked only when a new `TestNGMethod` object is created. So we are good there. 
I am not sure as to how would a user get to the part of setting an invalid class via the setter even when using the TestNG APIs. So I chose to skip the exception part. We take in whatever class the user provides, but we instantiate it only if its of type `IRetryAnalyzer` and in all other cases, we return a `null`.

Comment (juherr) [reply src/main/java/org/testng/internal/annotations/TestAnnotation.java]: It is error-prone because it is currently right but it can change.
Same thing for the null instead of exception: it will silently fail.

Comment (krmahadevan) [reply src/main/java/org/testng/internal/annotations/TestAnnotation.java]: @juherr 

> It is error-prone because it is currently right but it can change.
Fair enough. I decided to tackle this differently. I left the functionality as is, but modified `TestNGMethod` to create a new instance based on the instance that we get from the actual annotation and work with that instead. Its like cloning, but I just grab hold of the class and use reflection to create a new instance.

> Same thing for the null instead of exception: it will silently fail.
`null` instead of exception piece is basically what is the current behavior as well. Since we cannot possibly inject a non-adhering implementation for retry analyzer, I chose to retain the behavior as is.

File: src/main/java/org/testng/internal/annotations/TestAnnotation.java [hunk 2]
```diff
@@ -172,16 +172,16 @@ public IRetryAnalyzer getRetryAnalyzer() {
   }
 
   @Override
-  public void setRetryAnalyzer(Class<?> c) {
+  public void setRetryAnalyzer(Class<? extends IRetryAnalyzer> c) {
```
Comment (krmahadevan) [inline src/main/java/org/testng/internal/annotations/TestAnnotation.java]: @juherr - So here we have simplified the case, and gotten rid of the instance check. We still need to silently gobble down the inability to instantiate the class, because the default value is `Class` (Annotations doesn't accept null as a valid value) and `Class` cannot be instantiated. So if we threw exceptions here, then we would end up throwing exceptions for literally every case, wherein a user doesn't use a valid retry analyzer which kind of breaks backward compatibility in a big way.

**Comment by krmahadevan** [comment]
ping @cbeust - Can you please help merge if you are fine with the changes

File: src/main/java/org/testng/internal/annotations/TestAnnotation.java (hunk 2 above)
Comment (juherr) [reply src/main/java/org/testng/internal/annotations/TestAnnotation.java]: If you really want to be clean on this subject, the default retryAnalyzer class should be a real IRetryAnalyzer and we should warn the users if the one they provide is not an IRetryAnalyzer. It will allow us to prepare the change of the annotation definition (from Class to Class<? extends IRetryAnalyzer>).

**Comment by krmahadevan** [comment]
@juherr

>  the default retryAnalyzer class should be a real IRetryAnalyzer and we
should warn the users if the one they provide is not an IRetryAnalyzer.

How do you propose we do this ? We could alter the annotation's default
value from "Class" to some other Class, which implements IRetryAnalyzer but
whose retry() method always returns false.
I dont quite understand the "Warn the users" part that you are talking
about.

**Comment by juherr** [comment]
> We could alter the annotation's default value from "Class" to some other Class, which implements IRetryAnalyzer but whose retry() method always returns false.

That's exactly the idea! 👍 

> I don't quite understand the "Warn the users" part that you are talking about.

The annotation currently accepts any class. We already can force it to `Class<? extends IRetryAnalyzer>` (little-breaking change but allowed for a major version and the fix should be quick for users). Another option is keeping `Class` but we should check the type somewhere (I suppose we have a warning somewhere where we force the `Class` into a `Class<? extends IRetryAnalyzer>`.
In fact, I prefer the 1st solution.

**Comment by krmahadevan** [comment]
@juherr - I would like to make the last change viz., Use a `Class<? extends IRetryAnalyzer>` as a parameter type in the `@Test` annotation as a separate change. I tried doing the changes locally and I seem to be breaking some tests. I dont want to club that with this delivery. I hope that is fine with you.

File: src/main/java/org/testng/internal/annotations/TestAnnotation.java [hunk 3]
```diff
@@ -172,16 +173,9 @@ public IRetryAnalyzer getRetryAnalyzer() {
...
-
-    if (c != null && IRetryAnalyzer.class.isAssignableFrom(c)) {
-      try {
-        m_retryAnalyzer = (IRetryAnalyzer) c.newInstance();
-      }
-      catch (InstantiationException | IllegalAccessException e) {
-        // The class will never be called.
-      }
+  public void setRetryAnalyzer(Class<? extends IRetryAnalyzer> c) {
+    if (isRetryAnalyzerNotTestNGInjected(c)) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/annotations/TestAnnotation.java]: It should not be a problem if `DisabledRetryAnalyzer.class` is passed

**Comment by juherr** [comment]
Ping @cbeust

**Review by cbeust — APPROVED** [review]
