### PR TITLE
Null fields in parallel method tests

### LINKED ISSUE #1625: Null fields in parallel method tests
This occurs in 6.13 and was working in 6.12.

```java
public final class BeforeClassTest {
  @Mock List<String> list;

  @BeforeClass
  public void beforeClass() {
    MockitoAnnotations.initMocks(this);
  }

  @Test
  public void first() {
    Assert.assertNotNull(list);
  }

  @Test
  public void second() {
    Assert.assertNotNull(list);
  }
}
```

The `first` test passes and the `second` test fails with an NPE.
```
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.assertNotNull(Assert.java:686)
	at org.testng.Assert.assertNotNull(Assert.java:671)
```

If `@Test(singleThreaded = true)` is added to the class, then both tests succeed.

Strangely, when I replace the mock initialization with `list = new ArrayList<>();` then they both pass. I suspect there's some trigger in whether the methods were parallelized or not.

This occurs in my project and can be reproduced there as,
```
$ gradle strongKeysAndStrongValuesStatsSyncCaffeineTest \
    -DstrongKeysAndStrongValuesStatsSyncCaffeineTest.single=CaffeineTest
```
after upgrading the version in `dependency.gradle`

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1625

Caused by 
SHA: f622b85b22a0b9751f4ad125d141f440c87746a4

Un-related changes.
Cleaned up BeforeClassThreadTest to use assertions

Fixes #1625 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @cbeust - Can you please help review ? Looks like @juherr maybe busy

File: src/main/java/org/testng/internal/TestMethodWorker.java [hunk 1]
```diff
@@ -148,24 +148,30 @@ protected void invokeBeforeClassMethods(ITestClass testClass, IMethodInstance mi
...
-    }
-    Object instance = mi.getInstance();
-    if (!instances.contains(instance)) {
-      instances.add(instance);
-      for (IClassListener listener : m_listeners) {
-        listener.onBeforeClass(testClass);
+    // Synchronization on local variables is generally considered a bad practice, but this is an exception.
+    // We need to ensure that two threads that are querying for the same "Class" then they
+    // should be mutually exclusive. In all other cases, parallelism can be allowed.
+    //DONOT REMOVE THIS SYNC LOCK.
```
Comment (cbeust) [inline src/main/java/org/testng/internal/TestMethodWorker.java]: DO NOT

**Review by cbeust — COMMENTED** [review]
Feel free to merge after fixing the typo.

Thanks!

**Comment by krmahadevan** [comment]
Thanks @cbeust . Have fixed the typo, amended the commit and merged the changes.

File: src/test/java/test/configuration/github1625/TestclassSampleUsingMocks.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+import java.util.List;
+
+public class TestclassSampleUsingMocks {
+    @Mock
+    List<String> list;
+
+
+    @BeforeClass
+    public void beforeClass() {
+        MockitoAnnotations.initMocks(this);
```
Comment (juherr) [inline src/test/java/test/configuration/github1625/TestclassSampleUsingMocks.java]: Fyi, a `MockitoTestNGListener` exists too (but it won't follow the sample from the issue) :)
