### PR TITLE
Honour inheritance when parsing listener factories

### LINKED ISSUE #3095: Super class annotated with ITestNGListenerFactory makes derived test class throw TestNGException on execution
### TestNG Version
7.9.0

### Expected behavior
No problems running test method in derived test class where ITestNGListenerFactory annotation is present on super class.

### Actual behavior
TestNG crashes during load:

```
org.testng.TestNGException: Found more than one class implementing ITestNGListenerFactory:class com.test.MyTestNgFactory and class com.test.MyTestNgFactory
	at org.testng.internal.TestListenerHelper.lambda$findAllListeners$0(TestListenerHelper.java:149)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.internal.TestListenerHelper.findAllListeners(TestListenerHelper.java:139)
	at org.testng.TestRunner.initListeners(TestRunner.java:374)
	at org.testng.TestRunner.init(TestRunner.java:357)
	at org.testng.TestRunner.init(TestRunner.java:307)
	at org.testng.TestRunner.<init>(TestRunner.java:182)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:652)
	at org.testng.SuiteRunner.init(SuiteRunner.java:224)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:116)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1396)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1370)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1219)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```

This is a regression in 7.9.0 as it was never seen in 7.8.0 or prior versions.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
Running ChildClass#test() throws exception above.

```java
@Listeners(MyTestNgFactory.class)
public static class SuperClass {
}

public static class ChildClass extends SuperClass {
    @Test
    public void child() {
    }
}

public static class MyTestNgFactory implements ITestNGListener, ITestNGListenerFactory {
    @Override
    public ITestNGListener createListener(Class<? extends ITestNGListener> listenerClass) {
        return null;
    }
}
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #3095

Fixes #3095  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

**Root cause:** TestNG was enhanced such that the `@Listeners` annotation was inheritable via the PR https://github.com/testng-team/testng/pull/3002

## Summary by CodeRabbit

- **Bug Fixes**
	- Addressed issues with test execution behavior, including test class inheritance and method interception.
- **New Features**
	- Improved handling and uniqueness of listener annotations in test execution.
	- Enhanced management of listener factories for more effective test listener integration.
- **Refactor**
	- Streamlined test listener logic for better efficiency and clarity.
	- Introduced new test classes and methods for improved testing of listener inheritance and factory functionality.
- **Tests**
	- Added new tests to ensure correct handling of listener inheritance and listener factory behavior.

### CODE REVIEW

File: testng-core/src/main/java/org/testng/internal/TestListenerHelper.java [hunk 1]
```diff
@@ -196,9 +176,37 @@ public static ITestNGListenerFactory createListenerFactory(
...
     private Class<? extends ITestNGListenerFactory> listenerFactoryClass;
 
+    @SuppressWarnings("unchecked")
+    public void addListener(Class<? extends ITestNGListener> c) {
+      // @Listener annotation is now inheritable. So let's add it ONLY
+      // if it wasn't added already
+      if (!listenerClasses.contains(c)) {
+        listenerClasses.add(c);
+      }
+      boolean isListenerFactory = ITestNGListenerFactory.class.isAssignableFrom(c);
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/internal/TestListenerHelper.java:189]: The logic if not clear. Please introduce a private setListenerFactory

**Review by juherr — CHANGES_REQUESTED** [review]

File: testng-core/src/main/java/org/testng/internal/TestListenerHelper.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/internal/TestListenerHelper.java]: Refactored and pushed. Please check now.

File: testng-core/src/main/java/org/testng/internal/TestListenerHelper.java [hunk 2]
```diff
@@ -196,9 +176,36 @@ public static ITestNGListenerFactory createListenerFactory(
   }
 
   public static class ListenerHolder {
-    private List<Class<? extends ITestNGListener>> listenerClasses;
+    private final List<Class<? extends ITestNGListener>> listenerClasses = new ArrayList<>();
     private Class<? extends ITestNGListenerFactory> listenerFactoryClass;
 
+    public void addListener(Class<? extends ITestNGListener> c) {
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/internal/TestListenerHelper.java:183]: Ok. Refactored as suggested

**Review by juherr — APPROVED** [review]
