### PR TITLE
Grouping failures in testng-failed.xml for DataProvider with Factory

### LINKED ISSUE #2521: The method has a separate string with 'invocation-number' parameters for each failure (does not group) in 'testng-failed.xml' file for DataProvider + Factory.
### TestNG Version
The latest version on 14.04.2021 at 10:06 (last commit).

### Expected behavior
If Tests with DataProvider and Factory have few failures, 'testng-failed.xml' file dose not have separate string with 'invocation-numbers' parameters for each failure, it should be grouped for each method, e.g.:
```xml
    <classes>
      <class name="test.factory.issue1041_dp_f.FactoryAnnotatedConstructorExample">
        <methods>
          <include name="testMethod1" invocation-numbers="1 3"/>
          <include name="testMethod3" invocation-numbers="0 1"/>
        </methods>
      </class> <!-- test.factory.issue1041_dp_f.FactoryAnnotatedConstructorExample -->
    </classes>
```
It is work for Tests with DataProvider without Factory.

### Actual behavior
If Tests with DataProvider and Factory have failures, 'testng-failed.xml' file has a separate string with 'invocation-numbers' parameters for each failure (does not group) in 'testng-failed.xml' file, e.g.:
```xml
    <classes>
      <class name="test.failedreporter.issue2517.DataProviderWithFactoryFailedReporterSample">
        <methods>
          <include name="f1" invocation-numbers="0"/>
          <include name="f1" invocation-numbers="2"/>
        </methods>
      </class> <!-- test.failedreporter.issue2517.DataProviderWithFactoryFailedReporterSample -->
    </classes>
```

### Test case sample
```java
package test.factory.issue1041_dp_f;

import java.util.List;
import java.util.Objects;
import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;
import org.testng.collections.Lists;

public class FactoryAnnotatedConstructorExample {
  static List<FactoryAnnotatedConstructorExample> objects = Lists.newArrayList();

  private int data;

  @Factory(dataProvider = "dp")
  public FactoryAnnotatedConstructorExample(int data) {
    this.data = data;
    addInstance(this);
  }

  private static void addInstance(FactoryAnnotatedConstructorExample instance) {
    objects.add(instance);
  }

### PR DESCRIPTION
**Pull request by PavelSakharchuk**
Look issue: https://github.com/cbeust/testng/issues/2521

### CODE REVIEW

File: core/src/main/java/org/testng/reporters/FailedReporter.java [hunk 1]
```diff
@@ -193,13 +194,27 @@ private void createXmlTest(
...
         methodName.setParameters(findMethodLocalParameters(srcXmlTest, m));
+        methodName.setConstructorOrMethod(m.getConstructorOrMethod());
         methodNames.add(methodName);
       }
-      xmlClass.setIncludedMethods(methodNames);
+
+      List<XmlInclude> groupedByMethodNames = new ArrayList<>();
+      methodNames.stream()
+              .collect(Collectors.groupingBy(XmlInclude::getConstructorOrMethod))
+              .forEach((method, methodNameList) -> {
```
Comment (juherr) [inline core/src/main/java/org/testng/reporters/FailedReporter.java:207]: Why not using a map/collect instead of the forEach with the external collection?

File: core/src/main/java/org/testng/xml/XmlInclude.java [hunk 2]
```diff
@@ -61,6 +72,12 @@ public void setName(String name) {
     return m_invocationNumbers;
   }
 
+  public void addInvocationNumbers(List<Integer> invocationNumberList) {
+    m_invocationNumbers.addAll(invocationNumberList);
+    // Deleting of duplicates numbers
+    m_invocationNumbers = m_invocationNumbers.stream().distinct().collect(Collectors.toList());
```
Comment (juherr) [inline core/src/main/java/org/testng/xml/XmlInclude.java:78]: Just move `m_invocationNumbers` from list to set and update getInvocationNumbers() for a set->list transformation.

File: core/src/main/java/org/testng/reporters/FailedReporter.java [hunk 3]
```diff
@@ -193,13 +194,27 @@ private void createXmlTest(
...
-
         XmlInclude methodName =
             new XmlInclude(m.getMethodName(), m.getFailedInvocationNumbers(), ind++);
         methodName.setParameters(findMethodLocalParameters(srcXmlTest, m));
+        methodName.setConstructorOrMethod(m.getConstructorOrMethod());
         methodNames.add(methodName);
       }
-      xmlClass.setIncludedMethods(methodNames);
+
+      List<XmlInclude> groupedByMethodNames = new ArrayList<>();
```
Comment (krmahadevan) [inline core/src/main/java/org/testng/reporters/FailedReporter.java:204]: @PavelSakharchuk - We can refactor this changeset into something like below (Which would prevent us from injecting a `ConstructorOrMethod` object into `XmlInclude`. Ideally speaking the `XmlInclude` should not be even aware of `ConstructorOrMethod` object.


Here's a refactored implementation for computing groupedByMethodNames (This would also mean that we can get rid of the earlier `for..loop` that attempts to first create the `methodNames` list.


```java
      Map<ConstructorOrMethod, List<ITestNGMethod>> group = methodList.stream()
          .collect(Collectors.groupingBy(ITestNGMethod::getConstructorOrMethod));

      List<XmlInclude> groupedByMethodNames = group.values()
          .stream()
          .map(each -> asXmlIncludes(each, srcXmlTest))
          .map(each -> {
            if (each.size() > 1) {
              XmlInclude tmpMethodName = each.get(0);
              each.stream()
                  .map(XmlInclude::getInvocationNumbers)
                  .reduce((a1, a2) -> {
                    Set<Integer> set = new HashSet<>(a1);
                    set.addAll(a2);
                    return new ArrayList<>(set);
                  }).ifPresent(tmpMethodName::addInvocationNumbers);
              return Collections.singletonList(tmpMethodName);
            }
            return each;
          })
          .flatMap(Collection::stream)
          .collect(Collectors.toList());
```

and the implementation of `asXmlIncludes()` would look like below:

```java
  private static List<XmlInclude> asXmlIncludes(List<ITestNGMethod> methods, XmlTest srcXmlTest) {
    AtomicInteger i = new AtomicInteger(0);
    return methods.stream()
        .map(m -> {
          XmlInclude methodName =
              new XmlInclude(m.getMethodName(), m.getFailedInvocationNumbers(),
                  i.getAndIncrement());
          methodName.setParameters(findMethodLocalParameters(srcXmlTest, m));
          return methodName;
        })
        .collect(Collectors.toList());
  }
```

**Review by krmahadevan — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/testng/reporters/FailedReporter.java (hunk 1 above)
Comment (PavelSakharchuk) [reply core/src/main/java/org/testng/reporters/FailedReporter.java]: Thanks for your feedback. done

File: core/src/main/java/org/testng/xml/XmlInclude.java (hunk 2 above)
Comment (PavelSakharchuk) [reply core/src/main/java/org/testng/xml/XmlInclude.java]: Thanks for your feedback. done

File: core/src/main/java/org/testng/reporters/FailedReporter.java (hunk 3 above)
Comment (PavelSakharchuk) [reply core/src/main/java/org/testng/reporters/FailedReporter.java]: Thanks for your feedback. done

File: core/src/main/java/org/testng/xml/XmlInclude.java [hunk 4]
```diff
@@ -32,10 +37,14 @@ public XmlInclude(String n, int index) {
 
   public XmlInclude(String n, List<Integer> list, int index) {
     m_name = n;
-    m_invocationNumbers = list;
+    m_invocationNumbers = new HashSet<>(list);
     m_index = index;
   }
 
+  public void setConstructorOrMethod(ConstructorOrMethod m_method) {
```
Comment (krmahadevan) [inline core/src/main/java/org/testng/xml/XmlInclude.java:44]: @PavelSakharchuk - I think we can now revert this change since its not going to be used in the `FailedReporter` right ?

File: core/src/main/java/org/testng/xml/XmlInclude.java [hunk 5]
```diff
@@ -45,6 +54,10 @@ public void setParameters(Map<String, String> parameters) {
     m_parameters.putAll(parameters);
   }
 
+  public ConstructorOrMethod getConstructorOrMethod() {
```
Comment (krmahadevan) [inline core/src/main/java/org/testng/xml/XmlInclude.java:57]: Same thing here as well.

File: core/src/main/java/org/testng/xml/XmlInclude.java (hunk 4 above)
Comment (PavelSakharchuk) [reply core/src/main/java/org/testng/xml/XmlInclude.java]: I have done :)

File: core/src/main/java/org/testng/xml/XmlInclude.java (hunk 5 above)
Comment (PavelSakharchuk) [reply core/src/main/java/org/testng/xml/XmlInclude.java]: I have done :)

File: core/src/test/java/test/failedreporter/issue2521/DataProviderWithFactoryMultiFailedReporterTest.java [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+import java.util.List;
+import org.testng.Assert;
+import org.testng.TestNG;
+import org.testng.annotations.AfterMethod;
+import org.testng.annotations.BeforeMethod;
+import org.testng.annotations.Test;
+import org.testng.collections.Lists;
+import test.SimpleBaseTest;
+
+public class DataProviderWithFactoryMultiFailedReporterTest extends SimpleBaseTest {
```
Comment (krmahadevan) [inline core/src/test/java/test/failedreporter/issue2521/DataProviderWithFactoryMultiFailedReporterTest.java:13]: Can you please add this test to `src/test/resources/testng.xml` so that it gets included for every run ?

Comment (PavelSakharchuk) [reply core/src/test/java/test/failedreporter/issue2521/DataProviderWithFactoryMultiFailedReporterTest.java:13]: oh, I'm sorry. I have done.

**Review by krmahadevan — APPROVED** [review]
LGTM (y)

**Review by juherr — APPROVED** [review]

**Comment by juherr** [comment]
Thanks for the fix! 👍
