### PR TITLE
Fix NPE in Thread affinity mode

### LINKED ISSUE #2110: NPE is thrown when running with Thread affinity
`7.0.0-beta7`

### Expected behavior
No NPE's should be thrown

### Actual behavior
NPE is thrown

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

```java
import org.testng.annotations.Test;

public class TestClass2 {
  @Test()
  public void test0() {
    System.out.println("TestClass2 - test0. Thread " + Thread.currentThread().getId());
  }

  @Test
  public void test1() {
    System.out.println("TestClass2 - test1. Thread " + Thread.currentThread().getId());
  }

  @Test(dependsOnMethods = "test1")
  public void test2() {
    System.out.println("TestClass2 - test2. Thread " + Thread.currentThread().getId());
  }

  @Test(dependsOnMethods = "test2")
  public void test3() {
    System.out.println("TestClass2 - test3. Thread " + Thread.currentThread().getId());
  }

  @Test()
  public void test4() {
    System.out.println("TestClass2 - test4. Thread " + Thread.currentThread().getId());
  }
}
```

```java
import java.io.File;
import java.util.Collections;
import org.testng.TestNG;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlSuite.ParallelMode;
import org.testng.xml.XmlTest;

public class TestRunner {

  public static void main(String[] args) {
    System.err.println("TestNG Version " + getTestNGVersion());
    System.setProperty("testng.thread.affinity", "true");
    System.err.println("Running WITH Thread Affinity");
    runTestNGTest();
  }

  private static void runTestNGTest() {
    TestNG testNG = new TestNG();
    testNG.setVerbose(2);
    testNG.setXmlSuites(Collections.singletonList(createXmlSuite()));
    testNG.run();
  }

  private static String getTestNGVersion() {
    String file = TestNG.class.getProtectionDomain().getCodeSource().getLocation().getFile();
    return new File(file).getParentFile().getName();
  }

  private static XmlSuite createXmlSuite() {
    XmlSuite xmlSuite = new XmlSuite();
    xmlSuite.setParallel(ParallelMode.CLASSES);
    xmlSuite.setThreadCount(50);
    xmlSuite.setName("1185_suite");
    XmlTest xmlTest = new XmlTest(xmlSuite);
    xmlTest.setName("1185_test");
    XmlClass xmlClass = new XmlClass(TestClass2.class);
    xmlTest.setXmlClasses(Collections.singletonList(xmlClass));
    System.err.println("Generated Xml File ");
    System.err.println(xmlSuite.toXml());
    return xmlSuite;
  }
}
```

Issue has been created from [this](https://github.com/cbeust/testng/issues/1185#issuecomment-510549002) comment

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2110

When there is just one test class and user does the
following:

1. Enables thread affinity 
2. Chooses to run with parallel=“classes”

TestNG is throwing a NPE. Fixed the problem.

Fixes #2110 

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java [hunk 1]
```diff
@@ -127,35 +127,42 @@ private void mapNodeToWorker(List<IWorker<T>> runnables, List<T> freeNodes) {
...
-  private void mapNodeToParent(List<T> freeNodes, int ix) {
+  private void mapNodeToParent(List<T> freeNodes) {
     if (!RuntimeBehavior.enforceThreadAffinity()) {
       return;
     }
-    T key = freeNodes.get(ix);
-    List<T> nodes = m_graph.getDependenciesFor(key);
-    nodes.forEach(eachNode -> upstream.put(eachNode, key));
+    for (T freeNode: freeNodes) {
+    List<T> nodes = m_graph.getDependenciesFor(freeNode);
```
Comment (juherr) [inline src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: style: indentation

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java [hunk 2]
```diff
@@ -127,35 +127,42 @@ private void mapNodeToWorker(List<IWorker<T>> runnables, List<T> freeNodes) {
...
 
-  private void mapNodeToParent(List<T> freeNodes, int ix) {
+  private void mapNodeToParent(List<T> freeNodes) {
     if (!RuntimeBehavior.enforceThreadAffinity()) {
       return;
     }
-    T key = freeNodes.get(ix);
-    List<T> nodes = m_graph.getDependenciesFor(key);
-    nodes.forEach(eachNode -> upstream.put(eachNode, key));
+    for (T freeNode: freeNodes) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: could be functionnal style with a transformation from free node to dependencie nodes

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java [hunk 3]
```diff
@@ -127,35 +127,42 @@ private void mapNodeToWorker(List<IWorker<T>> runnables, List<T> freeNodes) {
...
+    List<T> nodes = m_graph.getDependenciesFor(freeNode);
+    nodes.forEach(eachNode -> upstream.put(eachNode, freeNode));
+    }
   }
 
   private void handleThreadAffinity(List<T> freeNodes) {
     if (!RuntimeBehavior.enforceThreadAffinity()) {
       return;
     }
     for (T node : freeNodes) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: could be functional style

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java [hunk 4]
```diff
@@ -127,35 +127,42 @@ private void mapNodeToWorker(List<IWorker<T>> runnables, List<T> freeNodes) {
...
-      if (w != null) {
-        long current = w.getThreadIdToRunOn();
-        runnable.setThreadIdToRunOn(current);
+      for (T freeNode : freeNodes) {
+        IWorker<T> w = mapping.get(freeNode);
+        if (w != null) {
+          long current = w.getThreadIdToRunOn();
+          runnable.setThreadIdToRunOn(current);
+        }
+        mapping.put(freeNode, runnable);
```
Comment (juherr) [inline src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: How do you prevent that the runnable will be mapped on all free nodes?

**Review by juherr — APPROVED** [review]

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java (hunk 3 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: functional style kind of makes the readability a bit difficult I felt. Thats why I chose not to go with that in this case.

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java (hunk 4 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: I thought through this a bit more. The only time when that can happen is when there are two or more free nodes (which essentially are dependent methods) that need to use the same thread id as their upstream method. In that case, we will essentially run both the methods in the same thread.

For e.g., if user is saying `parallel=methods` and have the below setup with thread affinity enabled.

* `testa()` - independent
* `testb()` - depends on `testa()`
* `testc()` - depends on `testa()`

This will cause both `testb()` and `testc()` to run on the same thread as `testa()` [ In a way this kind of enforces sequential execution, but that is fine I guess because user wants to have thread affinity, so they already are looking for something like this ]

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: Would be difficult because the inner `forEach()` iteration needs a reference to the outer freeNode iterating variable, which I think can't be done when you use a stream coupled with a transformation.

File: src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/thread/graph/GraphThreadPoolExecutor.java]: fixed.
