### PR TITLE
Control Stacktrace verbosity in Xml Reports

### LINKED ISSUE #1228: Stacktrace is being printed for tests that passed when using expectedExceptions
### TestNG Version
6.9.10

### Expected behavior
I am using org.testng.reporters.XMLReporter as one of my listeners. All of my tests passed, so there should be no stacktraces in my testng.xml

### Actual behavior
For tests where I used expectedExceptions like the following:
```
@Test(invocationCount = kInvocationCount, threadPoolSize = kThreadPoolSize, expectedExceptions = {Exception.class}
```

The report shows the test-method status="PASS", but also prints the exception thrown, and the full stacktrace.

### Is the issue reproductible on runner?

- [x] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes # .

### Did you remember to?

- [] Add test case(s)
- [X] Update `CHANGES.txt`

Fixes #1228

Providing a new JVM argument named “stacktrace.output.level”
via which one can control the verbosity of stacktrace in 
xml reports.

### CODE REVIEW

**Comment by juherr** [comment]
I like the idea but if I understand well then the fix will impact stacktrace from failed methods too. 
The issue is about stacktrace from succeed methods only.

**Comment by krmahadevan** [comment]
@juherr - Thanks for pointing it out. I have taken care of this. Can you please help review ?

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java [hunk 1]
```diff
@@ -284,23 +284,39 @@ private void addTestResultException(XMLStringBuffer xmlBuffer, ITestResult testR
...
-      if ((config.getStackTraceOutputMethod() & XMLReporterConfig.STACKTRACE_FULL) == XMLReporterConfig
-              .STACKTRACE_FULL) {
-        xmlBuffer.push(XMLReporterConfig.TAG_FULL_STACKTRACE);
-        xmlBuffer.addCDATA(stackTraces[1]);
-        xmlBuffer.pop();
+      int level = calculateStackTraceLevels(testResult);
+      switch (level) {
+        case XMLReporterConfig.STACKTRACE_SHORT:
+          xmlBuffer.push(XMLReporterConfig.TAG_SHORT_STACKTRACE);
+          xmlBuffer.addCDATA(stackTraces[0]);
```
Comment (cbeust) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Isn't `stackTraces[0]` (and `[1]`) just one frame of the stack trace? I don't understand what makes them short or full...

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java [hunk 2]
```diff
@@ -284,23 +284,39 @@ private void addTestResultException(XMLStringBuffer xmlBuffer, ITestResult testR
...
-        xmlBuffer.addCDATA(stackTraces[0]);
-        xmlBuffer.pop();
-      }
-      if ((config.getStackTraceOutputMethod() & XMLReporterConfig.STACKTRACE_FULL) == XMLReporterConfig
-              .STACKTRACE_FULL) {
-        xmlBuffer.push(XMLReporterConfig.TAG_FULL_STACKTRACE);
-        xmlBuffer.addCDATA(stackTraces[1]);
-        xmlBuffer.pop();
+      int level = calculateStackTraceLevels(testResult);
+      switch (level) {
```
Comment (juherr) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: In the case of `STACKTRACE_BOTH`, nothing is printed?

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java [hunk 3]
```diff
@@ -284,23 +284,39 @@ private void addTestResultException(XMLStringBuffer xmlBuffer, ITestResult testR
       }
 
       String[] stackTraces = Utils.stackTrace(exception, false);
```
Comment (juherr) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Perf/improvment: if the stacktrace is not displayed, `Utils.stackTrace` should not be computed.

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java [hunk 4]
```diff
@@ -284,23 +284,39 @@ private void addTestResultException(XMLStringBuffer xmlBuffer, ITestResult testR
...
+    if (testResult.isSuccess()) {
+      stackTraceoutputMethod = config.getStackTraceOutputLevelForPassedTests();
+    }
+    if ((stackTraceoutputMethod & XMLReporterConfig.STACKTRACE_SHORT) == XMLReporterConfig.STACKTRACE_SHORT) {
+      return XMLReporterConfig.STACKTRACE_SHORT;
+    }
+    if ((stackTraceoutputMethod & XMLReporterConfig.STACKTRACE_FULL) == XMLReporterConfig.STACKTRACE_FULL) {
+      return XMLReporterConfig.STACKTRACE_FULL;
+    }
+    return XMLReporterConfig.STACKTRACE_BOTH;
```
Comment (juherr) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Should be `STACKTRACE_NONE` instead because if `stackTraceoutputMethod = STACKTRACE_BOTH` the method will return `STACKTRACE_SHORT`

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java [hunk 5]
```diff
@@ -284,23 +284,39 @@ private void addTestResultException(XMLStringBuffer xmlBuffer, ITestResult testR
...
       xmlBuffer.pop();
     }
   }
 
+  private int calculateStackTraceLevels(ITestResult testResult) {
+    int stackTraceoutputMethod = config.getStackTraceOutputMethod();
+    if (testResult.isSuccess()) {
+      stackTraceoutputMethod = config.getStackTraceOutputLevelForPassedTests();
+    }
+    if ((stackTraceoutputMethod & XMLReporterConfig.STACKTRACE_SHORT) == XMLReporterConfig.STACKTRACE_SHORT) {
```
Comment (juherr) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: In fact, I don't catch the need if the bit mask: `stackTraceoutputMethod` should already be the good value (check should be done in the setter) and all possible values are already known: `STACKTRACE_NONE`, `STACKTRACE_SHORT`, `STACKTRACE_FULL` and `STACKTRACE_BOTH`.

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java [hunk 6]
```diff
@@ -284,23 +284,39 @@ private void addTestResultException(XMLStringBuffer xmlBuffer, ITestResult testR
...
-        xmlBuffer.pop();
-      }
-      if ((config.getStackTraceOutputMethod() & XMLReporterConfig.STACKTRACE_FULL) == XMLReporterConfig
-              .STACKTRACE_FULL) {
-        xmlBuffer.push(XMLReporterConfig.TAG_FULL_STACKTRACE);
-        xmlBuffer.addCDATA(stackTraces[1]);
-        xmlBuffer.pop();
+      int level = calculateStackTraceLevels(testResult);
+      switch (level) {
+        case XMLReporterConfig.STACKTRACE_SHORT:
```
Comment (juherr) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: I think it is the perfect time to replace `XMLReporterConfig.STACKTRACE_*` by an enum.

**Review by juherr — CHANGES_REQUESTED** [review]
Some esthetic changes and a bit of refactoring of the legacy code, and it will be perfect :)

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java (hunk 3 above)
Comment (krmahadevan) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Fixed this.

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java (hunk 2 above)
Comment (krmahadevan) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Fixed this.

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java (hunk 6 above)
Comment (krmahadevan) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Took care of this.

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java (hunk 4 above)
Comment (krmahadevan) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Fixed this.

**Comment by krmahadevan** [comment]
@juherr - I have fixed all your review comments. Please let me know if there is anything that is missing from my side.

File: src/main/java/org/testng/reporters/XMLReporterConfig.java [hunk 7]
```diff
@@ -239,4 +239,49 @@ public void setGenerateTestResultAttributes(boolean generateTestResultAttributes
...
+      return Integer.toString(level);
+    }
+
+    public static StackTraceLevels parse(int level) {
+      for (StackTraceLevels value : values()) {
+        if (value.getLevel() == level) {
+          return value;
+        }
+      }
+      throw new IllegalArgumentException(level + " is not a valid StackTrace level");
```
Comment (juherr) [inline src/main/java/org/testng/reporters/XMLReporterConfig.java]: Proposition: warn + using NONE if level < NONE and BOTH if level > BOTH

**Review by juherr — APPROVED** [review]
Awesome job, thanks! 👍

File: src/main/java/org/testng/reporters/XMLSuiteResultWriter.java (hunk 1 above)
Comment (cbeust) [inline src/main/java/org/testng/reporters/XMLSuiteResultWriter.java]: Ok got it, thanks for the clarification.

**Comment by juherr** [comment]
LGTM :+1: Ping @cbeust
