### PR TITLE
Restore DependsOnGroups functionality

### LINKED ISSUE #2664: Order for DependsOnGroups  has changed after TestNg 7.4.0
### TestNG Version
7.5 not working
7.4 works

### Expected behavior
s3
s1
s2

### Actual behavior

s1
s2
s3

### Is the issue reproducible on runner?

- [ ] Maven
- [ ] Eclipse
- [ ] IntelliJ

### Test case sample

Here is an example for BeforeSuite, but the same problem exists for all configuration methods. The same issue also for dependsOnMethod

```
    @BeforeSuite(groups = { "g1" })
    public void s3() {
        System.out.println("s3");
    }

    @BeforeSuite(groups = { "g2" }, dependsOnGroups = "g1")
    public void s2() {
        System.out.println("s2");
    }

    @BeforeSuite(groups = { "g2" }, dependsOnGroups = "g1")
    public void s1() {
        System.out.println("s1");
    }

    @Test()
    public void test3() {
        System.out.println("test3");
    }
```

I have tried to find the commit where the fault was introduced, but my IDE did not like to switch gradle version and I'm new at gradle.

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2664

Fixes #2664  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: testng-core-api/src/main/java/org/testng/xml/XmlTest.java [hunk 1]
```diff
@@ -663,23 +663,4 @@ public XmlGroups getXmlGroups() {
   public boolean nameMatchesAny(List<String> names) {
     return names.contains(getName());
   }
-
-  /**
-   * @param xmlTest - The {@link XmlTest} that represents the current <code>test</code>
-   * @return - <code>true</code> if group based selection was employed and false otherwise.
-   */
-  public static boolean isGroupBasedExecution(XmlTest xmlTest) {
```
Comment (juherr) [inline testng-core-api/src/main/java/org/testng/xml/XmlTest.java:671]: It's a public api. Maybe deprecated it instead of remove it if it was already released once.

File: testng-core/src/test/java/test/configuration/ConfigurationGroupsTest.java [hunk 2]
```diff
@@ -37,4 +39,26 @@ public void runTest(Class<?> testClass, String groupName) {
       {ConfigurationGroups7SampleTest.class, "A"}
     };
   }
+
+  @Test(description = "GITHUB-2664", dataProvider = "getTestClasses")
+  public void ensureDependsOnGroupsHonouredForConfigs(Class<?> clazz) {
+    MethodInvocationListener.logs.clear();
+    TestNG testng = create(clazz);
+    testng.setVerbose(2);
+    testng.setListenerClasses(Collections.singletonList(MethodInvocationListener.class));
```
Comment (juherr) [inline testng-core/src/test/java/test/configuration/ConfigurationGroupsTest.java:48]: If you addListener instance instead of the listener class, you'll be able to get log from instance instead of dealing with static.

**Review by juherr — COMMENTED** [review]
LGTM

File: testng-core-api/src/main/java/org/testng/xml/XmlTest.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core-api/src/main/java/org/testng/xml/XmlTest.java:671]: This was introduced by me in `7.5-SNAPSHOT` and its not public yet. That's why I directly went ahead and deleted it.

File: testng-core/src/test/java/test/configuration/ConfigurationGroupsTest.java (hunk 2 above)
Comment (krmahadevan) [reply testng-core/src/test/java/test/configuration/ConfigurationGroupsTest.java]: Fixed.

**Comment by krmahadevan** [comment]
@juherr - If you are fine with the changes, please approve this PR so that we can get it merged.

**Review by juherr — APPROVED** [review]

**Comment by martinaldrin** [comment]
Many thanks for fixing this issue.  Will all my unit test pass with this fix?

**Comment by martinaldrin** [comment]
I tested Issue2664Test from my PR  #2666, Tests are not running in correct order.

> [RemoteTestNG] detected TestNG version 7.5.0
> 
> ===============================================
> Command line suite
> Total tests run: 3, Passes: 3, Failures: 0, Skips: 0
> ===============================================
> 
> 
> ===============================================
> Command line suite
> Total tests run: 4, Passes: 4, Failures: 0, Skips: 0
> ===============================================
> 
> FAILED: ensureThatConfigurationMethodsWithGroupDependencyWorksWithBaseClass
>         GITHUB-2663
> org.junit.ComparisonFailure: expected:<...e",
>     "beforeSuite[3",
>     "beforeSuite1",
>     "beforeSuite2",
>     "beforeSuiteBase2",
>     "beforeTestBase",
>     "beforeTest3",
>     "beforeTest1",
>     "beforeTest2",
>     "beforeTestBase2",
>     "beforeClassBase",
>     "beforeClass3",
>     "beforeClass1",
>     "beforeClass2",
>     "beforeClassBase2",
>     "beforeMethodBase",
>     "beforeMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethodBase2",
>     "test3",
>     "afterMethod3",
>     "afterMethod1",
>     "afterMethod2",
>     "beforeMethodBase",
>     "beforeMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethodBase2",
>     "test2",
>     "afterMethod3",
>     "afterMethod1",
>     "afterMethod2",
>     "beforeMethodBase",
>     "beforeMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethodBase2",
>     "testBase",
>     "afterMethod3",
>     "afterMethod1",
>     "afterMethod2",
>     "beforeMethodBase",
>     "beforeMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethodBase2",
>     "test1",
>     "afterMethod3",
>     "afterMethod1",
>     "afterMethod2",
>     "afterClass3",
>     "afterClass1",
>     "afterClass2",
>     "afterTest3",
>     "afterTest1",
>     "afterTest2",
>     "afterSuite3",
>     "afterSuite1",
>     "afterSuite2]"]> but was:<...e",
>     "beforeSuite[Base2",
>     "beforeSuite1",
>     "beforeSuite2",
>     "beforeSuite3",
>     "beforeTestBase",
>     "beforeTestBase2",
>     "beforeTest1",
>     "beforeTest2",
>     "beforeTest3",
>     "beforeClassBase",
>     "beforeClassBase2",
>     "beforeClass1",
>     "beforeClass2",
>     "beforeClass3",
>     "beforeMethodBase",
>     "beforeMethodBase2",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethod3",
>     "test3",
>     "afterMethod1",
>     "afterMethod2",
>     "afterMethod3",
>     "beforeMethodBase",
>     "beforeMethodBase2",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethod3",
>     "test2",
>     "afterMethod1",
>     "afterMethod2",
>     "afterMethod3",
>     "beforeMethodBase",
>     "beforeMethodBase2",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethod3",
>     "testBase",
>     "afterMethod1",
>     "afterMethod2",
>     "afterMethod3",
>     "beforeMethodBase",
>     "beforeMethodBase2",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethod3",
>     "test1",
>     "afterMethod1",
>     "afterMethod2",
>     "afterMethod3",
>     "afterClass1",
>     "afterClass2",
>     "afterClass3",
>     "afterTest1",
>     "afterTest2",
>     "afterTest3",
>     "afterSuite1",
>     "afterSuite2",
>     "afterSuite3]"]>
> 	at test.configuration.issue2664.Issue2664Test.ensureThatConfigurationMethodsWithGroupDependencyWorksWithBaseClass(Issue2664Test.java:134)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> ... Removed 30 stack frames
> FAILED: ensureThatConfigurationMethodsWithGroupDependencyWorks
>         GITHUB-2663
> org.junit.ComparisonFailure: expected:<["beforeSuite[3",
>     "beforeSuite1",
>     "beforeSuite2",
>     "beforeTest3",
>     "beforeTest1",
>     "beforeTest2",
>     "beforeClass3",
>     "beforeClass1",
>     "beforeClass2",
>     "beforeMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "test3",
>     "afterMethod3",
>     "afterMethod1",
>     "afterMethod2",
>     "beforeMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "test2",
>     "afterMethod3",
>     "afterMethod1",
>     "afterMethod2",
>     "beforeMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "test1",
>     "afterMethod3",
>     "afterMethod1",
>     "afterMethod2",
>     "afterClass3",
>     "afterClass1",
>     "afterClass2",
>     "afterTest3",
>     "afterTest1",
>     "afterTest2",
>     "afterSuite3",
>     "afterSuite1",
>     "afterSuite2]"]> but was:<["beforeSuite[1",
>     "beforeSuite2",
>     "beforeSuite3",
>     "beforeTest1",
>     "beforeTest2",
>     "beforeTest3",
>     "beforeClass1",
>     "beforeClass2",
>     "beforeClass3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethod3",
>     "test3",
>     "afterMethod1",
>     "afterMethod2",
>     "afterMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethod3",
>     "test2",
>     "afterMethod1",
>     "afterMethod2",
>     "afterMethod3",
>     "beforeMethod1",
>     "beforeMethod2",
>     "beforeMethod3",
>     "test1",
>     "afterMethod1",
>     "afterMethod2",
>     "afterMethod3",
>     "afterClass1",
>     "afterClass2",
>     "afterClass3",
>     "afterTest1",
>     "afterTest2",
>     "afterTest3",
>     "afterSuite1",
>     "afterSuite2",
>     "afterSuite3]"]>
> 	at test.configuration.issue2664.Issue2664Test.ensureThatConfigurationMethodsWithGroupDependencyWorks(Issue2664Test.java:62)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> ... Removed 30 stack frames
> 
> ===============================================
>     Default test
>     Tests run: 2, Failures: 2, Skips: 0
> ===============================================
> 
> 
> ===============================================
> Default suite
> Total tests run: 2, Passes: 0, Failures: 2, Skips: 0
> ===============================================
> 
>

**Comment by krmahadevan** [comment]
@martinaldrin - I created a sample project which uses that test class and tried running it against `6.14.3`, `7.4.0` and `7.5-SNAPSHOT`

With `6.14.3` and `7.4.0` the test `Issue2664Test.ensureThatConfigurationMethodsWithGroupDependencyWorksWithBaseClass()` fails. 

So this is not a regression but a new issue that we need to fix.

Also note that when I use `mvn clean test -Dtestng.version=7.5-SNAPSHOT` the tests run fine. So I am guessing that my changes have actually fixed all the issues atleast with this scenario.

Output from different version execution is attached in the log file.

Both the tests pass when executed against TestNG `7.5-SNAPSHOT` using the command `mvn clean test -Dtestng.version=7.5-SNAPSHOT`

Complete execution logs across all 3 versions are available in [run.log](https://github.com/cbeust/testng/files/7782676/run.log)

Here's the sample project.


[issue_2664.zip](https://github.com/cbeust/testng/files/7782680/issue_2664.zip)

If there is anything additional that is failing, please create a new issue and include a sample that can be executed to reproduce the problem.

**Comment by martinaldrin** [comment]
It seems that my test actually works, my mistake. 

When do you think we can expect a release of TestNg 7.5?

**Comment by krmahadevan** [comment]
@martinaldrin - It should be pretty soon. Just waiting on some access related clarifications from @cbeust
