### PR TITLE
Restore testnames when using suites in suite.

### LINKED ISSUE #2709: Testnames not working together with suites in suite
Hi,

I did a uplift yesterday and today many loops started to fail due missing functionality from our own fork. 
Feature was supposed to be included in TestNg in this commit, but something has changed since this commit was merged.
https://github.com/cbeust/testng/commit/3e14c7db6be71f76d4d630fcd162a8b3c8e566c6

07:12:50.792 [main] ERROR org.testng.TestNG - 
The test(s) <[test1,test2,test3]> cannot be found.

### TestNG Version
broken in  TestNg 7.5 works in 7.4
#2532 breaks the testname support for suites in suite

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I will try to reproduce the fault in a small test, updates are coming.

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### PR DESCRIPTION
**Pull request by martinaldrin**
Fixes #2709.

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`
- [ ] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 1]
```diff
@@ -420,7 +421,8 @@ public void initializeSuitesAndJarFile() {
         new JarFileUtils(getProcessor(), m_xmlPathInJar, m_testNames, m_parallelMode);
 
     Collection<XmlSuite> allSuites = utils.extractSuitesFrom(jarFile);
-    m_suites.addAll(processCommandLineArgs(allSuites));
+    allSuites.stream().forEach(s -> processParallelModeCommandLineArgs(s));
```
Comment (Elisedlund-ericsson) [inline testng-core/src/main/java/org/testng/TestNG.java:424]: it made no sense to check that all testnames exist in alla suite files in the jar. 
and it also made no sense to check processCommandLineArgs a second time to get its side effect. (with suites that was not on the command line even)  

just enabling the parallel+ threadcount if command line argument was given seems like the intended bugfix in:
https://github.com/cbeust/testng/issues/2532

**Review by Elisedlund-ericsson — APPROVED** [review]

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (martinaldrin) [reply testng-core/src/main/java/org/testng/TestNG.java:424]: @dsankouski  can you have a look at my correction to ensure that we don't break anything for your fix.

**Comment by bj-9527** [comment]
Hi Martin,

I think you also need to add some info in `changes.txt`.

**Comment by martinaldrin** [comment]
> Hi Martin,
> 
> I think you also need to add some info in `changes.txt`.

thanks, done

**Comment by martinaldrin** [comment]
@krmahadevan please review when you have time.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (dsankouski) [reply testng-core/src/main/java/org/testng/TestNG.java:424]: Seems fine.

Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java:424]: We don't need to be streaming, if we are going to be using `for..Each`. We can simplify this to `allSuites.forEach(this::processParallelModeCommandLineArgs);`

**Review by krmahadevan — CHANGES_REQUESTED** [review]
I haven't quite understood the scenario wherein this doesn't work. Can we please help add a unit test for this which explicitly tests out the fix (am guessing that there's no test right now for this which is why the build was passing even though this functionality was broken)

**Comment by martinaldrin** [comment]
> I haven't quite understood the scenario wherein this doesn't work. Can we please help add a unit test for this which explicitly tests out the fix (am guessing that there's no test right now for this which is why the build was passing even though this functionality was broken)

The problem occurs when we defined suites in suites as below, then it requires the test names to exist in all subsuites, after the bug that was introduced in TestNg 7.5.  but we define several testnames that can exist in any of the subsuites and only the matching tests should be exuecuted.

DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="testsuite">
    <suite-files>
        <suite-file path="./subsuite1.xml" />
        <suite-file path="./subsuite2.xml" />
        <suite-file path="./../startrestart/subsuite3.xml" />
    </suite-files>
</suite>

**Comment by martinaldrin** [comment]
> I haven't quite understood the scenario wherein this doesn't work. Can we please help add a unit test for this which explicitly tests out the fix (am guessing that there's no test right now for this which is why the build was passing even though this functionality was broken)

I added a unit test in JarFileUtilsTest.java, since I was able to reuse allot of code for a similar test.
I managed to reproduce the fault by adding back the old method.

File: testng-core/src/test/java/org/testng/JarFileUtilsTest.java [hunk 2]
```diff
@@ -82,6 +82,27 @@ public void testWithInvalidXmlFile() throws MalformedURLException {
...
+        new String[] {
+          "org.testng.jarfileutils.org.testng.SampleTest2",
+          "org.testng.jarfileutils.org.testng.SampleTest4",
+          "org.testng.jarfileutils.org.testng.SampleTest5"
+        };
+
+    testNg.setTestNames(Arrays.asList(expectedTestNames));
+    testNg.setXmlPathInJar(jar.getAbsolutePath());
+    testNg.setTestJar(jar.getAbsolutePath());
+    testNg.initializeSuitesAndJarFile();
```
Comment (krmahadevan) [inline testng-core/src/test/java/org/testng/JarFileUtilsTest.java:103]: @martinaldrin - I dont see any assertions. Was that intentional ?

Comment (martinaldrin) [reply testng-core/src/test/java/org/testng/JarFileUtilsTest.java:93]: > 

Yes, The purpose of the test is to ensure that a exception is not thrown. I can not add any assert methods.
We just ensure that the method do not check suites in jarfiles here, because that is handled later in JarFileUtiles.
And JarFileUtiles already have unit tests to ensure that this is working as expected, the problem started to aggregate suites in the jarfile here without consider sub suites.

A very similar method exist in class: JarFileUtil method: testngXmlExistsInJar that take care of that part.

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 3]
```diff
@@ -353,7 +353,8 @@ private OverrideProcessor getProcessor() {
       TestNamesMatcher testNamesMatcher = new TestNamesMatcher(s, m_testNames);
       List<String> missMatchedTestname = testNamesMatcher.getMissMatchedTestNames();
       if (!missMatchedTestname.isEmpty()) {
-        throw new TestNGException("The test(s) <" + missMatchedTestname + "> cannot be found.");
+        throw new TestNGException(
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:356]: It could be nice to integrate the check directly into `getSuitesMatchingTestNames`.

File: testng-core/src/test/java/org/testng/JarFileUtilsTest.java [hunk 4]
```diff
@@ -12,6 +12,7 @@
 import java.util.Collections;
 import java.util.LinkedList;
 import java.util.List;
+import com.google.common.collect.Lists;
```
Comment (juherr) [inline testng-core/src/test/java/org/testng/JarFileUtilsTest.java:15]: Wrong import

Comment (juherr) [reply testng-core/src/test/java/org/testng/JarFileUtilsTest.java:15]: You can use `Arrays.asList` instead

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 3 above)
Comment (martinaldrin) [reply testng-core/src/main/java/org/testng/TestNG.java]: done

File: testng-core/src/test/java/org/testng/JarFileUtilsTest.java (hunk 4 above)
Comment (martinaldrin) [reply testng-core/src/test/java/org/testng/JarFileUtilsTest.java]: done

**Review by krmahadevan — APPROVED** [review]

**Review by juherr — APPROVED** [review]

**Comment by juherr** [comment]
Thank for the change! 👍
