### PR TITLE
TestNG runs all methods when filtering via <include> fails

### LINKED ISSUE #1507: TestNG runs all methods when filtering via <include> fails
### Expected behavior
Only those methods that are listed as part of the `<include>` tag should be executed. If the actual class does not have any methods that match the contents of `<include>` tag, then nothing should get executed.

### Actual behavior
TestNG ends up running all methods.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

Here's a test class

```java
package com.rationaleemotions.googleforums;

import org.testng.annotations.Test;

public class ClassWithManyMethods {
    @Test
    public void testa() {
        System.err.println("testa()");
    }
    @Test
    public void testb() {
        System.err.println("testb()");
    }
    @Test
    public void testc() {
        System.err.println("testc()");
    }
    @Test
    public void testd() {
        System.err.println("testd()");
    }

}
```

Here's the xml suite file

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="many_methods_suite" parallel="false" verbose="2">
    <test name="many_methods_test" parallel="false">
        <classes>
            <class name="com.rationaleemotions.googleforums.ClassWithManyMethods">
                <methods>
                    <include name="cars_sedan"/>
                    <include name="train_Local"/>
                    <include name="flight_Domestic"/>
                </methods>
            </class>
        </classes>
    </test>
</suite>
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1507

Fixes #1507 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr / @cbeust - Can you please help take a look at this?

File: src/main/java/org/testng/internal/XmlMethodSelector.java [hunk 1]
```diff
@@ -283,6 +290,13 @@ public void setIncludedGroups(Map<String, String> includedGroups) {
   }
 
   private static boolean isIncluded(String[] groups, Collection<String> includedGroups) {
+    return isIncluded(groups, includedGroups, false);
+  }
+
+  private static boolean isIncluded(String[] groups, Collection<String> includedGroups, boolean noGroupsSpecified) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/XmlMethodSelector.java]: What if we have only `private static boolean isIncluded(String[] groups, Collection<String> includedGroups, Collection<String> excludedGroups)` instead of 2 methods?

File: src/test/java/test/methodselectors/MethodSelectorTest.java [hunk 2]
```diff
@@ -82,4 +83,17 @@ public void lessThanPriorityAllTests() {
   public static void ppp(String s) {
```
Comment (juherr) [inline src/test/java/test/methodselectors/MethodSelectorTest.java]: CleanCode: Could be removed

File: src/main/java/org/testng/internal/XmlMethodSelector.java [hunk 3]
```diff
@@ -283,6 +290,13 @@ public void setIncludedGroups(Map<String, String> includedGroups) {
...
+    if (noGroupsSpecified) {
+      return isMemberOf(groups, includedGroups);
+    }
     if (includedGroups.size() == 0) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/XmlMethodSelector.java]: CleanCode: `isEmpty()`

File: src/main/java/org/testng/internal/XmlMethodSelector.java [hunk 4]
```diff
@@ -142,14 +144,19 @@ else if (isExcludedInGroups) {
...
-          boolean isIncludedInMethods = isIncluded(fullyQualifiedMethodName, includedMethods);
+          boolean isIncludedInMethods = isIncluded(fullyQualifiedMethodName, includedMethods, noGroupsSpecified);
           List<String> excludedMethods = createQualifiedMethodNames(xmlClass,
               xmlClass.getExcludedMethods());
           boolean isExcludedInMethods = isExcluded(fullyQualifiedMethodName, excludedMethods);
           if (result) {
             // If we're about to include this method by group, make sure
             // it's included by method and not excluded by method
-            result = isIncludedInMethods && ! isExcludedInMethods;
+            if (!xmlClass.getIncludedMethods().isEmpty()) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/XmlMethodSelector.java]: The new `isIncluded` looks enough, do we really need this change?

**Review by juherr — COMMENTED** [review]
Looks good but some questions.

File: src/main/java/org/testng/internal/XmlMethodSelector.java (hunk 4 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/XmlMethodSelector.java]: The new `isIncluded()` works on methods that were filtered via `createQualifiedMethodNames(xmlClass, toStringList(xmlClass.getIncludedMethods()));`. But we need to involve the `isIncludedInMethods` and `isIncludedInMethods` if and only if there were some `<include>` or `<exclude>` methods specified by the users. That is why this check is required.

File: src/main/java/org/testng/internal/XmlMethodSelector.java (hunk 1 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/XmlMethodSelector.java]: Fixed.

File: src/main/java/org/testng/internal/XmlMethodSelector.java (hunk 3 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/XmlMethodSelector.java]: Fixed

File: src/test/java/test/methodselectors/MethodSelectorTest.java (hunk 2 above)
Comment (krmahadevan) [inline src/test/java/test/methodselectors/MethodSelectorTest.java]: Fixed

**Comment by krmahadevan** [comment]
ping @juherr - I have fixed all the review comments.

**Review by juherr — APPROVED** [review]
LGTM :+1: 
Ping @cbeust
