### PR TITLE
Ensure ITestResult injected to @AfterMethod is apt

### LINKED ISSUE #3006: ITestResult injected at @AfterMethod incorrect when a configuration method failed
### TestNG Version
v7.8.0

### Expected behavior
When a configuration method (method decorated with  `@BeforeMethod`) fails. The method decorated with `@AfterMehtod(alwayRun=true)` recives an ITestResult object with status `SKIPPED` (3) and the information about the configuration methods that failed.

### Actual behavior
When a configuration method (method decorated with  `@BeforeMethod`) fails. The method decorated with `@AfterMehtod(alwayRun=true)` recives an ITestResult object with status `CREATED` (-1) and no information about the skip reason.

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

```java
package playground;

import static org.testng.Assert.assertTrue;

import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class BugTest {
	
	@BeforeMethod
	public void beforeMethod() {
		throw new RuntimeException("Exception to simulate configuration error");
	}
	
	@Test
	public void test() {
		assertTrue(true);
	}
	
	@AfterMethod(alwaysRun = true)
	public void afterMethod(ITestResult testResult) {
		System.out.println(testResult.getStatus()); // -1
	}

}
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #3006

Fixes #3006  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: testng-core/src/main/java/org/testng/internal/invokers/TestInvoker.java [hunk 1]
```diff
@@ -598,7 +598,7 @@ private ITestResult invokeMethod(
       testResult.setMethod(arguments.getTestMethod());
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/internal/invokers/TestInvoker.java:598]: This line looks useless now.

**Review by juherr — APPROVED** [review]

File: testng-core/src/main/java/org/testng/internal/invokers/TestInvoker.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/internal/invokers/TestInvoker.java]: Thanks for catching that. Fixed it
