### PR TITLE
SuiteRunner could not be initial by default Configuration

### LINKED ISSUE #2743: SuiteRunner could not be initial by default Configuration
### Expected behavior
SuiteRunner could init by default Configuration

### Actual behavior
```
Caused by: java.lang.NullPointerException
	at org.testng.internal.objects.SimpleObjectDispenser.instantiateUsingDefaultConstructor(SimpleObjectDispenser.java:178)
	at org.testng.internal.objects.SimpleObjectDispenser.createInstance(SimpleObjectDispenser.java:87)
	... 46 more
```

### Is the issue reproducible on runner?
yes, here is a sample code
```
public class IssueTest {
  @Test
  public void issueTest() {
    XmlSuite suite = new XmlSuite();
    suite.setName("TestSuite");
    XmlTest test = new XmlTest(suite);
    test.setName("ChildTests");
    List<XmlClass> classes = new ArrayList<>();
    classes.add(new XmlClass("test.configuration.suites.IssueTest"));
    test.setXmlClasses(classes);

    final IConfiguration configuration = new Configuration();
    final boolean useDefaultListeners = true;

    SuiteRunner baseSuiteRunner = new SuiteRunner(configuration, suite,
        "outputDir",
        new ITestRunnerFactory() {

          @Override
          public TestRunner newTestRunner(ISuite suite, XmlTest xmlTest,
                                          Collection<IInvokedMethodListener> listeners, List<IClassListener> classListeners) {
            TestRunner runner =
                new TestRunner(configuration, suite, xmlTest,
                    false /* skipFailedInvocationCounts */,
                    listeners, classListeners);
            if (useDefaultListeners) {
              runner.addListener(new TestHTMLReporter());
              runner.addListener(new JUnitXMLReporter());
            }

            return runner;
          }

        },
        useDefaultListeners,
        Comparator.comparingInt(ITestNGMethod::getPriority));
    baseSuiteRunner.run();
  }
}
```

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### PR DESCRIPTION
**Pull request by bj-9527**
Fixes #2743.

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`
- [x] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: testng-core/src/test/java/test/configuration/ConfigurationTest.java [hunk 1]
```diff
@@ -29,4 +31,11 @@ public void testSuite() {
     testConfiguration(SuiteTestSample.class);
     Assert.assertEquals(Arrays.asList(1, 2, 3, 4, 5), SuiteTestSample.m_order);
   }
+
+  @Test
+  public void testSuiteRunnerWithDefaultConfiguration() {
+    TestNG testNG = create(SuiteRunnerIssueTestSample.class);
+    testNG.run();
+    Assert.assertNotNull(SuiteRunnerIssueTestSample.suiteRunner);
```
Comment (krmahadevan) [inline testng-core/src/test/java/test/configuration/ConfigurationTest.java:39]: @bj-9527 - This assertion looks suspicious. Can we change this assertion such that it checks if the `run()` was successful by checking the exit code instead ?

Comment (bj-9527) [reply testng-core/src/test/java/test/configuration/ConfigurationTest.java]: OK, I have change Assert to check status

**Review by krmahadevan — APPROVED** [review]

**Review by juherr — APPROVED** [review]
