### PR TITLE
TestNG exits with a zero when there are configuration failures

### LINKED ISSUE #1517: TestNG exits with a zero when there are configuration failures
### Expected behavior
When there's a configuration failure in a TestNG execution via its api, TestNG should be exiting with a non-zero status.

### Actual behavior
TestNG exits with a zero status.

### Is the issue reproductible on runner?

- [X] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

Here's a simple test class
```java
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class AppTest {

    @BeforeClass
    public void beforeClass() {
        throw new RuntimeException("Simulating a configuration failure");
    }
    @Test
    public void testMethod() {
        System.err.println("Hello world");
    }
}
```

Here's a runner class that runs the above mentioned test class
```java
import org.testng.TestNG;

public class TestRunner {
    public static void main(String[] args) {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{AppTest.class});
        testNG.setVerbose(3);
        testNG.run();
        System.err.println("Return code : " + testNG.getStatus());
    }
}
```

Actual output:

```shell
===== Invoked methods
  AppTest.beforeClass()[pri:0, instance:com.rationaleemotions.AppTest@6a38e57f] 1782113663
=====
FAILED CONFIGURATION: @BeforeClass beforeClass
java.lang.RuntimeException: Simulating a configuration failure
	at com.rationaleemotions.AppTest.beforeClass(AppTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:165)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at com.rationaleemotions.TestRunner.main(TestRunner.java:12)

SKIPPED: testMethod
java.lang.RuntimeException: Simulating a configuration failure
	at com.rationaleemotions.AppTest.beforeClass(AppTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:165)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at com.rationaleemotions.TestRunner.main(TestRunner.java:12)


===============================================
    Command line test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 0
===============================================


===============================================
Command line suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================

Return code : 0

Process finished with exit code 0
```

More Details available in this thread : https://groups.google.com/d/msg/testng-users/WlX5H5B8fwo/m_GR0svPAQAJ

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1517

Fixes #1517 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/TestNG.java [hunk 1]
```diff
@@ -947,9 +947,11 @@ private void addReporter(Class<? extends IReporter> r) {
   }
 
   private void initializeDefaultListeners() {
-    m_testListeners.put(ExitCodeListener.class, new ExitCodeListener(this));
+    ExitCodeListener exitCodeListener = new ExitCodeListener(this);
+    m_testListeners.put(ExitCodeListener.class, exitCodeListener);
 
     if (m_useDefaultListeners) {
+      addListener((ITestNGListener) exitCodeListener);
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Why do you add it only here?

File: src/main/java/org/testng/TestNG.java [hunk 2]
```diff
@@ -947,9 +947,11 @@ private void addReporter(Class<? extends IReporter> r) {
   }
 
   private void initializeDefaultListeners() {
-    m_testListeners.put(ExitCodeListener.class, new ExitCodeListener(this));
+    ExitCodeListener exitCodeListener = new ExitCodeListener(this);
+    m_testListeners.put(ExitCodeListener.class, exitCodeListener);
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Why do you put it directly in the map instead of `addListener`?

File: src/test/java/test/github1517/TestClassWithConfigFailureSample.java [hunk 3]
```diff
@@ -0,0 +1,16 @@
+package test.github1517;
```
Comment (juherr) [inline src/test/java/test/github1517/TestClassWithConfigFailureSample.java]: package `test.cli.github1517` or `test.listener.github1517` or something more precise?

File: src/main/java/org/testng/TestNG.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: I think that's existing code. Not part of my changes.

File: src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: I didn't quite get you there. Can you please clarify ?

File: src/test/java/test/github1517/TestClassWithConfigFailureSample.java (hunk 3 above)
Comment (krmahadevan) [reply src/test/java/test/github1517/TestClassWithConfigFailureSample.java]: Sure will change.

**Comment by krmahadevan** [comment]
@juherr - Can you please check now ?

**Review by juherr — APPROVED** [review]
LGTM :+1: 
Ping @cbeust

**Comment by cannino** [comment]
Do you perform any type of back porting? My organization is affected by this issue and is currently using version 6.9.12. Any chance we would see this fix in version 6.9.14?

**Comment by juherr** [comment]
> Do you perform any type of back porting?

We have only one release branch. Why not upgrading?

**Comment by cannino** [comment]
Our tests are poorly written and I work in an enterprise environment where upgrading can be painful. I upgraded from version 5.x to 6.9.12 last year. The test execution order changed so much between releases I had a heck of a time making some of the tests idempotent so they would not affect downstream tests. I have low confidence at this point something else wouldn't go wrong if we upgraded again, though LOTS of internals change between a major release...

**Comment by juherr** [comment]
I understand but maybe you won't have a regression with more recent versions. I suppose it should not be a big effort to try a run with the latest release.
Don't hesitate to report issues and postpone the upgrade if needed.

About the test execution order, it is not specified and may change, but you have many features which allow enforcing the order. If you use them and see some varations, it could be considered as an issue and a fix could be provided in a later release.
