### PR TITLE
SoftAssert: allow custom general message

### LINKED ISSUE #2121: SoftAssert: allow custom message.
### TestNG Version
6.13.4

### Expected behavior
Improve #504
 final SoftAssert sa = new SoftAssert();
      sa.assertTrue(false);
      sa.assertAll("Test abc fails:");

### Actual behavior
Cannot change default message in SoftAssert

### PR DESCRIPTION
**Pull request by dr29bart**
Closes #2121

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

### CODE REVIEW

File: src/test/java/test/assertion/SoftAssertTest.java [hunk 1]
```diff
@@ -35,6 +35,34 @@ public void onAssertFailure(IAssert assertCommand, AssertionError ex) {
...
+      final SoftAssert sa = new SoftAssert();
+      sa.assertTrue(false);
+      sa.assertAll(msg);
+      Assert.fail();
+    } catch (AssertionError exc) {
+      Assert.assertNotNull(exc.getMessage());
+      Assert.assertTrue(exc.getMessage().startsWith(msg));
+    }
+  }
+
```
Comment (cbeust) [inline src/test/java/test/assertion/SoftAssertTest.java]: You could avoid the duplication with one test and one data provider providing two messages, one null and one non null.
