### PR TITLE
Streamline working of shared thread pools

### LINKED ISSUE #3179: ClassCastException when use shouldUseGlobalThreadPool(true) property
### Expected behavior
no exceptions

### Actual behavior
there is exception:
```java
java.lang.ClassCastException: class org.testng.internal.thread.graph.TestNGFutureTask cannot be cast to class org.testng.internal.thread.Async$AsyncTask (org.testng.internal.thread.graph.TestNGFutureTask and org.testng.internal.thread.Async$AsyncTask are in unnamed module of loader 'app')
	at org.testng.internal.thread.Async$AsyncTask.compareTo(Async.java:22)
	at java.base/java.util.concurrent.PriorityBlockingQueue.siftUpComparable(PriorityBlockingQueue.java:353)
	at java.base/java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:475)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at org.testng.internal.thread.Async.run(Async.java:18)
	at org.testng.internal.invokers.MethodRunner.runInParallel(MethodRunner.java:143)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:982)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Is the issue reproducible on runner?
- Gradle

### Test case sample
```java
public class ClassCastExceptionExample implements IAlterSuiteListener {
  @Override
  public void alter(List<XmlSuite> suites) {
    suites.get(0).shouldUseGlobalThreadPool(true);
    suites.get(0).setThreadCount(3);
    suites.get(0).setParallel(XmlSuite.ParallelMode.METHODS);
  }

  @DataProvider(parallel = true)
  public Object[] dp() {return new Object[]{1};}

  @Test(dataProvider = "dp") public void test1(int dp) {}
  @Test(dataProvider = "dp") public void test3(int dp) {}
  @Test public void test2() {}
  @Test public void test4() {}
}
```
```
//gradle
tasks.test {
    useTestNG() {
        testNameIncludePatterns = ["ClassCastExceptionExample.*"]
        listeners.add('ClassCastExceptionExample')
    }
}
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### PR DESCRIPTION
**Pull request by krmahadevan**
If a user is not using priority driven tests then
TestNG should not consider any method interceptors that a user may be using.

Closes #3179

Fixes #3179 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed a `ClassCastException` when using the `shouldUseGlobalThreadPool(true)` property.
  - Improved error reporting for test timeouts by ensuring stack traces are propagated correctly.

- **Refactor**
  - Enhanced the internal test execution ordering mechanism to better handle prioritization.

- **Tests**
  - Added new tests to verify that priority-agnostic interceptors do not cause exceptions.
  - Introduced a sample test suite demonstrating parallel, data-driven test execution.

### CODE REVIEW

File: testng-core/src/main/java/org/testng/TestRunner.java [hunk 1]
```diff
@@ -662,9 +663,10 @@ private static Comparator<ITestNGMethod> newComparator(boolean needPrioritySort)
     return needPrioritySort ? new TestMethodComparator() : null;
   }
 
-  private boolean sortOnPriority(ITestNGMethod[] interceptedOrder) {
-    return m_methodInterceptors.size() > 1
-        || Arrays.stream(interceptedOrder).anyMatch(m -> m.getPriority() != 0);
+  private Pair<Boolean, Boolean> sortOnPriority(ITestNGMethod[] interceptedOrder) {
+    return new Pair<>(
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestRunner.java:667]: Using pair here makes too much noise.
As it is only 2 lines, used only once, just remove the method and use appropriate var names.

**Review by juherr — CHANGES_REQUESTED** [review]

File: testng-core/src/main/java/org/testng/TestRunner.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestRunner.java]: Fixed. Please check now

**Review by juherr — APPROVED** [review]
