### PR TITLE
Fix NPE when suite includes include/exclude group definitions.

### LINKED ISSUE #1180: NullPointerException on getting excluded/included groups
TestNg Version 6.9.13.6

My testng.xml file contains block `<groups></groups>` with some defined excluded groups in. I'm running the tests by using Maven. Just on starting I've got the following NPE:

```
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project ui-test: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process] 
org.testng.TestNGException: java.lang.NullPointerException
at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:325)
at org.testng.TestNG.run(TestNG.java:1081)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290) 
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NullPointerException
at org.testng.xml.XmlSuite.getExcludedGroups(XmlSuite.java:1072)
at org.testng.xml.XmlTest.getExcludedGroups(XmlTest.java:227)
at org.testng.internal.OverrideProcessor.process(OverrideProcessor.java:37)
at org.testng.xml.Parser.parse(Parser.java:225)
at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:305)
```

Everything works OK on the previous older version (e.g. 6.9.8)

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes # .
### Did you remember to?
- [X] Add test case(s)
- [X] Update `CHANGES.txt`

Fixes #1180

### CODE REVIEW

**Comment by krmahadevan** [comment]
@cbeust / @juherr - Can you please help review this PR and help get this merged ?

**Comment by cbeust** [comment]
Good catch, Krishnan!

File: src/test/java/org/testng/xml/XmlSuiteTest.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
+package org.testng.xml;
+
+import org.testng.Assert;
+import org.testng.annotations.Test;
+import test.SimpleBaseTest;
+
+import java.util.Arrays;
+
+public class XmlSuiteTest extends SimpleBaseTest {
```
Comment (krmahadevan) [inline src/test/java/org/testng/xml/XmlSuiteTest.java]: @juherr : I will keep that in mind going forward. Thanks for pointing it out.
