### PR TITLE
GITHUB-2888 - don't fail test with dataProvider if skipped

### LINKED ISSUE #2888: Skipped Tests with DataProvider appear as failed
### TestNG Version
7.7.1

How to reproduce?

**Context: I don't want a DataProvider to execute if the test is going to be skipped**

1. Create a TestListener that implements both IDataProviderListener and ITestListener
2. Override the onTestStart method to skip if certain conditions are matched (ex: the test contains a specific group)
3. Also override the beforeDataProviderExecution method to skip the DataProvider if the test contains a skip condition
4. Create a TestFile that uses TestListener as Listener
5. Add a test with a DataProvider that meets the skip condition
6. (Optional) Add a test without a DataProvider that meets the skip condition to compare
7. Run the test/s

### Expected behavior
Skipping a test with a DataProvider should skip the test and the DataProvider, the test result should show that the test was Skipped.
The test with the DP and one without it should behave the same, everything should be skipped

### Actual behavior
The test with the DataProvider is shown as failed with a SkipException

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
Here you have a small IntelliJ project containing a test file with two tests, one has the dumb DataProvider:
https://github.com/jmoreira18/TestNG-DataProvider-issue-demo

#### Code comments

[This part of the code](https://github.com/cbeust/testng/blame/master/testng-core/src/main/java/org/testng/internal/invokers/TestInvoker.java#L925) is not taking into account that it could be a SkipException, then it's treating it as a failure and failing the test
```
boolean bubbleUpFailures =
        m_configuration.isPropagateDataProviderFailureAsTestFailure() || bag.isBubbleUpFailures();

if (throwable instanceof TestNGException || bubbleUpFailures) {
        tr.setStatus(ITestResult.FAILURE);
        m_notifier.addFailedTest(arguments.getTestMethod(), tr);
} else {
        tr.setStatus(ITestResult.SKIP);
        m_notifier.addSkippedTest(arguments.getTestMethod(), tr);
}
```

Thanks in advance!

### PR DESCRIPTION
**Pull request by jmoreira18**
Fixes #2888

If you want to create a listener that would skip a DataProvider in case a Test will be skipped, the Test was marked as FAILED, instead of SKIPPED

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`
- [x] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: testng-core/src/test/java/test/dataprovider/issue2888/SkipDataProviderTest.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
+package test.dataprovider.issue2888;
+
+import org.testng.Assert;
+import org.testng.annotations.DataProvider;
+import org.testng.annotations.Listeners;
+import org.testng.annotations.Test;
+import test.SimpleBaseTest;
+
+@Listeners({SkipDataProviderListener.class})
+public class SkipDataProviderTest extends SimpleBaseTest {
```
Comment (juherr) [inline testng-core/src/test/java/test/dataprovider/issue2888/SkipDataProviderTest.java:10]: It is a sample, not a test.
Suffix it by Sample instead of Test and remove dependency to SimpleBaseTest.

File: testng-core/src/test/java/test/dataprovider/issue2888/SkipDataProviderListener.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+  @Override
+  public void onTestSkipped(ITestResult result) {}
+
+  @Override
+  public void beforeDataProviderExecution(
+      IDataProviderMethod dataProviderMethod, ITestNGMethod method, ITestContext iTestContext) {
+    skipIfSkipMe(method);
+  }
+
+  private void skipIfSkipMe(ITestNGMethod testNGMethod) {
```
Comment (juherr) [inline testng-core/src/test/java/test/dataprovider/issue2888/SkipDataProviderListener.java:27]: Could be static

**Review by juherr — CHANGES_REQUESTED** [review]
Thank for the contribution 👍

**Review by juherr — APPROVED** [review]

**Review by krmahadevan — APPROVED** [review]
