### PR TITLE
Fix GitHub issue 1493

### LINKED ISSUE #1493: wrong exception msg when timeout on test
6.11 and also on 6.12 as @juherr mentioned in testng-dev group.
### Expected behavior
Exception notifying about timeout during the test

### Actual behavior
java.lang.ArrayIndexOutOfBoundsException: 0

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

[sample.zip](https://github.com/cbeust/testng/files/1184156/sample.zip)

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1493

When TestNG triggers a timeout for a test because
it ran for too long, we are trying to construct 
the stack trace based on the number of threads.
But merely instantiating an exception object itself
gives us the current thread’s stack trace. 
Fixed this by removing the stack trace construction
logic.

Fixes #1493 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr

File: src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
+package test.github1493;
```
Comment (juherr) [inline src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java]: Should be moved into `test.timeout` package

File: src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+import org.testng.TestNG;
+import org.testng.annotations.Test;
+import org.testng.internal.thread.ThreadTimeoutException;
+import org.testng.xml.XmlSuite;
+import test.SimpleBaseTest;
+
+import java.util.Arrays;
+import java.util.List;
+
+public class EnsureTimeoutsErrorProperlyTest extends SimpleBaseTest {
```
Comment (juherr) [inline src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java]: Missing from the suite.

File: src/main/java/org/testng/internal/MethodInvocationHelper.java [hunk 3]
```diff
@@ -288,7 +288,6 @@ private static void invokeWithTimeoutWithNewExecutor(ITestNGMethod tm, Object in
       ThreadTimeoutException exception = new ThreadTimeoutException("Method "
           + tm.getQualifiedName() + "()"
           + " didn't finish within the time-out " + realTimeOut);
-      exception.setStackTrace(exec.getStackTraces()[0]);
```
Comment (juherr) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: I think we should keep it. Could add a test which throws an exception before the end of the timeout?

We can use a switch on the size: 0 = ignore, 1 = previous behavior, default = 1 + warn

**Review by juherr — CHANGES_REQUESTED** [review]

File: src/main/java/org/testng/internal/MethodInvocationHelper.java (hunk 3 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: > Could add a test which throws an exception before the end of the timeout?
That scenario does not traverse this code path.  because when we throw a `ThreadTimedoutException` we explicitly check if `exec.awaitTermination(realTimeOut)` returns false and when an exception is thrown before a timeout that doesn't happen.

> I think we should keep it.
I am not able to see any scenario wherein it would be used. That was why I removed off that section.

File: src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java (hunk 1 above)
Comment (krmahadevan) [inline src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java]: fixed

File: src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java (hunk 2 above)
Comment (krmahadevan) [inline src/test/java/test/github1493/EnsureTimeoutsErrorProperlyTest.java]: fixed

File: src/main/java/org/testng/internal/MethodInvocationHelper.java (hunk 3 above)
Comment (juherr) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: Ok, thanks for the explanations.

I just don't understand why `getStackTraces` returns an empty array.
I think something is broken in `ThreadFactoryImpl` which doesn't add new threads in the list.

Could you check?

File: src/test/java/test/timeout/github1493/EnsureTimeoutsErrorProperlyTest.java [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+import org.testng.xml.XmlSuite;
+import test.SimpleBaseTest;
+
+import java.util.Arrays;
+import java.util.List;
+
+public class EnsureTimeoutsErrorProperlyTest extends SimpleBaseTest {
+
+    @Test
+    public void testWithOnlyOneThread() {
```
Comment (juherr) [inline src/test/java/test/timeout/github1493/EnsureTimeoutsErrorProperlyTest.java]: Maybe you can just add it into `TimeOutTest`

File: src/main/java/org/testng/internal/MethodInvocationHelper.java (hunk 3 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: I guess its perhaps because `org.testng.internal.MethodInvocationHelper#invokeWithTimeoutWithNewExecutor` is designed to just work with 1 thread due to this line

```java
IExecutor exec = ThreadUtil.createExecutor(1, tm.getMethodName());
```
So I guess there would never be more than 1 thread.

Moreover, if you look at `org.testng.internal.MethodInvocationHelper#invokeWithTimeoutWithNewExecutor` implementation, you would notice that it first interrupts all the running threads by calling `exec.stopNow();` and then trying to access the threads that the underlying factory would have. That explains why its always an empty array.

Lastly I would still like to understand what is the value add that we would be adding by copy pasting the stacktrace. The thread has been interrupted (and that too by TestNG). The error msg IMHO is what adds a bit more value.

File: src/test/java/test/timeout/github1493/EnsureTimeoutsErrorProperlyTest.java (hunk 4 above)
Comment (krmahadevan) [inline src/test/java/test/timeout/github1493/EnsureTimeoutsErrorProperlyTest.java]: Yeah, I guess so. No point in adding one more new class just for a new test method. I will fix this once I go home.

File: src/main/java/org/testng/internal/MethodInvocationHelper.java (hunk 3 above)
Comment (juherr) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: `ThreadUtil.createExecutor(1, tm.getMethodName());` can explain why we took only the first element of the array (a comment missed before).

But it doesn't explain why `ThreadFactoryImpl` doesn't feed its `threads` list.
https://github.com/cbeust/testng/blob/15a824bd8d3658e7070b7cf105f2adc011d07000/src/main/java/org/testng/internal/thread/ThreadUtil.java#L90
I can't remember why I didn't keep it in https://github.com/cbeust/testng/commit/1b8bd784ee975cf3983ebb7c12eb539985720fbb#diff-a8556e01a426efbe66d3b76a06249c04L108
I guess the issue will be fixed if you restore the thread list usage :)

Comment (krmahadevan) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: > But it doesn't explain why ThreadFactoryImpl doesn't feed its threads list.

Because new threads are created in `org.testng.internal.thread.TestNGThreadFactory` and the base class doesn't have visibility to the `org.testng.internal.thread.ThreadUtil.ThreadFactoryImpl#threads` data member. I have now fixed this.

**Comment by krmahadevan** [comment]
@juherr - I have addressed all the observations. Please let me know if this is fine now.

**Comment by krmahadevan** [comment]
Except for this outstanding question :) 

> Lastly I would still like to understand what is the value add that we would be adding by copy pasting the stacktrace into the exception. The thread has been interrupted (and that too by TestNG). The error msg IMHO is what adds a bit more value.

File: src/main/java/org/testng/internal/MethodInvocationHelper.java (hunk 3 above)
Comment (juherr) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: :+1:

File: src/main/java/org/testng/internal/MethodInvocationHelper.java [hunk 5]
```diff
@@ -288,7 +288,10 @@ private static void invokeWithTimeoutWithNewExecutor(ITestNGMethod tm, Object in
       ThreadTimeoutException exception = new ThreadTimeoutException("Method "
           + tm.getQualifiedName() + "()"
           + " didn't finish within the time-out " + realTimeOut);
-      exception.setStackTrace(exec.getStackTraces()[0]);
+      StackTraceElement[][] stacktraces = exec.getStackTraces();
+      if (stacktraces.length > 0) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/MethodInvocationHelper.java]: Is it possible to have something different to 0?
Should we log something if the length != 0 because they are unexpected values?

**Review by juherr — APPROVED** [review]
LGTM :+1: 
Maybe we just need to add a log.
Ping @cbeust

**Comment by juherr** [comment]
About your question, I can't answer because I don't know what was the initial objective.
By default, I like to keep as it is and it looks it was done with a reason I ignore. It's not clear to me what is the difference between the 2 solutions.
Maybe you right and we should remove it :)
I have no problem with that but previously I've just wanted to understand the root cause of the preblem.
At least, we already found a regression I made and fix it.
