### PR TITLE
Fixing DynamicGraph issue with not separating priorities

### LINKED ISSUE #1360: TestNG does not distinguish between methods of different priorities
TestNG 6.10

### Expected behavior
Lets say there are 3 test classes in which each of them has 3 methods with priorities set as 1,2,3.
The expectation would be that TestNG first executes 3 methods with priority 1, followed by the next 3 methods with priority 2 and finally the 3 methods with priority 3.

### Actual behavior

Currently TestNG first executes 3 methods with priority 1 and then 6 methods with priority 2 and 3.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

```java
public class TestNG1 {
    @Test(priority = 1)
    public void test1TestNG1() {
        Assert.assertTrue(true);
    }

    @Test(priority = 2)
    public void test2TestNG1() {
        Assert.assertTrue(true);
    }

    @Test(priority = 3)
    public void test3TestNG1() {
        Assert.assertTrue(true);
    }
}

```

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #1360 
Closes #1360 

Currently DynamicGraph does not group 
dependent methods (i.e., methods which have lower
priorities and need higher priority methods to run
first before they can get executed) based on priorities.
This causes TestNG to just segregate independent 
methods (method with the lowest priority) and 
dependent methods.

Fixed this anomaly by introducing grouping of same 
weighted edges with the same priority.

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr - Can you please help take a look at this ?

File: src/main/java/org/testng/internal/DynamicGraph.java [hunk 1]
```diff
@@ -31,11 +31,17 @@
     private final T from;
     private final T to;
     private int weight;
+    private int order;
 
     private Edge(T from, T to, int weight) {
+      this(from, to, weight,0);
```
Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: Typo: space missing

File: src/main/java/org/testng/internal/DynamicGraph.java [hunk 2]
```diff
@@ -31,11 +31,17 @@
...
+    }
+
+    private Edge(T from, T to, int weight, int order) {
       this.from = from;
       this.to = to;
       this.weight = weight;
+      this.order=order;
```
Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: Typo: spaces missing

File: src/main/java/org/testng/internal/DynamicGraph.java [hunk 3]
```diff
@@ -31,11 +31,17 @@
     private final T from;
     private final T to;
     private int weight;
+    private int order;
```
Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: set `final` if possible.

File: src/main/java/org/testng/internal/DynamicGraph.java [hunk 4]
```diff
@@ -46,6 +52,12 @@ public void addNode(T node) {
     m_nodesReady.add(node);
   }
 
+  public void addEdge(int weight, T from, T to, int order) {
+    List<Edge<T>> edges = Lists.newArrayList();
+    edges.add(new Edge<>(from, to, weight, order));
+    addEdges(edges);
```
Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: `addEdges(Collections.singletonList(new Edge<>(from, to, weight, order)));`

But you can extract and use a new method too: `private void addEdge(Edge<T> edge)` (in fact, my favorite solution)

File: src/main/java/org/testng/internal/DynamicGraph.java [hunk 5]
```diff
@@ -129,6 +143,23 @@ private int getLowestEdgePriority(List<T> nodes) {
     return lowerPriority == null ? 0 : lowerPriority;
   }
 
+  private int getLowestOrder(List <T> nodes) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: Typo: `List<T>`

File: src/test/java/test/DynamicGraphTest.java [hunk 6]
```diff
@@ -126,4 +139,71 @@ public void test2() {
...
+    List<ITestNGMethod> p3Methods = graph.getFreeNodes();
+    Assert.assertEquals(p3Methods.size(), 3);
+    graph.setStatus(p3Methods, Status.FINISHED);
+    for (ITestNGMethod p3Method : p3Methods) {
+      Assert.assertTrue(expected.contains(constructName(p3Method)));
+    }
+
+  }
+
+  private String constructName(ITestNGMethod method) {
```
Comment (juherr) [inline src/test/java/test/DynamicGraphTest.java]: `static` is missing

File: src/test/java/test/DynamicGraphTest.java [hunk 7]
```diff
@@ -126,4 +139,71 @@ public void test2() {
...
+    XmlTest xmlTest = createXmlTest(xmlSuite, "1360_Tests", classes);
+    IAnnotationFinder annotationFinder = new JDK15AnnotationFinder(new DefaultAnnotationTransformer());
+    List<ITestNGMethod> methods = Lists.newArrayList();
+    for (Class<?> clazz : classes) {
+      methods.addAll(
+          Arrays.asList(
+              AnnotationHelper.findMethodsWithAnnotation(clazz, ITestAnnotation.class, annotationFinder, xmlTest)
+          )
+      );
+    }
```
Comment (juherr) [inline src/test/java/test/DynamicGraphTest.java]: I really love the hack you made! :D 
Could you extract it in a method? Something like `List<ITestNGMethod> extractTestNGMethods(Class<?>... classes)`

File: src/test/java/test/DynamicGraphTest.java [hunk 8]
```diff
@@ -126,4 +139,71 @@ public void test2() {
...
+          graph.addEdge(1, p1Method, p0Method, p1Method.getPriority());
+        }
+      }
+      previousPriority = currentPriority;
+    }
+    List<String> expected = Arrays.asList("TestNG1.test1TestNG1", "TestNG2.test1TestNG2", "TestNG3.test1TestNG3");
+    List<ITestNGMethod> p1Methods = graph.getFreeNodes();
+    Assert.assertEquals(p1Methods.size(), 3);
+    graph.setStatus(p1Methods, Status.FINISHED);
+    for (ITestNGMethod p1Method : p1Methods) {
```
Comment (juherr) [inline src/test/java/test/DynamicGraphTest.java]: It's ok but you should have a look at AssertJ :)

**Review by juherr — COMMENTED** [review]
Some little things! Don't forget to squash commits at the end if possible.

File: src/main/java/org/testng/internal/DynamicGraph.java (hunk 3 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/DynamicGraph.java]: I chose to leave this as `weight`

File: src/test/java/test/DynamicGraphTest.java (hunk 8 above)
Comment (krmahadevan) [inline src/test/java/test/DynamicGraphTest.java]: Sure. I will take a look at that.

**Comment by krmahadevan** [comment]
@juherr - I have fixed all the review comments.

File: src/main/java/org/testng/internal/DynamicGraph.java (hunk 3 above)
Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: Could you set `final` on both order and weight if possible?

**Review by juherr — APPROVED** [review]
LGTM 👍 

Ping @cbeust

File: src/test/java/test/DynamicGraphTest.java [hunk 9]
```diff
@@ -126,4 +132,60 @@ public void test2() {
...
+    }
+
+    expected = Arrays.asList("TestNG1.test3TestNG1", "TestNG2.test3TestNG2", "TestNG3.test3TestNG3");
+    List<ITestNGMethod> p3Methods = graph.getFreeNodes();
+    Assert.assertEquals(p3Methods.size(), 3);
+    graph.setStatus(p3Methods, Status.FINISHED);
+    for (ITestNGMethod p3Method : p3Methods) {
+      Assert.assertTrue(expected.contains(constructName(p3Method)));
+    }
+
```
Comment (cbeust) [inline src/test/java/test/DynamicGraphTest.java]: Lot of repeated code here, you should be able to extract this logic in a method and invoke it three times.

File: src/main/java/org/testng/internal/DynamicGraph.java [hunk 10]
```diff
@@ -46,6 +53,10 @@ public void addNode(T node) {
     m_nodesReady.add(node);
   }
 
+  public void addEdge(int weight, T from, T to, int order) {
```
Comment (cbeust) [inline src/main/java/org/testng/internal/DynamicGraph.java]: I got confused trying to understand the parameter ordering, I suggest you make both the `Edge` constructor and the `addEdge()` method use the same ordering, e.g. `from`, `to`, `weight`, `order`.

Comment (juherr) [inline src/main/java/org/testng/internal/DynamicGraph.java]: +1 but I put `weight` as the first param because I wanted to keep a coherence with `public void addEdge(int weight, T from, T... tos)` where `tos` must be at the end.

I don't know what could be the best solution.

Comment (cbeust) [inline src/main/java/org/testng/internal/DynamicGraph.java]: Either order is fine with me, just be consistent :)

File: src/test/java/test/DynamicGraphTest.java (hunk 9 above)
Comment (krmahadevan) [inline src/test/java/test/DynamicGraphTest.java]: Fixed it.

File: src/main/java/org/testng/internal/DynamicGraph.java (hunk 10 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/DynamicGraph.java]: Now both `Edge` constructor and `addEdge()` start off with `weight, order`

**Comment by krmahadevan** [comment]
@cbeust - I have fixed the review comments. Can you please check if this is now good to be merged ?

**Comment by cbeust** [comment]
@krmahadevan Can you look into the Travis failures?

Just want to make sure before I roll your change in 6.11. Thanks!

**Comment by krmahadevan** [comment]
@cbeust 
The [JDK8](https://travis-ci.org/cbeust/testng/jobs/206044289) build failed in one of the concurrency tests.
```
 Failures in <suite> :TestNG, <test> :Parallelization
    test.thread.parallelization.ParallelByMethodsTestCase1Scenario2.verifyThatTestMethodsRunInParallelThreads()
    StackTrace:
     java.lang.AssertionError: The expected maximum number of methods to execute simultaneously is 20 for TestSuiteB-ThreeTestClassTest so no more than 20 methods should be executing at the same time. 
```

The [JDK7](https://travis-ci.org/cbeust/testng/jobs/206044290) build error'ed out after running for 12 minutes

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

Would it be possible for you to re-trigger the build ? I can trigger a build only when I push in a change and currently from work, its not possible for me.
