### PR TITLE
Provide insight into “Who caused my test to skip”

### LINKED ISSUE #1869: Can't differentiate between skip source of test method
When a configuration method fails, tests which are skipped as a consequence are injected with the failure cause.
This change was introduced to resolve issue #674. The accepted fix is: #1242 

While this fix gives valuable information that wasn't present before, it presents a new challenge in understanding where the Throwable originated from. Did the test method throw this Throwable itself, and if not, which previous invocation _did_ throw this exception?

### LINKED ISSUE #1878: Provide visibility into the actual method (config/test) that caused a downstream test to be skipped
### Expected behavior

When a test method gets skipped, it would be great if TestNG provided the user visibility into all TestNG methods (either config or test methods) that caused a test method to be skipped.

### Actual behavior

Currently this functionality is not supported in TestNG.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [ ] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

The following use-cases are to be supported.

1. When a `@BeforeSuite` or `@BeforeTest` method fails, report it as the reason for skip for all tests that got skipped.
2. When a `@BeforeClass` or a `@BeforeMethod` fails, report it as a reason for skip for all tests that belong to the same instance or the child class instances.
3. When a `@BeforeGroups` fails, report all the failed methods that belonged to the group as the reason for skip for all downstream tests.
4. When a test method fails, report it as a reason for skip for all downstream methods.

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1878
Closes #1869

Fixes #1878  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/ITestResult.java [hunk 1]
```diff
@@ -88,4 +91,13 @@
    * @param wasRetried - <code>true</code> if the test was retried and <code>false</code> otherwise.
    */
   void setWasRetried(boolean wasRetried);
+
+  /**
+   * @return - The list of either upstream method(s) or configuration method(s) whose failure led to
+   * the current method being skipped. If there were no such reasons then an empty list is
```
Comment (juherr) [inline src/main/java/org/testng/ITestResult.java]: Is it possible to have a skipped method without reason?

File: src/main/java/org/testng/internal/TestMethodWithDataProviderMethodWorker.java [hunk 2]
```diff
@@ -127,13 +127,7 @@ public TestMethodWithDataProviderMethodWorker(
...
         while (m_invocationCount-- > 0) {
           ITestResult r =
-              new TestResult(
-                  m_testMethod.getTestClass(),
-                  m_testMethod,
-                  null,
-                  start,
-                  System.currentTimeMillis(),
-                  m_testContext);
+              TestResult.newEndTimeAwareTestResult(m_testMethod, null, start, m_testContext);
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestMethodWithDataProviderMethodWorker.java]: Instead of `null`, maybe we can have a custom Exception like TooMuchInvoicationCountException

File: src/main/java/org/testng/internal/TestResult.java [hunk 3]
```diff
@@ -33,33 +38,49 @@
...
 
-  public TestResult(
-      IClass testClass,
-      ITestNGMethod method,
-      Throwable throwable,
-      long start,
-      long end,
-      ITestContext context) {
-    init(testClass, method, throwable, start, end, context);
+  public static TestResult newTestResultWithCauseAs(ITestNGMethod method, Throwable t,
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: Try to keep the same param order: `method, context, throwable, start`

File: src/main/java/org/testng/internal/TestResult.java [hunk 4]
```diff
@@ -320,4 +336,90 @@ public boolean wasRetried() {
   public void setWasRetried(boolean wasRetried) {
     this.m_wasRetried = wasRetried;
   }
+
+  public List<ITestNGMethod> getSkipCausedBy() {
+    if (this.m_status != SKIP) {
+      return Lists.newArrayList();
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: 2 calls will return 2 different instances.

File: src/main/java/org/testng/internal/TestResult.java [hunk 5]
```diff
@@ -320,4 +336,90 @@ public boolean wasRetried() {
...
+      return Collections.unmodifiableList(skippedDueTo);
+    }
+    skipAnalysed = true;
+    //check if there were any config failures
+    Set<ITestResult> skippedConfigs = m_context.getFailedConfigurations().getAllResults();
+    for (ITestResult skippedConfig : skippedConfigs) {
+      if (isGlobalFailure(skippedConfig) ||
+          isRelated(skippedConfig) || belongToSameGroup(skippedConfig)) {
+        skippedDueTo.add(skippedConfig.getMethod());
+        return Collections.unmodifiableList(skippedDueTo);
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: Why only collect the first match? What if many matches?

File: src/main/java/org/testng/internal/TestResult.java [hunk 6]
```diff
@@ -320,4 +336,90 @@ public boolean wasRetried() {
...
+    List<ITestResult> allfailures = Lists.newArrayList(m_context.getFailedTests().getAllResults());
+    allfailures.addAll(m_context.getFailedButWithinSuccessPercentageTests().getAllResults());
+    skippedDueTo = allfailures.stream()
+        .map(ITestResult::getMethod)
+        .filter(each -> upstreamMethods.contains(each.getQualifiedName()))
+        .collect(Collectors.toList());
+    return Collections.unmodifiableList(skippedDueTo);
+  }
+
+  private boolean isGlobalFailure(ITestResult result) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: static here and later

File: src/main/java/org/testng/ITestResult.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/ITestResult.java]: No its not possible. The only time when the return value would be empty is when its queried for a non skipped method. Fixed the javadocs to clarify that.

File: src/main/java/org/testng/internal/TestMethodWithDataProviderMethodWorker.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestMethodWithDataProviderMethodWorker.java]: What would we be achieving by introducing a new exception ?

File: src/main/java/org/testng/internal/TestResult.java (hunk 3 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: Fixed

File: src/main/java/org/testng/internal/TestResult.java (hunk 4 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: I didn't quite understand this comment. can you please explain ? If the `TestResult` is not for a skipped method, then an empty list is returned. For everything else, the reason is computed and then returned.

File: src/main/java/org/testng/internal/TestResult.java (hunk 5 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: @juherr - Is that even possible ?

File: src/main/java/org/testng/internal/TestResult.java (hunk 6 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: Only this method can be made static. Fixed it.

**Comment by krmahadevan** [comment]
@juherr - Fixed all the review comments.... Please help take a look

File: src/main/java/org/testng/ITestResult.java [hunk 7]
```diff
@@ -88,4 +91,13 @@
...
    */
   void setWasRetried(boolean wasRetried);
+
+  /**
+   * @return - The list of either upstream method(s) or configuration method(s) whose failure led to
+   * the current method being skipped. An empty list is returned when the current method is not
+   * a skipped method.
+   */
+  default List<ITestNGMethod> getSkipCausedBy() {
+    return Lists.newArrayList();
```
Comment (juherr) [inline src/main/java/org/testng/ITestResult.java]: Maybe unmodifiable

File: src/main/java/org/testng/internal/TestResult.java (hunk 4 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: @juherr - Just trying to understand.. How would that matter? I cache a valid list, because it needs to be computed and so I was trying to save the effort there. But this is just an empty list. How would it matter to an end user ?

File: src/main/java/org/testng/internal/TestResult.java (hunk 5 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: Ok.. So there are two scenarios with configs.. 

1. `@BeforeSuite/@BeforeTest/@BeforeClass` - If one of these failed then the cause is just 1.
2. `@BeforeGroups` - If this failed then there could be more than one method. So forming a list here.

**Comment by krmahadevan** [comment]
@juherr - Please check if all is well now.

File: src/main/java/org/testng/internal/TestResult.java (hunk 4 above)
Comment (juherr) [reply src/main/java/org/testng/internal/TestResult.java]: You are right, it's a little optimization but by default:
> Constructs an empty list with an initial capacity of ten.
https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#ArrayList--

Maybe use Collections.emptyList instead

File: src/main/java/org/testng/internal/TestResult.java [hunk 8]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+      List<String> upstreamGroups = Arrays.asList(m_method.getGroupsDependedUpon());
+      if (upstreamGroups.isEmpty()) {
+        return Collections.unmodifiableList(skippedDueTo);
+      }
+      List<ITestResult> allFailures = Lists.newArrayList(m_context.getFailedTests().getAllResults());
+      allFailures.addAll(m_context.getFailedButWithinSuccessPercentageTests().getAllResults());
+      skippedDueTo = allFailures.stream()
+          .map(ITestResult::getMethod)
+          .filter(each -> {
+            List<String> currentMethodGroups = Arrays.asList(each.getGroups());
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: you should be able to add 1 or 2 other map usages here:
```java
skippedDueTo = allFailures.stream()
          .map(ITestResult::getMethod)
          .map(method -> Arrays.asList(method.getGroups())
          .map(groups -> Lists.intersection(upstreamGroups, currentMethodGroups))
          .filter(List::isEmpty)
```

File: src/main/java/org/testng/internal/TestResult.java [hunk 9]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+
+      return Collections.unmodifiableList(skippedDueTo);
+    }
+
+    //So we have dependsOnMethod failures
+    List<ITestResult> allfailures = Lists.newArrayList(m_context.getFailedTests().getAllResults());
+    allfailures.addAll(m_context.getFailedButWithinSuccessPercentageTests().getAllResults());
+    skippedDueTo = allfailures.stream()
+        .map(ITestResult::getMethod)
+        .filter(each -> upstreamMethods.contains(each.getQualifiedName()))
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: Prefer a less generic name. Maybe `method`?

File: src/main/java/org/testng/internal/TestResult.java [hunk 10]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+  private boolean belongToSameGroup(ITestResult result) {
+    ITestNGMethod m = result.getMethod();
+    if (!m.isBeforeGroupsConfiguration()) {
+      return false;
+    }
+    String[] mygroups = this.m_method.getGroups();
+    if (mygroups.length == 0) {
+      return false;
+    }
+    List<String> cfgMethodGroups = Arrays.asList(result.getMethod().getGroups());
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: `m.getGroups()`

File: src/main/java/org/testng/internal/TestResult.java [hunk 11]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+    if (cfgMethodGroups.isEmpty()) {
+      return false;
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: Maybe we can avoid the list conversion in that case.

File: src/main/java/org/testng/internal/TestResult.java [hunk 12]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+    }
+
+    for (String each : mygroups) {
+      if (cfgMethodGroups.contains(each)) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: Use stream?

**Review by juherr — COMMENTED** [review]
Functional looks ok, just few style remarks

File: src/main/java/org/testng/internal/TestResult.java [hunk 13]
```diff
@@ -33,33 +38,49 @@
...
+
+  public static TestResult newEndTimeAwareTestResult(ITestNGMethod method, ITestContext context,
+      Throwable throwable, long start) {
+    TestResult result = newEmptyTestResult();
+    long time = System.currentTimeMillis();
+    result.init(method, throwable, start, time, context);
+    return result;
   }
 
   public void init(
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: @juherr - That is currently not possible. This method is being used outside.  There is currently one use case from within `org.testng.internal.Invoker#invokeMethod` wherein instantiation and initialisation is being done in two separate explicit calls. So refactoring this would need additional changes and that bloats my changeset. I am happy to do this as a separate PR.

File: src/main/java/org/testng/internal/TestResult.java [hunk 14]
```diff
@@ -33,33 +38,49 @@
...
-    init(testClass, method, throwable, start, end, context);
+  public static TestResult newTestResultWithCauseAs(ITestNGMethod method, ITestContext ctx,
+      Throwable t) {
+    TestResult result = newEmptyTestResult();
+    long time = System.currentTimeMillis();
+    result.init(method, t, time, time, ctx);
+    return result;
+  }
+
+  public static TestResult newEndTimeAwareTestResult(ITestNGMethod method, ITestContext context,
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: fixed.

File: src/main/java/org/testng/internal/TestResult.java [hunk 15]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
   public void setWasRetried(boolean wasRetried) {
     this.m_wasRetried = wasRetried;
   }
+
+  public List<ITestNGMethod> getSkipCausedBy() {
+    if (this.m_status != SKIP) {
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: fixed

File: src/main/java/org/testng/internal/TestResult.java [hunk 16]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+      return Collections.unmodifiableList(skippedDueTo);
+    }
+    if (skipAnalysed) {
+      return Collections.unmodifiableList(skippedDueTo);
+    }
+    skipAnalysed = true;
+    //check if there were any config failures
+    Set<ITestResult> skippedConfigs = m_context.getFailedConfigurations().getAllResults();
+    for (ITestResult skippedConfig : skippedConfigs) {
+      if (isGlobalFailure(skippedConfig) || isRelated(skippedConfig) ) {
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: fixed

File: src/main/java/org/testng/internal/TestResult.java [hunk 17]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+        //If there's a failure in @BeforeTest/@BeforeSuite/@BeforeClass
+        //then the reason is most often just one method.
+        skippedDueTo.add(skippedConfig.getMethod());
+        return Collections.unmodifiableList(skippedDueTo);
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: Is there anything wrong with doing this? I would like to understand more. Exit when a condition happens is what I prefer more, rather than reducing the number of exits and having a generic code. Maybe a programming style even. I would be happy to change, if you could please let me know the pitfalls with that thought process.

File: src/main/java/org/testng/internal/TestResult.java [hunk 18]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+      //If we found atleast one skipped due to reason, then its time to return back.
+      return Collections.unmodifiableList(skippedDueTo);
+    }
+    //Looks like we didnt have any configuration failures. So some upstream method perhaps failed.
+    List<String> upstreamMethods = Arrays.asList(m_method.getMethodsDependedUpon());
+    if (upstreamMethods.isEmpty()) {
+      //Maybe group dependencies exist ?
+      List<String> upstreamGroups = Arrays.asList(m_method.getGroupsDependedUpon());
+      if (upstreamGroups.isEmpty()) {
+        return Collections.unmodifiableList(skippedDueTo);
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: fixed

File: src/main/java/org/testng/internal/TestResult.java [hunk 19]
```diff
@@ -320,4 +336,100 @@ public boolean wasRetried() {
...
+      }
+      List<ITestResult> allFailures = Lists.newArrayList(m_context.getFailedTests().getAllResults());
+      allFailures.addAll(m_context.getFailedButWithinSuccessPercentageTests().getAllResults());
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: I ended up using `Lists.merge`. `Stream.concat()` is a cool mechanism. But I cant use that because I will end up losing access to instance references in the list which is needed for my filtering.

File: src/main/java/org/testng/internal/TestResult.java (hunk 8 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: No this will not work. The `map()` causes a transformation.

So when you do `.map(method -> Arrays.asList(method.getGroups())`, you have caused the stream to transform from a `Stream<ITestNGMethod>` to a `Stream<List<String>>` which is not useful for me. I would like to filter out methods that satisfy my filtering criteria.

Here's my understanding of these two:
`.filter` --> lets me apply selection criteria to filter out the output from the stream
`.map` --> causes me to apply some conversion logic and transform a stream from one form to the other.

File: src/main/java/org/testng/internal/TestResult.java (hunk 9 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: ok fixed.

File: src/main/java/org/testng/internal/TestResult.java (hunk 10 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: fixed

File: src/main/java/org/testng/internal/TestResult.java (hunk 11 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: fixed

File: src/main/java/org/testng/internal/TestResult.java (hunk 12 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: Fixed

**Comment by krmahadevan** [comment]
@juherr - I have fixed all the review comments. Please help take a look

File: src/main/java/org/testng/internal/TestResult.java (hunk 8 above)
Comment (juherr) [reply src/main/java/org/testng/internal/TestResult.java]: Ok, right!

File: src/main/java/org/testng/internal/TestResult.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (juherr) [reply src/main/java/org/testng/internal/TestResult.java]: My problem is that we are doing a functional assumption and we may miss something in case of we have wrong.
The behavior may change and the assumption too?
It will be more difficult to find the issue later.

Instead, iterating on all is not wrong (maybe it is?), reduce the code and the complexity.

File: src/main/java/org/testng/internal/TestResult.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (juherr) [reply src/main/java/org/testng/internal/TestResult.java]: Could you add a TODO or open an issue for that?

[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: I have raised an issue for this https://github.com/cbeust/testng/issues/1893

File: src/main/java/org/testng/internal/TestResult.java [hunk 20]
```diff
@@ -320,4 +336,89 @@ public boolean wasRetried() {
...
+        //method. So lets add everything.
+        skippedDueTo.add(skippedConfig.getMethod());
+      }
+    }
+    if (!skippedDueTo.isEmpty()) {
+      //If we found atleast one skipped due to reason, then its time to return back.
+      return Collections.unmodifiableList(skippedDueTo);
+    }
+    //Looks like we didnt have any configuration failures. So some upstream method perhaps failed.
+    List<String> upstreamMethods = Arrays.asList(m_method.getMethodsDependedUpon());
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: For perf reason, maybe we can postpone the array to list transformation (here and on the line 368)

File: src/main/java/org/testng/internal/TestResult.java [hunk 21]
```diff
@@ -320,4 +336,89 @@ public boolean wasRetried() {
...
+        .collect(Collectors.toList());
+    return Collections.unmodifiableList(skippedDueTo);
+  }
+
+  private static boolean isGlobalFailure(ITestResult result) {
+    ITestNGMethod m = result.getMethod();
+    return m.isBeforeTestConfiguration() || m.isBeforeSuiteConfiguration();
+  }
+
+  private boolean isRelated(ITestResult result) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: I think the signature should be `private static boolean isRelated(ITestResult result, Object instance)` because another option could be `boolean ITestResult#isRelated(Object instance)`

File: src/main/java/org/testng/internal/TestResult.java [hunk 22]
```diff
@@ -320,4 +336,89 @@ public boolean wasRetried() {
...
+    if (!m.isBeforeClassConfiguration() && !m.isBeforeMethodConfiguration()) {
+      return false;
+    }
+    Object current = this.getInstance();
+    Object thatObject = result.getInstance();
+    return current.getClass().isAssignableFrom(thatObject.getClass()) ||
+        thatObject.getClass().isAssignableFrom(current.getClass());
+  }
+
+  private boolean belongToSameGroup(ITestResult result) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestResult.java]: Same here with `private static boolean belongToSameGroup(ITestResult result, String[] groups)`

**Review by juherr — APPROVED** [review]
Can be merged with or without last remarks

File: src/main/java/org/testng/internal/TestResult.java (hunk 21 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: I am not quite sure I understand this. Here `isRelated()` is basically comparing just two `ITestResult` objects. That is why its an instance method. If it were to be static, then I would need to basically have it take in two `ITestResult` objects.

File: src/main/java/org/testng/internal/TestResult.java (hunk 22 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: Same case here as well. Here we are basically checking if two `ITestResult` objects belong to the same set of groups. That is why its an instance method.

File: src/main/java/org/testng/internal/TestResult.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: @juherr - Ok. That makes sense. Fixed

File: src/main/java/org/testng/internal/TestResult.java (hunk 20 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestResult.java]: Fixed.

**Comment by krmahadevan** [comment]
Based on an email from @cbeust - merging this PR since @juherr has helped approved it.

File: src/main/java/org/testng/internal/TestResult.java (hunk 21 above)
Comment (juherr) [reply src/main/java/org/testng/internal/TestResult.java]: Ok
