### PR TITLE
Fixing a failing test within DataProviderTest

### LINKED ISSUE #1170: DataProviderTest.shouldNotThrowConcurrentModificationException is failing
From [Jetbrains Teamcity](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TestNG_BuildTestsWithGradle&branch_TestNG=<default>&tab=buildTypeStatusDiv)

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes # .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

Fixes #1170

Also fixed some javadoc warnings.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - Can you please help get this merged ?

The motivation behind moving away from `Collections.unmodifiableList()` was basically this SO thread : http://stackoverflow.com/a/13232837

File: src/test/java/test/InvokedMethodNameListener.java [hunk 1]
```diff
@@ -141,7 +141,7 @@ private static String getName(ITestResult result) {
   }
 
   public List<String> getSucceedMethodNames() {
-    return Collections.unmodifiableList(succeedMethodNames);
+    return new ArrayList<>(succeedMethodNames);
```
Comment (cbeust) [inline src/test/java/test/InvokedMethodNameListener.java]: Nice catch, looks good to me.

Comment (cbeust) [inline src/test/java/test/InvokedMethodNameListener.java]: Come to think of it, it would be nice to still return an unmodifiable list that copies the original one (unlike `unmodifiableList`, which merely wraps it). Not sure this exists, though.

**Comment by juherr** [comment]
Thanks @krmahadevan ! :+1:

File: src/test/java/test/InvokedMethodNameListener.java (hunk 1 above)
Comment (juherr) [inline src/test/java/test/InvokedMethodNameListener.java]: What's about `Collections.unmodifiableList(new ArrayList<>(succeedMethodNames))` then?

Comment (cbeust) [inline src/test/java/test/InvokedMethodNameListener.java]: Doh, of course, that would work.
