### PR TITLE
[Flaky test fix] - Issue 2579

### LINKED ISSUE #2579: Flaky test: test.thread.issue188.IssueTest.testSuiteLevelParallelMode
See https://travis-ci.org/github/cbeust/testng/jobs/773395339#L746

```
> Task :testng-core:test
FAILURE   4.8sec, test.thread.issue188.IssueTest > testSuiteLevelParallelMode
    java.lang.AssertionError: Test methods should have started within a lag of max 40 ms but it was 43 ms [1622731448687,1622731448730,1622731448732,1622731448733]
        at test.thread.issue188.IssueTest.testSuiteLevelParallelMode(IssueTest.java:50)
FAILURE   4.8sec,    1 completed,   1 failed,   0 skipped, test.thread.issue188.IssueTest
FAILURE   4.8sec,    1 completed,   1 failed,   0 skipped, 188_test
FAILURE   4.8sec,    1 completed,   1 failed,   0 skipped, 188_suite
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2579

What the new test measures

Instead of checking an arbitrary timestamp gap, each test method records when it is actively executing.

```
time ---->

active count
6 |                 ***************
5 |              ***               ***
4 |           ***                     ***
3 |        ***                           ***
2 |     ***                               ***
1 |  ***                                   ***
0 +------------------------------------------------
  m1  m2  m3  m4  m5  m6 start running
```

New assertion:
startedTestMethods == 6
maxActiveTestMethods == 6

Meaning:
all 6 methods started, and at one point all 6 were observed executing concurrently.

Behavioral difference

Old:
"Did every method start within 40 ms of the previous one?"

New:
"Did all six methods actually run at the same time?"

The new check matches the feature under test: suite-level parallel="methods" should execute methods concurrently. It removes the host-specific 40 ms timing assumption while still failing if execution becomes sequential.

Fixes # .

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`
- [ ] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

## Summary by CodeRabbit

* **Tests**
  * Replaced fragile timestamp-based tracking with reliable concurrency counters to measure parallel test execution.
  * Improved test setup/reset and made metrics collection deterministic for parallel runs.
  * Simplified assertions to directly validate expected counts of started and concurrently active test methods, strengthening parallel-execution verification.

### CODE REVIEW

File: testng-core/src/test/java/test/thread/issue188/Issue188TestSample.java [hunk 1]
```diff
@@ -1,44 +1,54 @@
...
   }
 
   @Test
   public void anotherSampleTest() {
-    sleepSilently();
+    trackParallelExecution();
   }
 
-  private void sleepSilently() {
+  private static void trackParallelExecution() {
```
Comment (juherr) [inline testng-core/src/test/java/test/thread/issue188/Issue188TestSample.java:43]: Is it thread safe?

File: testng-core/src/test/java/test/thread/issue188/IssueTest.java [hunk 2]
```diff
@@ -28,35 +25,12 @@ public void testSuiteLevelParallelMode() {
...
-                      + " ms but it was "
-                      + diff
-                      + " ms ["
-                      + allTimeStamps
-                      + "]")
-              .isLessThanOrEqualTo(permissibleLag);
-          prev = current;
-        }
-      }
+      Assertions.assertThat(Issue188TestSample.getStartedTestMethods())
```
Comment (juherr) [inline testng-core/src/test/java/test/thread/issue188/IssueTest.java]: Import static assertThat

File: testng-core/src/test/java/test/thread/issue188/Issue188TestSample.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/test/java/test/thread/issue188/Issue188TestSample.java:43]: We are trying to ascertain that at some point all the concurrently spawned test methods did overlap each other since its never going to be possible to truly ascertain if TestNG did start all the tests in parallel. Timestamped based guess work is also still only guestimate because we would need to define a tolerance value. And that tolerance value is what has been causing flakiness in CI.

File: testng-core/src/test/java/test/thread/issue188/IssueTest.java (hunk 2 above)
Comment (krmahadevan) [reply testng-core/src/test/java/test/thread/issue188/IssueTest.java]: Fixed

**Review by juherr — APPROVED** [review]

**Review by juherr — CHANGES_REQUESTED** [review]
All tests are failing

**Comment by krmahadevan** [comment]
@juherr - That was due to formatting problems. Now its fixed.

**Review by juherr — APPROVED** [review]
