### PR TITLE
Streamline command line argument passing for TestNG

### LINKED ISSUE #341: testng does not respect "-parallel classes" when running with a jar file
## I have 2 test classes in my package and build into a jar, there is no testng.xml in the jar

```
public class T1 {
@Test public void test() throws InterruptedException {
    for (int i=0; i<3; i++) {
        System.out.println(this.getClass().getName());
        Thread.sleep(1000);}}}


public class T2 {
@Test public void test() throws InterruptedException {
    for (int i=0; i<3; i++) {
        System.out.println(this.getClass().getName());
        Thread.sleep(1000);}}}
```

After that I ran with -testclass & -parallel classes, it will run in parallel:

```
$ java -cp jcommander-1.27.jar:testng-6.8.jar:target/ohmy-0.0.1-SNAPSHOT.jar org.testng.TestNG -parallel classes -testclass frank.ohmy.T1,frank.ohmy.T2
```

---

```
[TestNG] Running:
  Command line suite

frank.ohmy.T1
frank.ohmy.T2
frank.ohmy.T1
frank.ohmy.T2
frank.ohmy.T1
frank.ohmy.T2

===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================
```
## But if I run with -testjar & -parallel classes, it will _NOT_ run in parallel:

```
$ java -cp jcommander-1.27.jar:testng-6.8.jar:target/ohmy-0.0.1-SNAPSHOT.jar org.testng.TestNG -parallel classes -testjar target/ohmy-0.0.1-SNAPSHOT.jar
[TestNG] Couldn't find the testng.xml in the jar file, running all the classes
frank.ohmy.T1
frank.ohmy.T1
frank.ohmy.T1
frank.ohmy.T2
frank.ohmy.T2
frank.ohmy.T2
```

Seems like a testng bug, I run on 6.8, also tried build from github version, still repro.

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #341

Fixed the discrepancy:
“testng does not respect "-parallel classes" when 
running with a jar file”

Fixes #341 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/JarFileUtils.java [hunk 1]
```diff
@@ -27,13 +27,20 @@
     private final String xmlPathInJar;
     private final List<String> testNames;
     private final List<XmlSuite> suites = Lists.newLinkedList();
+    private final XmlSuite.ParallelMode mode;
 
     JarFileUtils(IPostProcessor processor, String xmlPathInJar, List<String> testNames) {
+        this(processor, xmlPathInJar, testNames, null);
```
Comment (juherr) [inline src/main/java/org/testng/JarFileUtils.java]: Maybe `ParallelMode.NONE` instead of null as default value

File: src/main/java/org/testng/JarFileUtils.java [hunk 2]
```diff
@@ -44,7 +51,11 @@
             if (!foundTestngXml) {
                 Utils.log("TestNG", 1,
                         "Couldn't find the " + xmlPathInJar + " in the jar file, running all the classes");
-                suites.add(XmlSuiteUtils.newXmlSuiteUsing(classes));
+                XmlSuite suite = XmlSuiteUtils.newXmlSuiteUsing(classes);
+                if (this.mode != null) {
```
Comment (juherr) [inline src/main/java/org/testng/JarFileUtils.java]: If mode cannot be null, no need to check it ;)

**Review by juherr — APPROVED** [review]

File: src/main/java/org/testng/JarFileUtils.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/JarFileUtils.java]: Fixed

File: src/main/java/org/testng/JarFileUtils.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/JarFileUtils.java]: Fixed

**Comment by juherr** [comment]
Ping @cbeust
