### PR TITLE
Configure TestNG to fail when all tests are skipped

### LINKED ISSUE #217: exception in DataProvider doesn't fail test run
If my @DataProvider method throws an exception, the TestNG report correctly shows that exception. However, the exit status from TestNG execution is zero, indicating that all tests passed. If a DataProvider fails, the build should fail as well.

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #217

Currently TestNG doesn’t throw an exception which
build tools can leverage to fail a build, when all
the “@Test” methods get skipped and nothing was run.
TestNG returns the proper status, but sometimes 
build tools may not be reading that status and take
appropriate action.

Introduced a new configuration through this PR using
which a user can instruct TestNG itself to trigger
an exception when no tests were executed.

If one is using surefire plugin, then your surefire
plugin configuration would look like below:

```xml
<configuration>
  <properties>
    <property>
      <name>failwheneverythingskipped</name>
      <value>true</value>
    </property>
  </properties>
</configuration>
```

If you are using command line, then this feature
can be turned on by passing 
-failwheneverythingskipped=true

Fixes #217  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

### CODE REVIEW

File: src/main/java/org/testng/internal/ExitCodeListener.java [hunk 1]
```diff
@@ -63,4 +70,11 @@ public void onStart(ITestContext context) {}
 
   @Override
   public void onFinish(ITestContext context) {}
+
+  @Override
+  public void onExecutionFinish() {
+    if (failIfAllTestsSkipped && (getStatus().getExitCode() == ExitCode.SKIPPED)) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCodeListener.java]: Why not failing without success?

Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: I didn't quite get you @juherr . Can you please tell me what you are hinting at ?

Comment (juherr) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: I mean for all exit code != 0

Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: @juherr - I think only in the case of all skipped tests (due to a failure in the data provider) we don't bubble out any exceptions. In all other cases (failed tests, skipped tests due to configuration failures) we are good and the build is already getting failed (else we would have had people complain about this already)

All tests getting skipped due to a failure in the data provider is the exception flow that I am trying to address via this PR

Comment (juherr) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: ok

**Review by juherr — APPROVED** [review]
