### PR TITLE
fix(#2445): Fix for NPE when generating FailedReport with tests creat…

### LINKED ISSUE #2445: NPE in FailedReporter.java With Tests Created in Factory
### TestNG Version
7.3.0
(Note, this did not occur with 6.9.11, and began with the upgrade to the latest).
### Expected behavior
No NPE upon failure when using A Factory Class (with @Factory annotation) to define our xml Suite.

Sample testng.xml:
```
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="IntegrationTestSuite" verbose="1" parallel="methods" thread-count="15" configfailurepolicy="continue">

  <!--***** Set Parameters to be passed to methods *****-->
  <parameter name="baseUrl" value="http://localhost:8080/"/>


  <!--***** Define test Configuration below  *****-->
  <test name="service-at-local">
    <classes>
      <class name="org.acceptance.MyFactory"/>
    </classes>
  </test>
</suite>
```
MyFactory.java contains:
```
  @Factory
  public Object[] create() {
    List<Object> vResult = new ArrayList<>();

    vResult.add(new TestX());
    vResult.add(new TestY());

    return vResult.toArray();
  }
```

### Actual behavior

When the TestX() class has failures, the following NPE is produced.

```
[TestNG] Reporter [FailedReporter passed=0 failed=0 skipped=0] failed
java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:501)
	at java.util.HashMap.putAll(HashMap.java:785)
	at org.testng.xml.XmlClass.setParameters(XmlClass.java:233)
	at org.testng.reporters.FailedReporter.createXmlClasses(FailedReporter.java:199)
	at org.testng.reporters.FailedReporter.createXmlTest(FailedReporter.java:150)
	at org.testng.reporters.FailedReporter.generateXmlTest(FailedReporter.java:124)
	at org.testng.reporters.FailedReporter.generateFailureSuite(FailedReporter.java:64)
	at org.testng.reporters.FailedReporter.generateReport(FailedReporter.java:49)
	at org.testng.TestNG.generateReports(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1042)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

At this [line][0], xmlClass.getName() returns the individual TestX() and classParameters contains only the key of the MyFactory Class. Therefore classParameters.get(xmlClass.getName()) results in a null.

[0]: https://github.com/cbeust/testng/blob/7.3.0/src/main/java/org/testng/reporters/FailedReporter.java#L199

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### PR DESCRIPTION
**Pull request by arham-jain**
The recent update to separate out local parameters class wise causes an NPE in case of tests created in a factory as the actual class is fetched when getRealClass is called. To fix this have added a fallback to the old behaviour i.e., aggregating all of the parameters when setting XML class parameters when a specific classes' parameters are not found

Fixes #2445.

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Review by krmahadevan — CHANGES_REQUESTED** [review]
@arham-jain - Thanks for taking the time to submit a PR to fix this.
Can you please add a test for this in https://github.com/cbeust/testng/blob/master/src/test/java/test/reports/FailedReporterTest.java

**Comment by arham-jain** [comment]
Will add a test and notify @krmahadevan

**Comment by juherr** [comment]
For the test, please assert the resulting XML.

**Comment by arham-jain** [comment]
Have added the test, @krmahadevan @juherr could one of you please review?

**Comment by juherr** [comment]
Thanks for the test but in #2445 the `<parameter name="key" value="value"/>` is on `<suite>`, not `<test>`. Could you add another test with the parameter on a suite too?

Additionally, instead of asserting but code, could you just add the expected result file and compare it with the generated one?
If comparing raw files is not enough, you may add XmlUnit https://www.xmlunit.org/api/java/2.8.2/org/xmlunit/assertj/XmlAssert.html

**Comment by arham-jain** [comment]
Updating the same test to assert both the suite param and test param, and adding xmlunit for the assertion

**Comment by arham-jain** [comment]
Updated as per comments @juherr

File: src/test/java/test/reports/issue2445/Test2.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package test.reports.issue2445;
+
+import org.testng.annotations.Test;
+
+public class Test2 {
+  @Test
+  public void test2() {
+    System.out.println("Test2 test method");
```
Comment (juherr) [inline src/test/java/test/reports/issue2445/Test2.java:8]: Please remove syso

**Review by juherr — APPROVED** [review]
Just remove syso from the tests.

File: src/test/java/test/reports/issue2445/Test2.java (hunk 1 above)
Comment (arham-jain) [reply src/test/java/test/reports/issue2445/Test2.java]: Updated

**Comment by juherr** [comment]
@krmahadevan Feel free to merge if it is ok for you.

**Comment by arham-jain** [comment]
(Just for my understanding) wanted to know why you preferred an XML compare, even if it meant adding a new dependency @juherr. For readability?

**Review by krmahadevan — APPROVED** [review]

**Comment by juherr** [comment]
> (Just for my understanding) wanted to know why you preferred an XML compare, even if it meant adding a new dependency. For readability?

@arham-jain Yes, exactly. It was not clear to me what was the resulting file.
