### PR TITLE
TestNG Reporting - Identify retried tests

### LINKED ISSUE #1402: Feature: TestNG Reporting, how to quickly identify Retry-d Tests?
### Expected behavior
Hello: When a `@Test fails` and a `Retry` happens, is there a direct way in TestNG to distinguish between a Test that has been Retried and a test that has not been retried - such as through a NG context method or variable?

- Case 1: If a Test not been retried then the `1st test` is a test that has not been retried.
- Case 2: If a Test that has been retried 2 times then the `3rd test` is a test that has not been retried.

An option to do this: [http://www.seleniumeasy.com/testng-tutorials/retry-listener-failed-tests-count-update](http://www.seleniumeasy.com/testng-tutorials/retry-listener-failed-tests-count-update).

### Actual behavior
Currently, there is currently no easy way to determine a retried test. 
Reference: [http://stackoverflow.com/questions/43069150](http://stackoverflow.com/questions/43069150)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1402

Enriched the following to distinctly show retried
tests:
* xml reporter.
* console reporter
* text reporter
* mailable reporter
* html reporter.

Fixes #1402 .

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/SuiteRunnerWorker.java [hunk 1]
```diff
@@ -65,16 +68,19 @@ private void runSuite(SuiteRunnerMap suiteRunnerMap /* OUT */, XmlSuite xmlSuite
       SuiteResultCounts counts = new SuiteResultCounts();
       counts.calculateResultCounts(xmlSuite, suiteRunnerMap);
 
-      StringBuilder bufLog = new StringBuilder("\n===============================================\n")
-          .append(xmlSuite.getName());
-      bufLog.append("\nTotal tests run: ")
-          .append(counts.m_total).append(", Failures: ").append(counts.m_failed)
-          .append(", Skips: ").append(counts.m_skipped);
+      StringBuilder bufLog = new StringBuilder(LINE).append(xmlSuite.getName());
```
Comment (juherr) [inline src/main/java/org/testng/SuiteRunnerWorker.java]: You can remove the string builder here: there is no loop and the string concatenation will do the same things.

**Review by juherr — APPROVED** [review]
Ping @cbeust
