### PR TITLE
Issue with Priority with too low values

### LINKED ISSUE #2137: Issue with Priority with too low values
### TestNG Version
7.0.0

### Expected behavior
According to the [javadoc](https://testng.org/doc/documentation-main.html):
> priority | The priority for this test method. Lower priorities will be scheduled first. 

Hence and since priority is an integer, setting the priority of a test method as `Integer.MIN_VALUE`, should schedule said method before any other test.

### Actual behavior
With 3 or less priority levels setting the priority of a test method as `Integer.MIN_VALUE` causes this method to be executed as the last one.

testng_prio_1

With more levels the behavior varies as the priority values and method names change.

testng_prio_2
testng_prio_3
testng_prio_4

### Is the issue reproductible on runner?
- [x] Maven
- [x] IntelliJ

### Test case sample

```
public class PriorityTest {

    @Test(priority = Integer.MIN_VALUE)
    public void testSetup() {
        System.out.println("a");
    }

    @Test(priority = 2)
    public void testFail() {
        System.out.println("b");
    }

    @Test(priority = 4)
    public void testException() {
        System.out.println("c");
    }

    @Test(priority = 5)
    public void testTrue() {
        System.out.println("d");
    }

    @Test(priority = 999, alwaysRun = true)
    public void testTearDown() {
        System.out.println("e");
    }
}
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2137

Fixes #2137 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr

**Comment by krmahadevan** [comment]
@juherr - Can u pls help review this PR ?

File: src/test/java/test/priority/issue2137/IssueTest.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+
+import org.testng.annotations.Test;
+
+public class IssueTest {
+
+  @Test(priority = Integer.MIN_VALUE)
+  public void a() {
+  }
+
+  @Test(priority = 1)
```
Comment (juherr) [inline src/test/java/test/priority/issue2137/IssueTest.java]: You should try with more specific values like 0 and negative priorities

**Review by juherr — APPROVED** [review]

File: src/test/java/test/priority/issue2137/IssueTest.java (hunk 1 above)
Comment (krmahadevan) [reply src/test/java/test/priority/issue2137/IssueTest.java]: @juherr - Negative priorities already got covered when I used `Integer.MIN_VALUE`. I didn't use `0` because that would also cause the priorities to be side-lined (when two priorities are equal, TestNG looks for test name as the tie breaker)
