### PR TITLE
End-time for skipped configs should not be 0.

### LINKED ISSUE #2535: TestResult.getEndMillis() returns 0 for skipped configuration - after upgrading testng to 7.0 +
### Expected behavior
TestResult.getEndMillis() should return the endtime for skipped configuration.

### Actual behavior
TestResult.getEndMillis() returns 0 for skipped configuration.

### Is the issue reproductible on runner?

- [x] Maven

### Test case sample

```java 
package com.logmein.piranha.macdriver.systemtests;

import org.testng.Assert;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
public class CalculatorTest  {
    /**
     * This is a very basic test that launches Calculator on Mac and performs an addition operation
     * and verifies the result. 
     */
    @Test(description = "Simple calculator test.")
    public void calculatorUiTest() {

    }
    /**
     * Setup.
     */
    @BeforeClass
    public void setup() {
        // Fail this configuration
      
        Assert.assertTrue(false);       
    }
    @BeforeMethod
    public void setup1() {       
       //This configuration will be skipped.       
    }
}
```

While creating report the method TestResult.getEndMillis() returns 0 for method setup1

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2535

Fixes #2535 

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: testng-runner-api/src/main/java/org/testng/internal/TestResult.java [hunk 1]
```diff
@@ -219,6 +219,9 @@ public void setThrowable(Throwable throwable) {
   /** @return Returns the endMillis. */
   @Override
   public long getEndMillis() {
+    if (m_status == SKIP) {
```
Comment (juherr) [inline testng-runner-api/src/main/java/org/testng/internal/TestResult.java:222]: It's a workaround which fixes the issue but not a fix.
Instead, you need to check where `m_endMillis` is set and fix the business logic there.

**Review by juherr — CHANGES_REQUESTED** [review]

File: testng-runner-api/src/main/java/org/testng/internal/TestResult.java (hunk 1 above)
Comment (krmahadevan) [reply testng-runner-api/src/main/java/org/testng/internal/TestResult.java]: @juherr Thanks for pointing that out... Fixed it. Please check once again.

**Review by juherr — APPROVED** [review]
