### PR TITLE
Issue #128

### LINKED ISSUE #128: Using Object[] and Method as parameters for a test in a certain order yields an IllegalArgumentException, citing a type mismatch.
BUILD: Eclipse plugin 6.3.0.20111017_2337

DESCRIPTION:
Two data providers that provide two parameters are defined. The first data provider provides a java.lang.reflect.Method as the first parameter and an Object array as the second. The second data provider reverses the order of the parameters.

One empty test is defined to use the first data provider. Another empty test is defined to use the second data provider.

Run this test.

The data providers and tests are defined below:

```
@DataProvider(name = "methods")
public Object[][] getMethods() throws NoSuchMethodException
{
    return new Object[][]{
            new Object[]{String.class.getMethod("toString"), new Object[0]},
    };
}

@Test(dataProvider = "methods")
public void testInvokeRemote(Method param1, Object[] param2) throws Exception
{
    // This fails with: java.lang.IllegalArgumentException: argument type mismatch
}

@DataProvider(name = "methods2")
public Object[][] getMethods2() throws NoSuchMethodException
{
    return new Object[][]{
            new Object[]{new Object[0], String.class.getMethod("toString")},
    };
}

@Test(dataProvider = "methods2")
public void testInvokeRemoteReversed(Object[] param1, Method param2) throws Exception
{
    // This works.
}
```

EXPECTED RESPONSE:
The order of parameters that a test method accepts are irrelevant to the results of that test.

OBSERVED RESPONSE:
The first test (with parameter types Method, Object[]) fails with an IllegalArgumentException, citing a type mismatch.

The second test (with the same parameter types in reverse order) passes without incident.

REPRO RATE: 10/10

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #128  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr

File: src/main/java/org/testng/internal/reflect/ReflectionRecipes.java [hunk 1]
```diff
@@ -331,51 +331,60 @@ public static boolean lenientMatch(final Class<?>[] classes, final Object[] args
...
-      final Object[] injectedArray = new Object[arguments.size()];
-      return arguments.toArray(injectedArray);
-    } else {
-      return args;
+
+      if (!inject) {
+        arguments.add(queue.poll());
+      }
     }
+    if (!queue.backingList.isEmpty()) { // TODO Remove duplication from Paramters#getInjectedParameter
```
Comment (juherr) [inline src/main/java/org/testng/internal/reflect/ReflectionRecipes.java]: Did you find a way to remove the logic from `Parameters#getInjectedParameter`?

File: src/test/java/test/dataprovider/issue128/DataProviderParametersMismatchTest.java [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+            tng.run();
+            String msg = new String(out.toByteArray(), StandardCharsets.UTF_8);
+            boolean contains = msg.contains("Missing one or more parameters that are being injected by the data provider. Please add the below arguments to the method.");
+            Assert.assertTrue(contains, "Missing parameters warning should have triggered");
+        } finally {
+            System.setErr(currentErr);
+            System.setProperty("strictParameterMatch", "false");
+        }
+    }
+    @Test(dependsOnMethods = "testIfWarningsAreServed")
```
Comment (juherr) [inline src/test/java/test/dataprovider/issue128/DataProviderParametersMismatchTest.java]: A blank line is missing

**Review by juherr — COMMENTED** [review]
Check the warn from the suite. I looks there too much warn (not only missing params) and it was the problem I wasn't able to fix.

File: src/main/java/org/testng/internal/reflect/ReflectionRecipes.java (hunk 1 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/reflect/ReflectionRecipes.java]: @juherr - No I haven't yet thought about it. I thought it would be better if we have it as a separate PR rather than club those changes in here.

**Comment by krmahadevan** [comment]
@juherr 

> Check the warn from the suite. I looks there too much warn (not only missing params) and it was the problem I wasn't able to fix.

I didnt quite understand on the warning part. Can you please clarify ?

W.r.t the problem, are you talking about handling parameter injections wherein there's a native injection involved and a data provider also tries passing in the same parameter, but the test method which receives the parameter values has only one place holder ?
I think that is essentially not a problem with TestNG, but more of a user's problem. The user should either be taking care of adding an extra parameter to take care of the native injection as well or they would have to disable native injection using `@NoInjection`

**Comment by juherr** [comment]
@krmahadevan From Travis:

>    :::WARNING:::
>    Missing one or more parameters that are being injected by the data provider. Please add the below arguments to the method.
>    Method: xmlFileShouldBeRunAtItsPlaceAndNotCopied([Parameter{index=0, type=org.testng.ITestContext, declaredAnnotations=[]}])
>    Arguments: [(org.testng.TestRunner) org.testng.TestRunner@37fbf51c]

But the test method doesn't have any data provider and `TestRunner` is the expected `ITestContext`.
https://github.com/cbeust/testng/blob/5fa5ed7f9fb8428fbc2412321f95f73164222af7/src/test/java/test/EclipseTest.java#L16

**Comment by krmahadevan** [comment]
@juherr - I have pushed in a change.

I looked at the travis log now and I found only one occurrence of my warning 

```
TestNG > Injection STANDARD_ERROR
    :::WARNING:::
    Missing one or more parameters that are being injected by the data provider. Please add the below arguments to the method.
    Method: withInjection([Parameter{index=0, type=java.lang.reflect.Method, declaredAnnotations=[]}])
    Arguments: [(java.lang.reflect.Method) public void test.inject.CC.f()]
```

File: src/main/java/org/testng/internal/reflect/ReflectionRecipes.java (hunk 1 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/reflect/ReflectionRecipes.java]: @juherr - I have tried doing this by adding a check to see if its a `@Test` method and if yes, we resort to skipping native injection via `Parameters#getInjectedParameter`

File: src/test/java/test/dataprovider/issue128/DataProviderParametersMismatchTest.java (hunk 2 above)
Comment (krmahadevan) [inline src/test/java/test/dataprovider/issue128/DataProviderParametersMismatchTest.java]: fixed this.

**Comment by juherr** [comment]
Ok, great! This one is expected 👍 

Could you check if it is possible to remove `Paramters#getInjectedParameter`? You will be faced with issues with injection in configuration methods but maybe we can merge the logic in only one place. :crossed_fingers:

**Comment by krmahadevan** [comment]
@juherr 

> Could you check if it is possible to remove `Parameters#getInjectedParameter?`

This is now taken care of. I have added an additional commit that takes care of this.

File: src/main/java/org/testng/internal/Parameters.java [hunk 3]
```diff
@@ -164,6 +168,10 @@ private static String retrieveConfigAnnotation(Method m) {
 
   ////////////////////////////////////////////////////////
 
+  /**
+   * @deprecated - This method stands deprecated as of TestNG v6.11. There are no alternatives.
+   */
+  @Deprecated
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: It is located in the `internal` package. Maybe we can remove it.

File: src/main/java/org/testng/internal/Parameters.java [hunk 4]
```diff
@@ -182,62 +190,107 @@ else if (ITestResult.class.equals(c)) {
     return result;
   }
 
+  private static Object[] createParametersForConstructor(Constructor constructor,
+                                                         Class[] parameterTypes,
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: `Class<?>[]`

File: src/main/java/org/testng/internal/Parameters.java [hunk 5]
```diff
@@ -182,62 +190,107 @@ else if (ITestResult.class.equals(c)) {
...
+                                                         String[] optionalValues,
+                                                         String methodAnnotation,
+                                                         String[] parameterNames, MethodParameters params, XmlSuite xmlSuite) {
+    Object[] result = new Object[0];
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: Could be declared into the if statement.

File: src/main/java/org/testng/internal/Parameters.java [hunk 6]
```diff
@@ -182,62 +190,107 @@ else if (ITestResult.class.equals(c)) {
...
+    if (parameterTypes.length == 0) {
+      return result;
+    }
+    List<Object> vResult = Lists.newArrayList();
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: could be declared after the check param

File: src/main/java/org/testng/internal/Parameters.java [hunk 7]
```diff
@@ -182,62 +190,107 @@ else if (ITestResult.class.equals(c)) {
...
+
+    checkParameterTypes(constructor.getName(), parameterTypes, methodAnnotation, parameterNames);
+    Parameter[] paramsArray = ReflectionRecipes.getConstructorParameters(constructor);
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: could be declared into the if statement.

File: src/main/java/org/testng/internal/Parameters.java [hunk 8]
```diff
@@ -182,62 +190,107 @@ else if (ITestResult.class.equals(c)) {
     return result;
   }
 
+  private static Object[] createParametersForConstructor(Constructor constructor,
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: could we use a list instead of an array?

File: src/main/java/org/testng/internal/Parameters.java [hunk 9]
```diff
@@ -182,62 +190,107 @@ else if (ITestResult.class.equals(c)) {
...
+            parameterTypes, optionalValues, parameterNames, params, xmlSuite);
+    vResult.addAll(consParams);
+
+    return vResult.toArray(new Object[vResult.size()]);
+  }
+
+  private static List<Object> createParams(String name,
+                                       String prefix,
+                                       String methodAnnotation,
+                                       Class[] parameterTypes,
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: `Class<?>[]`

File: src/test/java/test/dataprovider/issue128/GitHub128Sample.java [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+    Assert.fail("The test is supposed to fail because the method param is not defined");
+  }
+
+  @Test(dataProvider = "methods2")
+  public void testInvokeRemoteReversed2(Object[] param1, @NoInjection Method param2) {
+    Assert.assertEquals(param1.length, 0);
+    Assert.assertEquals(param2.getName(), "toString");
+  }
+
+  // TODO Add similar test for Before/AfterMethod
```
Comment (juherr) [inline src/test/java/test/dataprovider/issue128/GitHub128Sample.java]: Could be removed now

File: CHANGES.txt [hunk 11]
```diff
@@ -17,6 +17,7 @@ Fixed: GITHUB-1144: Add Class and Constructor as legal native dependency injecti
 Fixed: GITHUB-1380: Circular dependencies may fail in parallel (Julien Herr)
 Fixed: GITHUB-1400: TestNG, Multiple duplicate listener warnings on implementing multiple listener interfaces (@bipo1980 & Nick Tan)
 Fixed: GITHUB-1426: @AfterMethod(alwaysRun = true) is not getting called if we have exception in @BeforeMethod (@dipak-pawar)
+Fixed: GITHUB-128: Using Object[] and Method as parameters for a test in a certain order yields an IllegalArgumentException, citing a type mismatch (@leef590 & Julien Herr,Krishnan Mahadevan)
```
Comment (juherr) [inline CHANGES.txt]: You can remove my name, you did all the difficult job ;)

**Review by juherr — APPROVED** [review]
It is bigger than expected but I'm happy to see it working! Good job 👍 
Ping @cbeust

File: src/main/java/org/testng/internal/Parameters.java (hunk 8 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: That would cause the translation from `Array` to `List` to be done in `org.testng.internal.Parameters#createInstantiationParameters`. So I thought its best to have this just as an array.

File: src/main/java/org/testng/internal/Parameters.java (hunk 4 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: Fixed.

File: src/main/java/org/testng/internal/Parameters.java (hunk 5 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: Fixed.

File: src/main/java/org/testng/internal/Parameters.java (hunk 6 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: fixed.

File: src/main/java/org/testng/internal/Parameters.java (hunk 7 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: fixed.

File: src/main/java/org/testng/internal/Parameters.java (hunk 9 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: fixed.

File: src/test/java/test/dataprovider/issue128/GitHub128Sample.java (hunk 10 above)
Comment (krmahadevan) [inline src/test/java/test/dataprovider/issue128/GitHub128Sample.java]: Removed.

File: CHANGES.txt (hunk 11 above)
Comment (krmahadevan) [inline CHANGES.txt]: That's fine @juherr. You started the work for this. So it makes sense to rightfully leave your name there.

**Comment by krmahadevan** [comment]
@juherr - I have fixed all the additional review comments you shared.

@cbeust - Please help with the merge, whenever you have some time to spare.

File: CHANGES.txt (hunk 11 above)
Comment (juherr) [inline CHANGES.txt]: ok :)

File: src/main/java/org/testng/internal/Parameters.java (hunk 8 above)
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: ok

**Comment by krmahadevan** [comment]
ping @cbeust ( This PR is already reviewed and approved by @juherr )
