### PR TITLE
Include all data driven tests for reporting skips

### LINKED ISSUE #2674: Run onTestSkipped for each value from data provider
### Expected behavior

Expected test case output:

```
Skipped test2(foo)
Skipped test2(bar)
```

### Actual behavior

Actual test case output:

```
Skipped test2()
```

### Is the issue reproducible on runner?
- Gradle
- IntelliJ

### Test case sample

```java
@Listeners(Example.MyListener.class)
public class Example {
    @Test
    void test1() { Assert.fail(); }

    @Test(dataProvider = "items", dependsOnMethods = {"test1"})
    void test2(String value) { }

    @DataProvider(name = "items")
    Object[][] items() { return new Object[][]{{"foo"}, {"bar"}}; }

    public static class MyListener implements IResultListener2 {
        @Override
        public void onTestSkipped(ITestResult result) { handle(result); }

        private void handle(ITestResult result) {
            Object param = result.getParameters().length != 0 ? result.getParameters()[0] : "";
            System.out.printf("Skipped %s(%s)\n", result.getName(), param);
        }
    }
}
```

I need `handle` method to be called for each value from data provider. 
If I cannot configure it that way, I am ok to cover it in `onTestSkipped` but I would like to know what would be the easiest method to invoke data provider in a generic way (without a direct call to `items` method).

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2674

We now have a new configuration parameter named
“-includeAllDataDrivenTestsWhenSkipping” which 
when used would cause a data driven test to report
All its iterations as skipped when there is a failure
in its upstream dependencies.

Fixes #2674  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 1]
```diff
@@ -1403,7 +1412,12 @@ public static TestNG privateMain(String[] argv, ITestListener listener) {
    *
    * @param cla The command line parameters
    */
-  protected void configure(CommandLineArgs cla) {
+  public void configure(CommandLineArgs cla) {
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:1415]: It is protected because it is not supposed to be used by users.
In fact, the CLI runner should call the appropriate methods on `TestNG` and `TestNG` should not have any dependency to CLI runner.

File: testng-core/src/main/java/org/testng/TestNG.java [hunk 2]
```diff
@@ -1403,7 +1412,12 @@ public static TestNG privateMain(String[] argv, ITestListener listener) {
...
+    boolean skipTestFlag =
+        Optional.ofNullable(cla.includeAllDataDrivenTestsWhenSkipping).orElse(false);
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/TestNG.java:1417]: Logic duplication: you already set the default value on `CommandLineArgs`. Maybe it should be a `boolean` in `CommandLineArgs` or null by default there.

Comment (juherr) [reply testng-core/src/main/java/org/testng/TestNG.java:1417]: In fact, why not follow the current pattern with null check?

File: testng-core/src/main/java/org/testng/internal/Configuration.java [hunk 3]
```diff
@@ -33,6 +33,8 @@
   private IInjectorFactory injectorFactory = new GuiceBackedInjectorFactory();
   private boolean overrideIncludedMethods = false;
 
+  private boolean includeAllDataDrivenTestsWhenSkipping = false;
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/internal/Configuration.java:36]: 3rd place with the default value

File: testng-core/src/main/java/org/testng/internal/IConfiguration.java [hunk 4]
```diff
@@ -49,4 +49,10 @@ default boolean addExecutionListenerIfAbsent(IExecutionListener l) {
   boolean getOverrideIncludedMethods();
 
   void setOverrideIncludedMethods(boolean overrideIncludedMethods);
+
+  default void setReportAllDataDrivenTestsAsSkipped(boolean reportAllDataDrivenTestsAsSkipped) {}
+
+  default boolean getReportAllDataDrivenTestsAsSkipped() {
+    return false;
```
Comment (juherr) [inline testng-core/src/main/java/org/testng/internal/IConfiguration.java:56]: 4th place with the default value

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: The javadocs on the method that accepts a Map says its deprecated and favours this method. With it being protected i wouldn't be able to test it out. Are you suggesting that i create a subclass of TestNG for testing purposes wherein i make it public ?

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 2 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java:1417]: I will revisit the false part and check. I added the additional guards because tests were throwing a NullPointerException if we do a null check. 

On a side note do you see any problem with us using 'Optional.ofNullable()'?

File: testng-core/src/main/java/org/testng/internal/IConfiguration.java (hunk 4 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/internal/IConfiguration.java:56]: This is an interface with a default implementation. There's no way to circumvent this part without making the method as `non default`. So I guess we should be fine with this one.

**Comment by krmahadevan** [comment]
@juherr - Fixed all the review comments. Please check.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: This method is currently what is being proposed as an alternative to surefire plugin invocation (it currently calls a method that accepts a `Map`). So am guessing that this method has to be public else surefire plugin wouldn't be able to invoke it (Unless and until they are subclassing TestNG and then invoking this. Are they ? )

Comment (juherr) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: Right, good catch. Time passed.
Now, I think we should have a dedicated interface if we want to open the method to `public`.

```java
public void configure(Configuration configuration) { ... }
class CommandLineArgs implements Configuration { ... }
```

Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: I dont think that would work.. I mean `implements Configuration` part because I dont know if the configuration captures everything that TestNG needs. Setting up TestNG via configurations is right now spread all over the place. In some places, TestNG sets it directly and in some cases it  delegates to the Configuration object. I think this would be an exercise by itself.

So in the meantime, do you think that I should just subclass TestNG for the tests wherein I set this configuration and complete this PR ?

Comment (juherr) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: Or maybe having a `TestNGConfigurator`:

```java
interface TestNGConfigurator {
  void configure(TestNG tng);
}
```

File: testng-core/src/main/java/org/testng/internal/IConfiguration.java (hunk 4 above)
Comment (juherr) [reply testng-core/src/main/java/org/testng/internal/IConfiguration.java:56]: You can use a constant for the default value.

Or you can use a classical interface.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: I didnt understand on 
* Who would implement this ?
* How would this be consumed ?
* Is this meant for tests only ?

**Review by juherr — APPROVED** [review]
LGTM, just track the planned refactore in an issue.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (juherr) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: > So in the meantime, do you think that I should just subclass TestNG for the tests wherein I set this configuration and complete this PR ?

It looks better in short term.

> I didnt understand on
>
> Who would implement this ?
> How would this be consumed ?
> Is this meant for tests only ?

It is a global thinking. I see a bad dependency between CLI runner and core module, and try to find a way to move the dependency from `core -> cli` to `cli -> core`.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 2 above)
Comment (juherr) [reply testng-core/src/main/java/org/testng/TestNG.java]: > On a side note do you see any problem with us using 'Optional.ofNullable()'?

I think `Optional` is good for API design. I don't know yet if it is a good or bad idea to use it for internal.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: Ok.. then I will for now refactor the PR to sub class TestNG and be done with this PR.

**Comment by juherr** [comment]
⚠️ Tests are failing

**Comment by krmahadevan** [comment]
The test failures are because of auto style violations.. Sigh! I thought I did that before pushing code... Anyways.. will go home and take a look at it and fix it along with sub classing part and proceed with merging this.

File: testng-core/src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (juherr) [reply testng-core/src/main/java/org/testng/TestNG.java:1415]: Thanks. If it takes too much effort, check if another compromise is possible without opening the method.

Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/TestNG.java]: sub-classed TestNG and reverted back the public method to its `protected` state.

**Comment by krmahadevan** [comment]
Fixed the test failures due to code formatting. Merging this PR.
