### PR TITLE
Parallel test run is not working in 6.13.1

### LINKED ISSUE #1636: Parallel test run is not working in 6.13.1
### Example test class
```java
public class ThreadCountTest {

    @Test
    public void test1(){
        System.out.println(Thread.currentThread().getId());
    }

    @Test
    public void test2(){
        System.out.println(Thread.currentThread().getId());
    }

    @Test
    public void test3(){
        System.out.println(Thread.currentThread().getId());
    }
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Thread count" parallel="methods" thread-count="3">
    <test name="Test">
        <classes>
            <class name="onetech.ThreadCountTest"/>
        </classes>
    </test>
</suite>
```

### TestNG - 6.11 output
```
13
14
15
```
(Each test is launched in a separate thread which is indicated by unique thread id)

### TestNG - 6.13.1 output
```
1
1
1
```
 (Every test is launched in the same thread)

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
See above

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1636

Fixes #1636 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/TestNG.java [hunk 1]
```diff
@@ -290,8 +290,12 @@ private void parseSuite(String suitePath) {
       Collection<XmlSuite> allSuites = Parser.parse(suitePath, getProcessor());
 
       for (XmlSuite s : allSuites) {
-        s.setParallel(this.m_parallelMode);
-        s.setThreadCount(this.m_threadCount);
+        if (this.m_parallelMode != null) {
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: `m_parallelMode` and `m_threadCount` are supposed to be valid values (default values if not set).
I'd prefer we sanitize the values when they are set. Do you think it is possible?

File: src/test/java/test/thread/Github1636Sample.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+import org.testng.annotations.Test;
+
+import java.util.Collections;
+import java.util.Map;
+import java.util.Set;
+import java.util.concurrent.ConcurrentHashMap;
+
+public class Github1636Sample {
+    private static Map<Long, Boolean> map = new ConcurrentHashMap<>();
+    static Set<Long> threads = Collections.newSetFromMap(map);
```
Comment (juherr) [inline src/test/java/test/thread/Github1636Sample.java]: For my information, why do you create a set from a map? Concurrent reason?

Comment (krmahadevan) [reply src/test/java/test/thread/Github1636Sample.java]: @juherr - Yes. Java doesn't have a `ConcurrentHashSet`. The recommended way of doing it is by retrieving the keys from a  `Map`.

File: src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: There are two scenarios. 
1. When the configuration is set via the `TestNG` object (which am guessing is the CLI mode) 
2. When the configuration is set via the `XmlSuite` object (which am guessing is the xml mode)

The problem is that, when the user is on the xml mode, we end up overwriting values from the CLI mode. The easiest way of not doing it was to basically ensure that the CLI values dont override the xml values, when the CLI values aren't set. Sanitizing the values to some defaults would basically not help us in doing that, because we wouldn't know if it was the default values or if the user did set them explicitly to the default values. I chose the easier way of overriding values if they weren't set (`null` and `-1` respectively for `m_parallelMode` and `m_threadCount`)

Comment (juherr) [reply src/main/java/org/testng/TestNG.java]: Ok, it makes sense.

**Review by juherr — APPROVED** [review]

**Comment by cbeust** [comment]
LGTM. @krmahadevan Feel free to merge once you've resolved the conflicts.

**Review by cbeust — APPROVED** [review]

**Comment by krmahadevan** [comment]
Thanks @cbeust - I fixed the merge conflicts and merged this.
