### PR TITLE
Fix #435: Apply suite level packages to all tests

### LINKED ISSUE #435: <packages> does not work in <suite> level
In most case, we use `<packages>` in `<test>` level to define a set of packages to include or exclude from the test.

However, can we use `<packages>` in `<suite>` level to define packages for all tests in this suite?

Sample Code:

```java
public class GroupTest {

@Test(groups="method1")
public void testingMethod1() {  
  System.out.println("Method - testingMethod1()");
}  

@Test(groups="method2")
public void testingMethod2() {  
    System.out.println("Method - testingMethod2()");
}  

@Test(groups="method1")
public void testingMethod1_1() {  
    System.out.println("Method - testingMethod1_1()");
}  
}
```

The xml for test:
1) The usual xml which can test group method1 and method2.
xml1

2) The wanted xml which runs no group.
xml2

Now that `<package>` is supported in` <suite>` scope, what is the function of it?

### PR DESCRIPTION
**Pull request by siegi**
Fixes #435.

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

### Notes

This is my first pull request to TestNG, so I'm not sure everything is according to project standards.
In particular I don't know if `TestRunner` is the appropriate place to merge the suite and test packages.

Please tell me if anything should be adjusted…

### CODE REVIEW

File: src/main/java/org/testng/TestRunner.java [hunk 1]
```diff
@@ -295,6 +293,22 @@ private void init(
...
 
+  /**
+   * Returns all packages to use for the current test. This includes the test from the test
+   * suite. Never returns null.
+   */
+  private List<XmlPackage> getAllPackages()
+  {
+    final List<XmlPackage> allPackages = Lists.newArrayList();
+    final List<XmlPackage> suitePackages = this.m_xmlTest.getSuite().getPackages();
+    if (suitePackages != null)
```
Comment (krmahadevan) [inline src/main/java/org/testng/TestRunner.java]: The `null` check is not needed, because `org.testng.xml.XmlSuite#getPackages` returns an empty list always.

File: src/main/java/org/testng/TestRunner.java [hunk 2]
```diff
@@ -295,6 +293,22 @@ private void init(
     init();
   }
 
+  /**
+   * Returns all packages to use for the current test. This includes the test from the test
+   * suite. Never returns null.
+   */
+  private List<XmlPackage> getAllPackages()
```
Comment (krmahadevan) [inline src/main/java/org/testng/TestRunner.java]: Styling issue:

The codebase follows this styling 
`private List<XmlPackage> getAllPackages() {`

Also please include `{}` for all `if` conditions.

**Review by krmahadevan — COMMENTED** [review]
The changes look good apart from the very minor observations. Can you please help fix the same ?

File: src/main/java/org/testng/TestRunner.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestRunner.java]: Ok, then lets leave the `null` checks as is. But please help address the styling discrepancy.

**Comment by siegi** [comment]
@krmahadevan, I fixed the styling issues, thanks for reviewing!

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
ping @juherr - Please help take a look and provide your inputs.

**Review by juherr — APPROVED** [review]
