### PR TITLE
Fix for issue #1668

### LINKED ISSUE #1668: "Invalid Method Selector" exception triggered when using suite level beanshell methodselectors
6.13.1

### Expected behavior
No Exception should be raised

### Actual behavior

The below exception is raised

```java
Exception in thread "main" org.testng.TestNGException: 
Invalid Method Selector:  found neither class name nor language
	at org.testng.xml.XmlMethodSelector.toXml(XmlMethodSelector.java:111)
	at org.testng.xml.DefaultXmlWeaver.asXml(DefaultXmlWeaver.java:178)
	at org.testng.xml.XmlWeaver.asXml(XmlWeaver.java:67)
	at org.testng.xml.XmlTest.toXml(XmlTest.java:475)
	at org.testng.xml.DefaultXmlWeaver.asXml(DefaultXmlWeaver.java:139)
	at org.testng.xml.XmlWeaver.asXml(XmlWeaver.java:57)
	at org.testng.xml.XmlSuite.toXml(XmlSuite.java:518)
	at com.rationaleemotions.stackoverflow.qn48341304.SampleTestExample.main(SampleTestExample.java:19)
```

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

Sample test class

```java
import org.testng.annotations.Test;

public class TestClassOne {
    @Test
    public void testMethod() {
        System.err.println(getClass().getName() + ".testMethod() executed");
    }
}
```

Suite xml file looks like below

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="48341304_Suite" parallel="false" verbose="2">
    <method-selectors>
        <method-selector>
            <script language="beanshell">
                <![CDATA[
                whatTest = System.getProperty("testToRun");
                if (whatTest == null || whatTest.trim().isEmpty()) return true;
                whatTest.contains(testngMethod.getXmlTest().getName());
                ]]>
            </script>
        </method-selector>
    </method-selectors>
    <test name="48341304_Test1" verbose="2">
        <classes>
            <class name="com.rationaleemotions.stackoverflow.qn48341304.TestClassOne"/>
        </classes>
    </test>
    <test name="48341304_Test2" verbose="2">
        <classes>
            <class name="com.rationaleemotions.stackoverflow.qn48341304.TestClassTwo"/>
        </classes>
    </test>
</suite>
```

Main test class runner that triggers the error

```java
import org.testng.TestNG;
import org.testng.xml.Parser;
import org.testng.xml.XmlSuite;

import java.io.IOException;
import java.util.List;

public class SampleTestExample {
    public static void main(String[] args) throws IOException {
        Parser parser = new Parser("src/test/resources/48341304.xml");
        List<XmlSuite> suites = parser.parseToList();
        XmlSuite xmlsuite = suites.get(0);
        TestNG testNG = new TestNG();
        testNG.setXmlSuites(suites);
        testNG.setUseDefaultListeners(false);
        testNG.run();
        System.err.println(xmlsuite.toXml());
    }
}
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixing “Invalid Method Selector" exception triggered 
when using suite level beanshell methodselectors 

Closes #1668

Fixes #1668  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/test/java/org/testng/xml/XmlSuiteTest.java [hunk 1]
```diff
@@ -57,4 +58,16 @@ public void testTimeOut(String timeout, int size, int lineNumber) throws IOExcep
...
+    @Test(description = "GITHUB-1668")
+    public void ensureNoExceptionsAreRaisedWhenMethodSelectorsDefinedAtSuiteLevel() throws IOException {
+        Parser parser = new Parser("src/test/resources/xml/issue1668.xml");
+        List<XmlSuite> suites = parser.parseToList();
+        XmlSuite xmlsuite = suites.get(0);
+        TestNG testNG = create();
+        testNG.setXmlSuites(suites);
+        testNG.setUseDefaultListeners(false);
+        testNG.run();
+        assertThat(xmlsuite.toXml()).isNotEmpty();
```
Comment (juherr) [inline src/test/java/org/testng/xml/XmlSuiteTest.java]: The assertion is not really clear without a comment.
In fact, according to the issue, you just expect to not have an exception.

File: src/main/java/org/testng/TestNG.java [hunk 2]
```diff
@@ -533,7 +533,9 @@ public void setTestClasses(Class[] classes) {
   }
 
   public void addMethodSelector(String className, int priority) {
-    m_methodDescriptors.put(className, priority);
+    if (className != null && !className.trim().isEmpty()) {
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Is `trim` really useful?
Maybe a util method `boolean isEmpty(String s)` could be helpful (a method may already exist).

**Review by juherr — APPROVED** [review]

File: src/test/java/org/testng/xml/XmlSuiteTest.java (hunk 1 above)
Comment (krmahadevan) [reply src/test/java/org/testng/xml/XmlSuiteTest.java]: Instead of just having a statement which invokes `xmlsuite.toXml()` (only when invoking this method the exception is raised, I chose to have an assertion that checks if the string is not empty. 

Yes you are correct, that a comment could have added value. I will amend the commit, add a comment and push the changeset

File: src/main/java/org/testng/TestNG.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: Since this is a public method, I chose to include a `trim()` invocation as well. In terms of the utils method, I have refactored to use `org.testng.util.Strings#isNotNullAndNotEmpty`

**Comment by krmahadevan** [comment]
ping @cbeust . Can you please help with getting this merged ?
