### PR TITLE
Bugfix/GitHub 2195 npe using groups before aftermethod

### LINKED ISSUE #2195: NPE Using groups and @Before/@AfterMethod with alwaysRun and dependsOnMethods
### TestNG Version
6.14.3 - 7.0.1-SNAPSHOT

### Expected behavior

Rise a friendly message instead of NPE

### Actual behavior

Using groups if a Before or After annotated method from a parent class is using alwaysRun and depends on a method which is not in the group nor annotated with alwaysRun an NPE is risen

```
Exception in thread "main" java.lang.NullPointerException
        at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:116)
        at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:281)
        at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:381)
        at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:71)
        at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:200)
        at org.testng.internal.TestNGMethodFinder.getBeforeGroupsConfigurationMethods(TestNGMethodFinder.java:99)
        at org.testng.TestClass.initMethods(TestClass.java:159)
        at org.testng.TestClass.init(TestClass.java:75)
        at org.testng.TestClass.<init>(TestClass.java:39)
        at org.testng.TestRunner.initMethods(TestRunner.java:463)
        at org.testng.TestRunner.init(TestRunner.java:342)
        at org.testng.TestRunner.init(TestRunner.java:295)
        at org.testng.TestRunner.<init>(TestRunner.java:181)
        at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:618)
        at org.testng.SuiteRunner.init(SuiteRunner.java:196)
        at org.testng.SuiteRunner.<init>(SuiteRunner.java:127)
        at org.testng.TestNG.createSuiteRunner(TestNG.java:1265)
        at org.testng.TestNG.createSuiteRunners(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1093)
        at org.testng.TestNG.runSuites(TestNG.java:1032)
        at org.testng.TestNG.run(TestNG.java:1000)
        at org.testng.TestNG.privateMain(TestNG.java:1326)
        at org.testng.TestNG.main(TestNG.java:1294)

```

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample

```java
@Test(groups={"testgroup"})
class Test1 extends BaseClass {

    public Test1() {
    }
}

class BaseClass {
    @BeforeMethod
    public void before(){}
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "before")
    public void beforeAlways(){}

   @Test
   public void test()
   
    @AfterMethod
    public void after(){}
    @AfterMethod(alwaysRun = true, dependsOnMethods = "after")
    public void after(){}
}
```

Test suite xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite parallel="none" name="Custom suite">
    <test name="TestNPE" verbose="10">
        <groups>
            <run>
                <include name="testgroup"/>
            </run>
        </groups>
        <classes>
            <class name="TestClass"/>
        </classes>
    </test> <!-- TestNPE -->
</suite> <!-- Custom suite -->
````

### PR DESCRIPTION
**Pull request by iagotomas**
Closes #2195 

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@iagotomas - There are test failures and also issues with formatting for the newly added classes. So can we do the following ?

1. For `MethodHelper` class, revert all the changes, and just apply only your line (and not format)
2. For the newly added test classes, please apply the formatting by leveraging https://github.com/google/google-java-format

**Comment by iagotomas** [comment]
Hi @krmahadevan did as you proposed and finally managed to commit changes with proper CRLF line endings. I had git auto.crlf enabled as it's mandatory in my company and it was modifying all commits, it wasn't the IDE :(
Hope it's working now. I struggled a bit to run tests including mine. I was expecting to be able to easily run them from the IDE but as I understood the setup goes through xml/yaml resource files which I initially wasn't aware.

File: src/test/java/org/testng/internal/MethodHelperTest.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+            false,
+            true,
+            false,
+            new String[0],
+            new String[0],
+            testClass);
+    ITestNGMethod[] methods = new ITestNGMethod[0];
+    method.addMethodDependedUpon("dummyDependsOnMethod");
+    MethodHelper.findDependedUponMethods(method, methods);
+    fail("Should have risen a nice exception");
```
Comment (krmahadevan) [inline src/test/java/org/testng/internal/MethodHelperTest.java]: I dont think you need this because TestNG by design will fail a test method when its expected to throw an exception and when the test method doesn't.

**Review by krmahadevan — COMMENTED** [review]
Apart from that minor observation with `fail()` I dont have anything else to add. The changeset looks good. Once @juherr also gives a quick 👍  we will get this merged.

Thanks for the contribution @iagotomas

**Comment by krmahadevan** [comment]
> Hi @krmahadevan did as you proposed and finally managed to commit changes with proper CRLF line endings. I had git auto.crlf enabled as it's mandatory in my company and it was modifying all commits, it wasn't the IDE :(
> Hope it's working now. I struggled a bit to run tests including mine. I was expecting to be able to easily run them from the IDE but as I understood the setup goes through xml/yaml resource files which I initially wasn't aware.

Thank you so much for taking the time to get through with this and also run the tests. I was under the assumption that you would have already taken a look at https://github.com/cbeust/testng/blob/master/CONTRIBUTING.md (we created this specifically to help people get oriented).

File: src/test/java/org/testng/internal/MethodHelperTest.java (hunk 1 above)
Comment (juherr) [reply src/test/java/org/testng/internal/MethodHelperTest.java]: agree

**Review by juherr — APPROVED** [review]

**Comment by krmahadevan** [comment]
@juherr - I went ahead and did the following on this PR

1. Squashed the commits (1 commit that contains @iagotomas changes, 1 commit that contains your changes) and I added one commit to include your both names in the changes file.
2. Fixed the merge conflicts.

Since you have already approved this PR, I am going ahead and merging it.
