### PR TITLE
Bug/testng eclipse #144/#155: Timeout while trying to contact RemoteTestNG.

### LINKED ISSUE #48: in version 6.3.1 RemoteTestNG Runner will hangs if run with a error argument
Now I use testng-eclipse plugin 6.3.1 to run a testng xml file with a error argument, and the TestNG runner is hang.
    -listener org.testng.demo.TestListener
    org.testng.demo.TestListener class is not exist.

I think the reason is:
 1. RemoteTestNG load listener failed and exit.
 2. The method startTestRunListening of TestRunnerViewPart are called, and called BaseMessageSender initReceiver() method.  In initReceiver method, use a endless loop trying to contact RemoteTestNG, and hanghere.

### LINKED ISSUE #144: Timeout while trying to contact RemoteTestNG.
Just installed the testng eclipse plugin (6.9.0.201505070412	) and not able to run the tests now. I am getting the error as shown in this screenshot.

screen shot 2015-05-09 at 1 55 25 pm

### PR DESCRIPTION
**Pull request by missedone**
in this PR, i'd like to bring the while loop for socket.accept back.
beside, i added a new interface `stopReceiver()` allow the API invoker to break from the dead loop.

this is really a historical issue, here is the relate git commit history:
1. add while loop for socket.accept to fix issue #102 BaseMessageSender fails to connect if JVM is slow
2. remoe the while loop to fix https://github.com/cbeust/testng-eclipse/issues/48: testng-eclipse will be hang if run RemoteTestNG with error argument

after some investigation, i think we need bring the while loop back so that it can wait until the first client connect request arrive.
the way to fix the eclipse hang was wrong, the correct way to do it is:
1. put the init receiver into thread (this is done by putting it in a eclipse job)
2. hook into the eclipse launch lifecycle to correct stop the init reviever thread to prevent from a dead loop

Along with the PR for eclipse plugin: https://github.com/cbeust/testng-eclipse/pull/166
it fixes https://github.com/cbeust/testng-eclipse/issues/144 and https://github.com/cbeust/testng-eclipse/issues/155

### CODE REVIEW

File: src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java [hunk 1]
```diff
@@ -124,61 +127,68 @@ public void initReceiver() throws SocketTimeoutException {
...
       throw ste;
     }
     catch (IOException ioe) {
-      // TODO Auto-generated catch block
-      ioe.printStackTrace();
+      closeQuitely(serverSocket);
     }
   }
 
+  public void stopReceiver() {
```
Comment (missedone) [inline src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java]: allow to break the dead loop, to be called by testng eclipse plugin

**Comment by missedone** [comment]
link to corresponding plugin PR: https://github.com/cbeust/testng-eclipse/pull/166

File: src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java [hunk 2]
```diff
@@ -24,6 +26,7 @@
   private int m_port;
   protected Object m_ackLock = new Object();
 
+  private boolean m_requstStopReceiver;
```
Comment (juherr) [inline src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java]: Typo: m_requestStopReceiver

**Comment by juherr** [comment]
:+1:

**Comment by missedone** [comment]
thanks, fixed the typo

File: src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java [hunk 3]
```diff
@@ -124,61 +127,68 @@ public void initReceiver() throws SocketTimeoutException {
...
   public void shutDown() {
-    if(null != m_outStream) {
-      try {
-        m_outStream.close();
-      }
-      catch(IOException ex) {
-        // ignore
-      }
-      m_outStream = null;
+    closeQuitely(m_outStream);
```
Comment (cbeust) [inline src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java]: Typo: "quietly"

**Comment by cbeust** [comment]
I don't see anyone invoking `stopReceiver()`, am I missing something?

**Comment by missedone** [comment]
typo fixed.

@cbeust stopReceiver() is invoked at eclipse plugin side, when people cancel the Job or the Launch terminated
https://github.com/cbeust/testng-eclipse/pull/166/files

File: src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java [hunk 4]
```diff
@@ -124,61 +127,68 @@ public void initReceiver() throws SocketTimeoutException {
...
       throw ste;
     }
     catch (IOException ioe) {
-      // TODO Auto-generated catch block
-      ioe.printStackTrace();
+      closeQuietly(serverSocket);
     }
   }
 
+  public void stopReceiver() {
```
Comment (missedone) [inline src/main/java/org/testng/remote/strprotocol/BaseMessageSender.java]: this is invoked at eclipse plugin side: https://github.com/cbeust/testng-eclipse/pull/166/files#r37427417
