### PR TITLE
Flaky Test Fix - 2587

### LINKED ISSUE #2587: issue326.IssueTest: Expecting:  <1007L> to be less than or equal to: <1000L>
```
FAILURE   1,3sec, test.factory.issue326.IssueTest > testToCheckParallelExecutionOfInstancesWithOneThreadPerInstance
    java.lang.AssertionError: 
    Expecting:
     <1007L>
    to be less than or equal to:
     <1000L> 
        at test.factory.issue326.IssueTest.testToCheckParallelExecutionOfInstancesWithOneThreadPerInstance(IssueTest.java:29)
```

See https://github.com/cbeust/testng/runs/2752744004?check_suite_focus=true#step:6:498

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2587

Illustration:

```
Time --->
Freddy:  |-------------|
       100ms       900ms

Barney:       |-------------|
            300ms       1100ms
```

Check:

Freddy starts before Barney ends: 100 < 1100  true
Barney starts before Freddy ends: 300 < 900   true

So the windows overlap, meaning TestNG did not run Freddy completely first and Barney completely second.

Non-overlapping sequential execution would look like this:

```
Time --->

Freddy:  |-------------|
       100ms       900ms

Barney:                  |-------------|
                       950ms       1600ms
```

Check:

Freddy starts before Barney ends: 100 < 1600  true
Barney starts before Freddy ends: 950 < 900   false

So the assertion would fail.

Fixes # .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

## Summary by CodeRabbit

* **Tests**
  * Strengthened parallelism validation: verifies overlapping execution windows, exact per-instance invocation counts, and that each instance ran on a single, distinct thread.
  * Reworked timing checks to use interval overlap assertions rather than per-method start-time deltas for more robust concurrency verification.
* **Refactor**
  * Standardized concurrency utilities and listener internals for thread-safe recording.
  * Enhanced listener tracking to record end times and thread identifiers for more reliable timing and thread assertions.

### CODE REVIEW

File: testng-core/src/test/java/test/factory/issue326/IssueTest.java [hunk 1]
```diff
@@ -23,32 +25,52 @@ public void testToCheckParallelExecutionOfInstancesWithOneThreadPerInstance() {
     testng.addListener(listener);
     testng.run();
 
-    // Ensure that the difference in start times for the methods in both instances is <= 1000 ms.
-    long diff = computeDiffInStartTimeFor(listener.getResults(), SampleTestClass.FREDDY);
-    assertThat(diff).isLessThanOrEqualTo(1000);
-    diff = computeDiffInStartTimeFor(listener.getResults(), SampleTestClass.BARNEY);
-    assertThat(diff).isLessThanOrEqualTo(1000);
+    Map<String, List<Statistics>> results = listener.getResults();
```
Comment (juherr) [inline testng-core/src/test/java/test/factory/issue326/IssueTest.java:28]: Keep comments that explain what is checked and why

**Comment by juherr** [comment]
The Nitpick comment looks good

File: testng-core/src/test/java/test/factory/issue326/IssueTest.java (hunk 1 above)
Comment (krmahadevan) [reply testng-core/src/test/java/test/factory/issue326/IssueTest.java:28]: Fixed

**Comment by krmahadevan** [comment]
> The Nitpick comment looks good

Fixed

**Review by juherr — APPROVED** [review]
Lgtm but have a look at coderabbit review

File: testng-core/src/test/java/test/factory/issue326/LocalTrackingListener.java [hunk 2]
```diff
@@ -2,25 +2,24 @@
...
     String key = testResult.getInstance().toString();
-    results.computeIfAbsent(key, k -> Lists.newArrayList()).add(new Statistics(testResult));
-    if (!threadIds.containsKey(key)) {
-      Long threadId = Long.parseLong(testResult.getAttribute(SampleTestClass.THREAD_ID).toString());
-      threadIds.put(key, threadId);
-    }
+    results.computeIfAbsent(key, k -> new CopyOnWriteArrayList<>()).add(new Statistics(testResult));
+    Long threadId = asLong(testResult);
+    threadIds.putIfAbsent(key, threadId);
   }
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply testng-core/src/test/java/test/factory/issue326/LocalTrackingListener.java:23]: While this is a valid concern in the general context, its not relevant here because `test.factory.issue326.SampleTestClass#SampleTestClass` does not have any configuration methods.

**Comment by krmahadevan** [comment]
> Lgtm but have a look at coderabbit review

Its not relevant to this PR in specific because the sample class in question does not have configuration methods.
