### PR TITLE
Prevent <test> level params from being hoisted to <suite> level.

### LINKED ISSUE #1250: Testng-failed.xml is getting test level parameters into suite level parameters
### Expected behavior
parameters declared at `<test>` level are supposed to be retained at `<test>` level and not supposed to be hoisted to the `<suite> level.

### Actual behavior
Currently TestNG seems to be hoisting `<test>` level parameters to the `<suite>` level.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

Sample that can be used to recreate the problem.

Testcase

```java
package org.rationale.emotions;

import org.testng.Assert;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class OperatingSystemTest {
    @Parameters("flavor")
    @Test
    public void testOperatingSystem(@Optional String flavor) {
        if ("windows".equalsIgnoreCase(flavor)) {
            throw new IllegalStateException("Simulating a failure");
        }
        Assert.assertTrue(flavor.length() > 1);
    }
}
```

Original suite xml file

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="My Suite" parallel="false" verbose="2">
    <test name="Desktop">
        <classes>
            <class name="org.rationale.emotions.OperatingSystemTest"/>
        </classes>
    </test>

    <test name="Tablet">
        <parameter name="flavor" value="windows"/>
        <classes>
            <class name="org.rationale.emotions.OperatingSystemTest"/>
        </classes>
    </test>

    <test name="Mobile">
        <parameter name="flavor" value="IPHONE6Plus"/>
        <classes>
            <class name="org.rationale.emotions.OperatingSystemTest"/>
        </classes>
    </test>
</suite>
```

Actual contents of `testng-failed.xml` being generated

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" verbose="2" name="Failed suite [My Suite]">
  <parameter name="flavor" value="IPHONE6Plus"/>
  <test name="Desktop(failed)">
    <classes>
      <class name="org.rationale.emotions.OperatingSystemTest">
        <methods>
          <include name="testOperatingSystem" invocation-numbers="0"/>
        </methods>
      </class> <!-- org.rationale.emotions.OperatingSystemTest -->
    </classes>
  </test> <!-- Desktop(failed) -->
  <test name="Tablet(failed)">
    <parameter name="flavor" value="windows"/>
    <classes>
      <class name="org.rationale.emotions.OperatingSystemTest">
        <methods>
          <include name="testOperatingSystem" invocation-numbers="0"/>
        </methods>
      </class> <!-- org.rationale.emotions.OperatingSystemTest -->
    </classes>
  </test> <!-- Tablet(failed) -->
</suite> <!-- Failed suite [My Suite] -->
```

Expected contents were supposed to be 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" verbose="2" name="Failed suite [My Suite]">
  <test name="Desktop(failed)">
    <classes>
      <class name="org.rationale.emotions.OperatingSystemTest">
        <methods>
          <include name="testOperatingSystem" invocation-numbers="0"/>
        </methods>
      </class> <!-- org.rationale.emotions.OperatingSystemTest -->
    </classes>
  </test> <!-- Desktop(failed) -->
  <test name="Tablet(failed)">
    <parameter name="flavor" value="windows"/>
    <classes>
      <class name="org.rationale.emotions.OperatingSystemTest">
        <methods>
          <include name="testOperatingSystem" invocation-numbers="0"/>
        </methods>
      </class> <!-- org.rationale.emotions.OperatingSystemTest -->
    </classes>
  </test> <!-- Tablet(failed) -->
</suite> <!-- Failed suite [My Suite] -->

```

Refer to this TestNG forum thread : https://groups.google.com/forum/#!topic/testng-users/AeVrrSqKSfI

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes # 1250

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

Fixes #1250

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - Can you please help review ?

**Comment by juherr** [comment]
LGTM :+1: Ping @cbeust

File: src/test/java/test/failedreporter/FailedReporterParametersTest.java [hunk 1]
```diff
@@ -77,9 +77,6 @@ public static void runAssertions(File outputDir, String expectedFormat, String[]
       List<String> resultLines = Lists.newArrayList();
       grep(failed, String.format(expectedFormat, expectedKey, expectedKey + "Value"), resultLines);
       int expectedSize = 1;
-      if ("testParam".equals(expectedKey)) {
-        expectedSize = 2;
-      }
```
Comment (cbeust) [inline src/test/java/test/failedreporter/FailedReporterParametersTest.java]: Is this change related to this PR?

Comment (krmahadevan) [inline src/test/java/test/failedreporter/FailedReporterParametersTest.java]: @cbeust : yes this change is part of the pull request.

*Explanation*
Without the fix, `testng-failed.xml` was generated such that the the parameters 
`<parameter name="testParam" value="testParamValue"/>` was being made available
at both the `<suite>` level and `<test>` level.

After I fixed it, it will now be *ONLY* available at the scope as per the original suite file (so in our case only at the `<test>` level).

The reason I deleted these lines from the test was because the tests were doing an incorrect assertion (which I fixed )

*Suite file generated by this unit test*
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite verbose="0" name="Default Suite">
  <parameter name="suiteParam" value="suiteParamValue"/>
  <test name="Command line test 9deb29f4-4649-4fb0-bc67-03fb90c09b5f">
    <parameter name="testParam" value="testParamValue"/>
    <classes>
      <class name="">
        <parameter name="classParam" value="classParamValue"/>
        <methods>
          <include name="f2">
            <parameter name="methodParam" value="methodParamValue"/>
          </include> <!-- f2 -->
        </methods>
      </class> <!--  -->
    </classes>
  </test> <!-- Command line test 9deb29f4-4649-4fb0-bc67-03fb90c09b5f -->
</suite> <!-- Default Suite -->
```

*`testng-failed.xml` generated by the test without the file* (as you can see the `testParam` is available at both the `<suite>` and `<test>` level even though it wasn't the case in the original xml)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite verbose="0" name="Failed suite [Default Suite]">
  <parameter name="suiteParam" value="suiteParamValue"/>
  <parameter name="testParam" value="testParamValue"/>
  <test name="Command line test 9deb29f4-4649-4fb0-bc67-03fb90c09b5f(failed)">
    <parameter name="testParam" value="testParamValue"/>
    <classes>
      <class name="test.failedreporter.FailedReporterSampleTest">
        <parameter name="classParam" value="classParamValue"/>
        <methods>
          <include name="f2">
            <parameter name="methodParam" value="methodParamValue"/>
          </include> <!-- f2 -->
        </methods>
      </class> <!-- test.failedreporter.FailedReporterSampleTest -->
    </classes>
  </test> <!-- Command line test 9deb29f4-4649-4fb0-bc67-03fb90c09b5f(failed) -->
</suite> <!-- Failed suite [Default Suite] -->
```

**Comment by krmahadevan** [comment]
@cbeust - Please let me know if you need anything more from my side before merging this change.

**Comment by krmahadevan** [comment]
Resolved merge conflicts to bring back the branch to a mergeable state. Ping @cbeust @juherr

**Comment by krmahadevan** [comment]
ping @cbeust  (I have fixed the conflicts)
