### PR TITLE
-Dtestng.thread.affinity=true do not work when running multiple instance of test in parallel

### LINKED ISSUE #2321: -Dtestng.thread.affinity=true do not work when running multiple instance of test in parallel
### Expected behavior
two instance of test class should get different thread. All the test method within the test class should run in same thread.

### Actual behavior
Test method of same instance are getting different thread.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class MultipleInstance {
    private int part;

    private long threadId;

    @Factory(dataProvider = "dp")
    public MultipleInstance(int part) {
        this.part = part;
    }

    @Test
    public void independent() {
        threadId = Thread.currentThread().getId();
        System.err.println(getClass().getSimpleName() + " part - " + part + " independent() running on " + threadId);
    }

    @Test(dependsOnMethods = "independent")
    public void dependent() {
        long currentThreadId = Thread.currentThread().getId();
        System.err.println(getClass().getSimpleName() + " part - " + part + " dependent() running on " + currentThreadId);
        Assert.assertEquals(currentThreadId, threadId, "Thread Ids didn't match");
    }


    @DataProvider(name = "dp")
    public static Object[][] getData() {
        return new Object[][]{
                {1},
                {2}
        };
    }
}
```

```java
import java.util.Collections;

public class IssueTest {
    public static void main(String[] args) {
        XmlSuite xmlSuite = new XmlSuite();
        xmlSuite.setName("sample_suite");
        xmlSuite.setParallel(XmlSuite.ParallelMode.INSTANCES);
        xmlSuite.setVerbose(2);
        XmlTest xmlTest = new XmlTest(xmlSuite);
        xmlTest.setName("sample_test");
        xmlTest.setParallel(XmlSuite.ParallelMode.INSTANCES);
        xmlTest.setVerbose(2);
        xmlTest.setXmlClasses(Collections.singletonList(new XmlClass(MultipleInstance.class)));
        System.err.println(xmlSuite.toXml());
        System.setProperty("testng.thread.affinity", "true");
        TestNG testng = new TestNG();
        testng.setXmlSuites(Collections.singletonList(xmlSuite));
        testng.run();
    }
}
```

### PR DESCRIPTION
**Pull request by kobebryant2007**
-Dtestng.thread.affinity=true do not work when running multiple instance of test in parallel

Closes #2321

Fixes #2321 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/DependencyMap.java [hunk 1]
```diff
@@ -82,13 +83,22 @@ private static boolean hasInstance(
       ITestNGMethod baseClassMethod, ITestNGMethod derivedClassMethod) {
     Object baseInstance = baseClassMethod.getInstance();
     Object derivedInstance = derivedClassMethod.getInstance();
-    return derivedInstance != null || baseInstance != null;
+    boolean result = derivedInstance != null || baseInstance != null;
+    boolean params = null != baseClassMethod.getFactoryMethodParamsInfo() && null != derivedClassMethod.getFactoryMethodParamsInfo().getParameters();
+    if (result && params && System.getProperty("testng.thread.affinity", "false").equals("true")) {
```
Comment (krmahadevan) [inline src/main/java/org/testng/DependencyMap.java:88]: Please use `org.testng.internal.RuntimeBehavior#enforceThreadAffinity` instead of querying the JVM argument

File: src/main/java/org/testng/DependencyMap.java [hunk 2]
```diff
@@ -82,13 +83,22 @@ private static boolean hasInstance(
...
+    }
+    return result;
   }
 
   private static boolean isSameInstance(
       ITestNGMethod baseClassMethod, ITestNGMethod derivedClassMethod) {
     Object baseInstance = baseClassMethod.getInstance();
     Object derivedInstance = derivedClassMethod.getInstance();
+    boolean result = derivedInstance != null && baseInstance != null;
+    if (result && null != baseClassMethod.getFactoryMethodParamsInfo() && System.getProperty("testng.thread.affinity", "false").equals("true")) {
```
Comment (krmahadevan) [inline src/main/java/org/testng/DependencyMap.java:99]: Please use `org.testng.internal.RuntimeBehavior#enforceThreadAffinity` instead of querying the JVM argument

File: src/test/java/test/testng2321/TestMultipleInstance.java [hunk 3]
```diff
@@ -0,0 +1,50 @@
+package test.testng2321;
+
+import org.testng.Assert;
+import org.testng.annotations.AfterSuite;
+import org.testng.annotations.BeforeSuite;
+import org.testng.annotations.DataProvider;
+import org.testng.annotations.Factory;
+import org.testng.annotations.Test;
+
+public class TestMultipleInstance {
```
Comment (krmahadevan) [inline src/test/java/test/testng2321/TestMultipleInstance.java:10]: Instead of having this as a separate class, can you please have this moved into `test.thread.parallelization.issue1773.IssueTest` as a test method ? This test class can be invoked by test method in this class and checked for exit status.

**Review by krmahadevan — CHANGES_REQUESTED** [review]

File: src/test/resources/2321.xml [hunk 4]
```diff
@@ -0,0 +1,9 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (krmahadevan) [inline src/test/resources/2321.xml:1]: This suite file is not being referred to in the main `src/test/resources/testng.xml` file

File: src/main/java/org/testng/DependencyMap.java [hunk 5]
```diff
@@ -82,13 +83,22 @@ private static boolean hasInstance(
...
+      return baseInstance.getClass().isAssignableFrom(derivedInstance.getClass()) && baseClassMethod.getFactoryMethodParamsInfo().getParameters()[0] == derivedClassMethod.getFactoryMethodParamsInfo().getParameters()[0];
```
Comment (krmahadevan) [inline src/main/java/org/testng/DependencyMap.java:100]: Shouldn't we be doing an equality check rather than checking a reference equality ?

File: src/main/java/org/testng/DependencyMap.java [hunk 6]
```diff
@@ -82,13 +83,22 @@ private static boolean hasInstance(
       ITestNGMethod baseClassMethod, ITestNGMethod derivedClassMethod) {
     Object baseInstance = baseClassMethod.getInstance();
     Object derivedInstance = derivedClassMethod.getInstance();
-    return derivedInstance != null || baseInstance != null;
+    boolean result = derivedInstance != null || baseInstance != null;
+    boolean params = null != baseClassMethod.getFactoryMethodParamsInfo() && null != derivedClassMethod.getFactoryMethodParamsInfo().getParameters();
+    if (result && params && System.getProperty("testng.thread.affinity", "false").equals("true")) {
+      return baseClassMethod.getFactoryMethodParamsInfo().getParameters()[0] == derivedClassMethod.getFactoryMethodParamsInfo().getParameters()[0];
```
Comment (krmahadevan) [inline src/main/java/org/testng/DependencyMap.java:89]: Shouldn't we be doing an equality check rather than checking a reference equality ?

**Comment by krmahadevan** [comment]
@kobebryant2007 - I went ahead and applied the changes that I called out as part of the code review.

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@juherr - I identified the review points and fixed them as well. Please take a look and add your comments if there are any.

File: src/main/java/org/testng/DependencyMap.java [hunk 7]
```diff
@@ -82,13 +83,30 @@ private static boolean hasInstance(
...
+      ITestNGMethod baseClassMethod, ITestNGMethod derivedClassMethod) {
+    return baseClassMethod.getFactoryMethodParamsInfo().getParameters()[0]
+        .equals(derivedClassMethod.getFactoryMethodParamsInfo().getParameters()[0]);
   }
 
   private static boolean isSameInstance(
       ITestNGMethod baseClassMethod, ITestNGMethod derivedClassMethod) {
     Object baseInstance = baseClassMethod.getInstance();
     Object derivedInstance = derivedClassMethod.getInstance();
+    boolean result = derivedInstance != null && baseInstance != null;
```
Comment (juherr) [inline src/main/java/org/testng/DependencyMap.java:105]: I propose:

```java
if (derivedInstance != null && baseInstance != null) {
  if (null != baseClassMethod.getFactoryMethodParamsInfo() && RuntimeBehavior.enforceThreadAffinity()) {
    return baseInstance.getClass().isAssignableFrom(derivedInstance.getClass()) &&
          hasSameParameters(baseClassMethod, derivedClassMethod);  
  } else {
    return baseInstance.getClass().isAssignableFrom(derivedInstance.getClass());
  }
} else {
  return false;
}
```

It highlights the difference between the 2 options.
Quick return could be used too.

**Review by juherr — APPROVED** [review]
Just check my proposition on the style :)

File: src/main/java/org/testng/DependencyMap.java (hunk 7 above)
Comment (krmahadevan) [reply src/main/java/org/testng/DependencyMap.java]: Fixed
