### PR TITLE
No exception catching on assertion #2182

### LINKED ISSUE #2182: Replace exception catching validation on assertNotEquals
### TestNG Version
7.0.0

### Expected behavior
**assertNotEquals** should not catch exception as a valid behaviour.

### Actual behavior
**assertNotEquals** uses **AssertionError** thrown from **assertEquals** as validation.

Using exception breakpoint on **AssertionError** results on false positives because of this behaviour.

### PR DESCRIPTION
**Pull request by cdalexndr**
Fixes #2182.

### Did you remember to?

- [ ] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Review by krmahadevan — COMMENTED** [review]
@cdalexndr - Can you please add an entry into `CHANGES.txt` ?

File: src/main/java/org/testng/Assert.java [hunk 1]
```diff
@@ -118,57 +118,86 @@ public static void assertEquals(Object actual, Object expected, String message)
...
 
-  private static void assertArrayEquals(Object actual, Object expected, String message) {
-    if (expected == actual) {
-      return;
-    }
-    if (null == expected) {
-      fail("expected a null array, but not null found. " + message);
+  /** returns not equal reason or null if equal **/
+  private static String getArrayNotEqualReason(Object actual, Object expected){
+    if(actual == expected)
```
Comment (krmahadevan) [inline src/main/java/org/testng/Assert.java:162]: can we please use `{}` for this `if` condition ?

**Review by krmahadevan — CHANGES_REQUESTED** [review]

File: src/main/java/org/testng/Assert.java [hunk 2]
```diff
@@ -118,57 +118,87 @@ public static void assertEquals(Object actual, Object expected, String message)
...
-      return;
+  /** returns not equal reason or null if equal **/
+  private static String getArrayNotEqualReason(Object actual, Object expected){
+    if(actual == expected) {
+      return null;
     }
-    if (null == expected) {
-      fail("expected a null array, but not null found. " + message);
+    if(null == expected) {
+      return "expected a null array, but not null found";
```
Comment (krmahadevan) [inline src/main/java/org/testng/Assert.java:166]: @cdalexndr - An invocation to `fail(msg)` would trigger an assertion error with that msg, but now we are returning back error messages, which don't seem to be used anywhere at all. So wouldn't that actually change our error reporting during failures ?

For e.g., `getArrayNotEqualReason()` is being invoked in the below method

```java
private static boolean areArraysEqual(Object actual, Object expected){
     return getArrayNotEqualReason( actual, expected ) == null;
   }
```

but here the error message is not being used at all, which means its getting lost no ?

Comment (cdalexndr) [reply src/main/java/org/testng/Assert.java:166]: I use the error message to not duplicate code and use a single method for checking equality/inequality. The same method can be used to check equality when error message is null or check inequality when error message is not null.
This method `areArraysEqual` has no usage for the error message because it returns a boolean, but other methods use the error message when failing `fail(errorMsg)`.

Comment (cdalexndr) [reply src/main/java/org/testng/Assert.java:166]: `getArrayNotEqualReason` error message is used in `getNotEqualDeepReason` method:
```
public static String getNotEqualDeepReason(Set<?> actual, Set<?> expected){
....
  String arrayNotEqualReason = getArrayNotEqualReason( value, expectedValue );
        if(arrayNotEqualReason != null)
          return arrayNotEqualReason;
....
}
```
which is used in `assertEqualsDeep`:
```
  public static void assertEqualsDeep(Set<?> actual, Set<?> expected, String message) {
    String notEqualDeepReason = getNotEqualDeepReason( actual, expected );
    if(notEqualDeepReason != null){
      if (message == null) {
        fail(notEqualDeepReason);
....
```

Comment (cdalexndr) [reply src/main/java/org/testng/Assert.java:166]: Just changed `getNotEqualDeepReason` method visibility from public to private.

**Review by krmahadevan — APPROVED** [review]

**Review by juherr — CHANGES_REQUESTED** [review]
Please check the code style which doesn't follow the current convention.

**Comment by cdalexndr** [comment]
Where can I find the code style options? There is no mention in [Contributing](https://github.com/cbeust/testng/blob/master/CONTRIBUTING.md).
You should add an [.editorconfig](https://editorconfig.org/) file that is automatically applied by some IDEs.

**Comment by krmahadevan** [comment]
@cdalexndr - 

> Where can I find the code style options?

We are using the google code style https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

> There is no mention in Contributing.

Sure. We will enhance the document to include reference to this.

> You should add an .editorconfig file that is automatically applied by some IDEs.

Good suggestion. Will add up this as well to TestNG.

**Comment by cdalexndr** [comment]
Formatted code

**Comment by cdalexndr** [comment]
Opened https://github.com/cbeust/testng/issues/2291 regarding code style.

**Comment by krmahadevan** [comment]
@juherr - Please advise if this can be merged.

**Review by juherr — APPROVED** [review]
