### PR TITLE
Attempt at reducing memory foot print

### LINKED ISSUE #2096: 7.0.0-beta6 memory issues (regression)
A test task runs over 310,000 independent test executions. In `6.14.3` this completes in about 2.5 minutes. In `7.0.0-beta6` this slows down to a crawl at 200k tests, appearing to GC thrash as small batches of tests complete.

In the past, I've seen this occur due to reporting keeping parameters in-memory. The project uses a [workaround](https://github.com/ben-manes/caffeine/blob/c6264dad9b54eeff0193f9c6f77339d0c45f9141/caffeine/src/test/java/com/github/benmanes/caffeine/cache/testing/CacheValidationListener.java#L149-L161) to replace test parameters with their `toString` version, as these are too heavy for a large run. I suspect there is some similar per-test memory grab by the reporter.

The next step is probably to take a heap dump and determine what is held. Before running too far into this, do you know what changes were made that might hint at what to look for?

```gradle
./gradlew :caffeine:strongKeysAndStrongValuesAsyncCaffeineTest
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2096

As part of reducing the memory foot print following
was done:

* No TestNG listeners would now extend 
TestListenerAdapter. Instead everyone will implement
the required interfaces.
* Remove unwanted aggregation of method references
and instead resort to providing the same info
on demand.
* Refactored TestRunner to not explicitly keep
track of invoked methods and instead baked that
knowledge into the ITestNGMethod object itself
via a boolean.

Fixes #2096  .

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/MethodHelper.java [hunk 1]
```diff
@@ -435,6 +436,35 @@ public static void fixMethodsWithClass(
     return methodInstances.stream().map(IMethodInstance::getMethod).collect(Collectors.toList());
   }
 
+  public static void dumpInvokedMethodInfoToConsole(
+      ITestNGMethod[] methods, int currentVerbosity) {
+    if (currentVerbosity < 3) {
+      return;
+    }
+    System.out.println("===== Invoked methods");
```
Comment (juherr) [inline src/main/java/org/testng/internal/MethodHelper.java:444]: Remove sysout

**Review by juherr — APPROVED** [review]

File: src/main/java/org/testng/internal/MethodHelper.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/MethodHelper.java:444]: @juherr - That was existing code. Its not something I added newly. Will clean up them (found some other places also) in a subsequent PR
