### PR TITLE
Fixing error message verbiage

### LINKED ISSUE #1440: Improve error message when wrong params on configuration methods
Related to #202 and #128 

> Error shown :- FAILED CONFIGURATION: @AfterTest Fail_Test || java.lang.IllegalArgumentException: wrong number of arguments

With 

```java
@AfterTest
void Fail_Test(ITestResult Result) throws IOException {
  ...
```

From: https://stackoverflow.com/q/44134266/4234729

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixed the error message verbiage for config methods 
with wrong params.

Closes #1440

Fixes #1440 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr - Can you please help with this PR ?

The Travis Build failed for OracleJDK7 with the below error 

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

So I guess we should be fine.

File: src/main/java/org/testng/internal/Parameters.java [hunk 1]
```diff
@@ -57,6 +57,8 @@
   static {
     List<Class> ctxTest = Arrays.asList(new Class[] {ITestContext.class, XmlTest.class});
     List<Class> mParams = Arrays.asList(new Class[] {ITestContext.class, XmlTest.class,Method.class,Object[].class});
+    List<Class> mParamsBeforeAfterMethods = new ArrayList<>(mParams);
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: Could be more symmetric: use `asList` here or use `new ArrayList` above.

File: src/main/java/org/testng/internal/Parameters.java [hunk 2]
```diff
@@ -258,6 +269,22 @@ private static void checkParameterTypes(String methodName,
     }
   }
 
+  private static boolean validParameters(String methodAnnotation,Class[] parameterTypes) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: a blank space is missing

File: src/main/java/org/testng/internal/Parameters.java [hunk 3]
```diff
@@ -258,6 +269,22 @@ private static void checkParameterTypes(String methodName,
...
+    boolean flag = true;
+    methodAnnotation = methodAnnotation.replace("@","");
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: blank space missing

File: src/main/java/org/testng/internal/Parameters.java (hunk 1 above)
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: Could be `List<Class<?>>`

File: src/main/java/org/testng/internal/Parameters.java [hunk 4]
```diff
@@ -258,6 +269,22 @@ private static void checkParameterTypes(String methodName,
...
+    List<Class> localMapping = mapping.get(methodAnnotation);
+    if (localMapping == null) {
+      return false;
+    }
+    for (Class parameterType : parameterTypes) {
+      if (! localMapping.contains(parameterType)) {
+        flag = false;
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: `return false`?

File: src/test/java/test/inject/NativeInjectionTest.java [hunk 5]
```diff
@@ -20,14 +20,15 @@ public void testBeforeSuiteInjection(Class clazz, String methodName, String expe
 
     @DataProvider
     public Object[][] getTestData() {
-        String variant1="Can inject only one of <ITestContext, XmlTest> into a %s annotated ";
-        String variant2="Can inject only one of <ITestContext, XmlTest, Method, Object[]> into a %s annotated ";
+        String variant1="Can inject only one of <ITestContext, XmlTest> into a @%s annotated ";
+        String variant2="Can inject only one of <ITestContext, XmlTest, Method, Object[]> into a @%s annotated ";
```
Comment (juherr) [inline src/test/java/test/inject/NativeInjectionTest.java]: variant2 is no more tested. Could you find an appropriate use case or remove the variant?

**Review by juherr — COMMENTED** [review]
Few little propositions of change

**Comment by juherr** [comment]
@krmahadevan Could you check #202 and #128 at the same time if the issues are related? Maybe new test cases will be enough.

**Comment by krmahadevan** [comment]
@juherr  - I have fixed all the review comments.

For #202 - I am not able to recreate the problem. I used the below sample

```java
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.lang.reflect.Method;
import java.util.Arrays;

public class Github202 {
    @BeforeMethod
    public void setUp(Object[] params, Method method) {
        System.err.println("Incoming parameters : " + Arrays.toString(params));
        System.err.println("Method : " + method.getName() + "()");
    }

    @Test(dataProvider = "param")
    public void testMethod1_ok(String param) {
        System.err.println("Parameter : " + param);
    }

    @Test
    public void testMethod2_bug() {
    }

    @DataProvider(name = "param")
    public Object[][] getParam() {
        return new Object[][]{{"Kuk"}};
    }
}
```

And here's the output 
```
Incoming parameters : [Kuk]
Method : testMethod1_ok()
Parameter : Kuk
Incoming parameters : []
Method : testMethod2_bug()

===============================================
Default Suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================
```

For #128 - I think its a different issue because it talks about data provider driven test methods being triggered as mismatched methods, but the current issue is related to error messages on configs.

**Comment by krmahadevan** [comment]
The Oracle JDK8 build failure was from `test.thread.parallelization.ParallelByMethodsTestCase6Scenario1.verifyThatTestMethodsRunInParallelThreads()` which is NOT related to my changes.

File: src/main/java/org/testng/internal/Parameters.java [hunk 6]
```diff
@@ -233,19 +260,27 @@ private static void checkParameterTypes(String methodName,
...
+
+    if ((parameterNames.length == 0)) {
       //parameterNames is usually populated via the @Parameters annotation, so we would need to
       //apply our logic only when @Parameters annotation is not involved.
-      String errPrefix = "Cannot inject " + methodAnnotation + " annotated Method [" + methodName + "] with "
-            + Arrays.toString(parameterTypes);
-      if (mapping.containsKey(methodAnnotation)) {
-        errPrefix = "Can inject only one of " + prettyFormat(mapping.get(methodAnnotation)) +
-            " into a " + methodAnnotation + " annotated " + methodName;
+      String annotation = methodAnnotation;
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: It looks `annotation` is only used in the `if (invalid)` so this part could be moved there (and we will gain a bit)

File: src/main/java/org/testng/internal/Parameters.java [hunk 7]
```diff
@@ -52,11 +52,39 @@
...
+          | AfterMethod  | Yes          | Yes     | Yes    | Yes      | Yes         |
+          +--------------+--------------+---------+--------+----------+-------------+
+          | Test         | Yes          | No      | No     | No       | No          |
+          +--------------+--------------+---------+--------+----------+-------------+
 
+ */
   static {
-    List<Class> ctxTest = Arrays.asList(new Class[] {ITestContext.class, XmlTest.class});
-    List<Class> mParams = Arrays.asList(new Class[] {ITestContext.class, XmlTest.class,Method.class,Object[].class});
+    List<Class<?>> ctxTest = Arrays.asList(new Class<?>[]{ITestContext.class, XmlTest.class});
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: You can remove the `new Class<?>[]` here as `asList` has varargs.

File: src/main/java/org/testng/internal/Parameters.java [hunk 8]
```diff
@@ -69,13 +97,12 @@
     mapping.put(BeforeClass.class.getSimpleName(), ctxTest);
     mapping.put(AfterClass.class.getSimpleName(), ctxTest);
 
-    mapping.put(BeforeMethod.class.getSimpleName(), mParams);
-    mapping.put(AfterMethod.class.getSimpleName(), mParams);
+    mapping.put(BeforeMethod.class.getSimpleName(), beforeAfterMethod);
+    mapping.put(AfterMethod.class.getSimpleName(), beforeAfterMethod);
+    mapping.put(Test.class.getSimpleName(), Arrays.asList(new Class<?>[] {ITestContext.class}));
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: I prefer `Collections.singletonList(ITestContext.class)`

File: src/main/java/org/testng/internal/Parameters.java [hunk 9]
```diff
@@ -233,19 +260,27 @@ private static void checkParameterTypes(String methodName,
       }
     }
 
-    if ( (parameterNames.length ==0) && (totalLength != 0) ) {
+
+    if ((parameterNames.length == 0)) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: Useless brackets

File: src/main/java/org/testng/internal/Parameters.java [hunk 10]
```diff
@@ -258,7 +293,21 @@ private static void checkParameterTypes(String methodName,
...
   }
 
-  private static String prettyFormat(List<Class> classes) {
+  private static boolean validParameters(String methodAnnotation, Class[] parameterTypes) {
+    methodAnnotation = methodAnnotation.replace("@", "");
+    List<Class<?>> localMapping = mapping.get(methodAnnotation);
+    if (localMapping == null) {
+      return false;
+    }
+    for (Class parameterType : parameterTypes) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: `Class<?>`

File: src/main/java/org/testng/internal/Parameters.java [hunk 11]
```diff
@@ -52,11 +52,39 @@
       AfterMethod.class
   };
 
-  private static Map<String, List<Class>> mapping = Maps.newHashMap();
+  private static Map<String, List<Class<?>>> mapping = Maps.newHashMap();
+/*
+          +--------------+--------------+---------+--------+----------+-------------+
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: Very good idea! I made a wiki page with it https://github.com/cbeust/testng/wiki/Allowrd-parameters-injection-in-methods

File: src/main/java/org/testng/internal/Parameters.java [hunk 12]
```diff
@@ -233,19 +260,27 @@ private static void checkParameterTypes(String methodName,
...
-      if (mapping.containsKey(methodAnnotation)) {
-        errPrefix = "Can inject only one of " + prettyFormat(mapping.get(methodAnnotation)) +
-            " into a " + methodAnnotation + " annotated " + methodName;
+      String annotation = methodAnnotation;
+      if (!methodAnnotation.startsWith("@")) {
+        annotation = "@" + methodAnnotation;
+      }
+      boolean invalid = (totalLength != 0) || (!validParameters(methodAnnotation, parameterTypes));
+      if (invalid) {
+        String errPrefix = "Cannot inject " + annotation + " annotated Method [" + methodName + "] with "
```
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: In that case, it may be easier to understand with if/else

**Review by juherr — COMMENTED** [review]
Some new little remarks

**Comment by juherr** [comment]
@krmahadevan For #202, is it possible the issue comes from `@Test` on class?

File: src/main/java/org/testng/internal/Parameters.java (hunk 7 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: I tried this earlier, but IntelliJ keeps warning me saying that incompatible types (expected `List<Class<?>>` but found `List<Class<? extends Serializable>>`). So i had to leave this as is.

File: src/main/java/org/testng/internal/Parameters.java (hunk 8 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: This also causes an error because `Collections.singletonList(ITestContext.class)` results in a `List<ITestContext>` but the mapping's type is defined as `Map<String, List<Class<?>>>`.

File: src/main/java/org/testng/internal/Parameters.java (hunk 9 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: fixed.

File: src/main/java/org/testng/internal/Parameters.java (hunk 6 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: fixed.

File: src/main/java/org/testng/internal/Parameters.java (hunk 10 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: fixed.

File: src/main/java/org/testng/internal/Parameters.java (hunk 12 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: Fixed.

**Comment by krmahadevan** [comment]
@juherr 

> For #202, is it possible the issue comes from @Test on class?

I tried that way as well. Still not able to reproduce the issue.

File: src/main/java/org/testng/internal/Parameters.java (hunk 7 above)
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: Ok, strange.

File: src/main/java/org/testng/internal/Parameters.java (hunk 12 above)
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: In fact, the idea was to move the `errPrefix` init in the if/else block. Could you just change it and squash your commits before the merge?

Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: @juherr - `errPrefix` init has to be outside of the `if/else` block because its eventually being used to form the default prefix for the error message...

Please see below the relevant code snippet.
```java
String errPrefix = "Cannot inject " + annotation + " annotated Method [" + methodName + "] with " + Arrays.toString(parameterTypes);
if (mapping.containsKey(methodAnnotation)) {
  errPrefix = "Can inject only one of " + prettyFormat(mapping.get(methodAnnotation)) + " into a " + annotation + " annotated " + methodName;
}
throw new TestNGException(errPrefix + ".\nFor more information on native dependency injection please refer to " + "http://testng.org/doc/documentation-main.html#native-dependency-injection"
);
```

Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]:
```java
String errPrefix;
if (mapping.containsKey(methodAnnotation)) {
  errPrefix = "Can inject only one of " + prettyFormat(mapping.get(methodAnnotation)) + " into a " + annotation + " annotated " + methodName;
} else {
  errPrefix = "Cannot inject " + annotation + " annotated Method [" + methodName + "] with " + Arrays.toString(parameterTypes);
}
throw new TestNGException(errPrefix + ".\nFor more information on native dependency injection please refer to " + "http://testng.org/doc/documentation-main.html#native-dependency-injection"
);
```

My fault, I was not explicit enough :) The idea is to avoid a string generation when the if case is true.

Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: Ah ok! My bad.. I am still warming up from all the **bed rest** :) Fixed it and squashed all the commits into one and did a forceful push.

**Comment by krmahadevan** [comment]
@juherr  - I have squashed the commits and did the changes like you had suggested.

**Review by juherr — APPROVED** [review]
LGTM! 👍 
Ping @cbeust

File: src/main/java/org/testng/internal/Parameters.java (hunk 11 above)
Comment (cbeust) [inline src/main/java/org/testng/internal/Parameters.java]: Great idea indeed.

Looking more closely to this table, I'm surprised `XmlTest` is allowed in `@BeforeSuite` since that doesn't make sense to me (we haven't entered a `<test>` tag yet). Is this correct?

File: src/main/java/org/testng/internal/Parameters.java (hunk 7 above)
Comment (cbeust) [inline src/main/java/org/testng/internal/Parameters.java]: By the way, ideally, this table should be in the doc and not the wiki, if one of you wants to add it there as well.

Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: Agree but the wiki was faster :)

File: src/main/java/org/testng/internal/Parameters.java (hunk 11 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: @cbeust - Yes. This seems to be current behavior. Just to ensure that this was the case, I backtracked to using TestNG 6.9.9 and found that this was the case.

Here's a sample
```java
import org.testng.TestNG;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;
import org.testng.xml.XmlTest;

import java.io.File;

public class SuiteLevelInjection {
    @BeforeSuite
    public void beforeSuite(XmlTest xmlTest) {
        String file = TestNG.class.getProtectionDomain().getCodeSource().getLocation().getFile();
        System.err.println("TestNG Version " + new File(file).getParentFile().getName());
        System.err.println("XmlTest name :" + xmlTest.getName());
        System.err.println("Classes : " + xmlTest.getClasses());
    }

    @Test
    public void testMethod() {
        System.err.println("Test method name ");
    }
}
```

And here's the output
```
[TestNG] Running:
  /Users/krmahadevan/Library/Caches/IntelliJIdea2017.1/temp-testng-customsuite.xml
TestNG Version 6.9.9
XmlTest name :testbed
Classes : [[XmlClass class=com.rationaleemotions.github.issue1446.SuiteLevelInjection]]
Test method name 

===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

Comment (cbeust) [inline src/main/java/org/testng/internal/Parameters.java]: Thanks for testing this, @krmahadevan, but what does it mean exactly? Which `<test>` is being passed since the parser hasn't reached any yet in `@BeforeSuite`?

Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: @cbeust Its picking the `XmlTest` object that represents the last `<test>` tag found in the TestNG suite xml file and then showing its details. To be honest, the behavior is weird and TestNG should not allow a `XmlTest` injection into the `@BeforeSuite` annotation as you called out. But this will cause a backward compatibility issue if we fix this. Please let me know what needs to be done.

File: src/main/java/org/testng/internal/Parameters.java (hunk 7 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/Parameters.java]: @juherr / @cbeust - I raised a PR to the documentation site https://github.com/testng-team/testng-team.github.io/pull/20 can you please help take a look ?

File: src/main/java/org/testng/internal/Parameters.java (hunk 11 above)
Comment (juherr) [inline src/main/java/org/testng/internal/Parameters.java]: We should display a warning when `XmlTest` is used in a before suite.

But what about `XmlSuite`, `XmlClass`, ...? 
I think we can consider `ISuite`, `IClass`, ... too.

**Comment by cbeust** [comment]
Yes, and maybe remove this from the documentation since this behavior is
really not useful at all (and probably unpredictable). I can't imagine
anyone would rely on that and what they would use it for.


-- 
Cédric
