### PR TITLE
Possibility to retry a test until it FAILED

### LINKED ISSUE #1519: Possibility to retry a test until it FAILED
We need to have a possibility to run tests until test will be failed (because we have flaky tests and want to run a test until it failed and then investigate: read logs etc) 

Main problem: hardcoded FAILURE test status in condition for retry: 
```java
boolean willRetry = retryAnalyzer != null && status == ITestResult.FAILURE && failure.instances != null && retryAnalyzer.retry(testResult);
```

In old TestNG version (TestNG which bundled with IDEA) we had a chance to avoid it by the following way:

```java
class RetryUntilFailedListener : IInvokedMethodListener {
    override fun beforeInvocation(method: IInvokedMethod?, testResult: ITestResult?) { }

    override fun afterInvocation(method: IInvokedMethod?, testResult: ITestResult?) {
        if (method!!.isTestMethod) {
            if (testResult!!.status == ITestResult.SUCCESS) {
                println("SUCCESS. NEED TO RETRY")
                testResult.status = ITestResult.FAILURE //because retry works only if (testResult.getStatus() == ITestResult.FAILURE)
                testResult.setAttribute("RETRY", "YES")
            } else if (testResult.status == ITestResult.FAILURE)
                testResult.setAttribute("RETRY", "NO")
        }
    }

}
```

but now it doesn't work because in old versions  `invokeTestMethods` run `handleInvocationResults` but now it doesn't. So now I can't override test status before retry logic.

### TestNG Version
latest

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #1519 .

For a failing test following would happen:
* Inspect the exception to consider “expectedExceptions”
* Run “afterInvocations()”
* Invoke a “RetryAnalyzer” if provided.

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java [hunk 1]
```diff
@@ -34,4 +38,12 @@ public void testInvocationCounts() {
         List<ITestResult> skipped = tla.getSkippedTests();
         assertEquals(skipped.size(), InvocationCountTest.invocations.size() - fsp.size());
     }
+
+    @Test
+    public void testIfRetryIsInvokedBeforeListener() {
+        TestNG tng = create(TestClassSample.class);
+        tng.addListener((ITestNGListener)new MyListener());
+        tng.run();
+        Assertions.assertThat(TestClassSample.messages).containsExactly("afterInvocation", "retry","afterInvocation");
```
Comment (juherr) [inline src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: Typo: missing space after ","

Comment (juherr) [inline src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: Static import of assertThat

File: src/test/java/test/retryAnalyzer/github1519/TestClassSample.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
+package test.retryAnalyzer.github1519;
+
+import org.testng.Assert;
+import org.testng.annotations.Test;
+import org.testng.collections.Lists;
+
+import java.util.List;
+
+public class TestClassSample {
+    static boolean retry = false;
```
Comment (juherr) [inline src/test/java/test/retryAnalyzer/github1519/TestClassSample.java]: You can manage the retry logic here because the test assertion is done on the messages

**Review by juherr — APPROVED** [review]
Few little remarks. :+1: 
Ping @cbeust

File: src/test/java/test/retryAnalyzer/github1519/TestClassSample.java (hunk 2 above)
Comment (krmahadevan) [reply src/test/java/test/retryAnalyzer/github1519/TestClassSample.java]: This boolean is flipped by the `RetryAnalyzer`. So the first time, the test would fail, and the control would go to `RetryAnalyzer` after which the boolean gets set to `true` by it. So the next run of the `@Test` would pass. I did that to avoid having to setup an exit criteria in the `RetryAnalyzer` implementation.

File: src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java (hunk 1 above)
Comment (krmahadevan) [reply src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: fixed

Comment (krmahadevan) [reply src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: fixed

File: src/test/java/test/retryAnalyzer/github1519/TestClassSample.java (hunk 2 above)
Comment (juherr) [reply src/test/java/test/retryAnalyzer/github1519/TestClassSample.java]: Ok, it works too :)

**Comment by krmahadevan** [comment]
ping @cbeust I have addressed the merge conflicts as well. Please let me know if there is anything that is pending from my side to get this merged.
