### PR TITLE
Streamline listener invocation with config methods

### LINKED ISSUE #1602: beforeInvocation method don't get called for skipped tests
### Expected behavior
Invoked method listener `beforeInvocation` methods should be called even if the test method gets skipped.

### Actual behavior
Invoked method listener `beforeInvocation` methods aren't called for skipped tests.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
* Create a simple invoked method listener that emits a message from `beforeInvocation` and `afterInvocation` if the invoked method is a test.
* Create a test class with a @BeforeMethod configuration method that will fail
* Create a simple test method
* Run the test method

EXPECT: Both `beforeInvocation` and `afterInvocation` should emit messages
ACTUAL: Only `afterInvocation` message will appear

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1602

* Ensured that before and after invocation are triggered
for Skipped config methods
* Fixed status anomalies when ITestResult is 
passed around before/after invocation methods.
*Altered an existing test to accommodate listener
invocation for skipped config methods as well 
(since now irrespective of whether a config method
gets executed or get skipped, the listeners for it
will always be invoked)

Fixes #1602  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/Invoker.java [hunk 1]
```diff
@@ -221,7 +226,7 @@ private void invokeConfigurations(IClass testClass,
         } else {
           invokeConfigurationMethod(newInstance, tm, parameters, testResult);
         }
-
+        testResult.setStatus(ITestResult.SUCCESS);
```
Comment (juherr) [inline src/main/java/org/testng/internal/Invoker.java]: Could you check you are not overriding status from `MethodInvocationHelper`?

Comment (krmahadevan) [reply src/main/java/org/testng/internal/Invoker.java]: @juherr - No I am not overriding the status. I have checked it. Thanks to you, i realized I can actually get rid of this. So I amended the commit, reverted this changeset and push in the changes. Please check

**Review by juherr — APPROVED** [review]
