### PR TITLE
Remove IInvokedMethod references from SuiteRunner

### LINKED ISSUE #2096: 7.0.0-beta6 memory issues (regression)
A test task runs over 310,000 independent test executions. In `6.14.3` this completes in about 2.5 minutes. In `7.0.0-beta6` this slows down to a crawl at 200k tests, appearing to GC thrash as small batches of tests complete.

In the past, I've seen this occur due to reporting keeping parameters in-memory. The project uses a [workaround](https://github.com/ben-manes/caffeine/blob/c6264dad9b54eeff0193f9c6f77339d0c45f9141/caffeine/src/test/java/com/github/benmanes/caffeine/cache/testing/CacheValidationListener.java#L149-L161) to replace test parameters with their `toString` version, as these are too heavy for a large run. I suspect there is some similar per-test memory grab by the reporter.

The next step is probably to take a heap dump and determine what is held. Before running too far into this, do you know what changes were made that might hint at what to look for?

```gradle
./gradlew :caffeine:strongKeysAndStrongValuesAsyncCaffeineTest
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Instead of saving all invoked methods, now we are
resorting to computing it on a need basis.

Fixes #2096

### CODE REVIEW

File: src/main/java/org/testng/internal/TestInvoker.java [hunk 1]
```diff
@@ -573,6 +573,7 @@ private ITestResult invokeMethod(
       runInvokedMethodListeners(BEFORE_INVOCATION, invokedMethod, testResult);
 
       if (arguments.getTestMethod() instanceof IInvocationStatus) {
+        ((IInvocationStatus) arguments.getTestMethod()).setInvokedAt(invokedMethod.getDate());
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestInvoker.java:576]: Why don't you `.markAsInvoked()` here?

File: src/main/java/org/testng/IInvocationStatus.java [hunk 2]
```diff
@@ -1,8 +1,12 @@
 package org.testng;
 
 public interface IInvocationStatus {
```
Comment (juherr) [inline src/main/java/org/testng/IInvocationStatus.java:3]: Could you add some javadoc to explain what is the goal of the public interface?

File: src/main/java/org/testng/IInvocationStatus.java [hunk 3]
```diff
@@ -1,8 +1,12 @@
...
+
   void markAsInvoked();
```
Comment (juherr) [inline src/main/java/org/testng/IInvocationStatus.java:5]: Is it still useful? With invocation time we can now consider that it is invoked when a time is set, right?

File: src/main/java/org/testng/SuiteRunner.java [hunk 4]
```diff
@@ -61,7 +60,6 @@
       invokedMethodListeners;
 
   /** The list of all the methods invoked during this run */
```
Comment (juherr) [inline src/main/java/org/testng/SuiteRunner.java:62]: Remove the associated comment too.

Comment (krmahadevan) [reply src/main/java/org/testng/SuiteRunner.java:62]: Fixed

File: src/main/java/org/testng/IInvocationStatus.java (hunk 3 above)
Comment (krmahadevan) [reply src/main/java/org/testng/IInvocationStatus.java:5]: Not needed anymore. We can just manage with the invocation time.

File: src/main/java/org/testng/IInvocationStatus.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/IInvocationStatus.java:3]: Thanks for pointing this out. This wasnt meant to be a public interface. Moved it to internal package and added javadocs

File: src/main/java/org/testng/internal/TestInvoker.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestInvoker.java:576]: Got rid of that and now just use `setInvokedAt()`

**Comment by krmahadevan** [comment]
@juherr - I have fixed all the review comments. Please help take another look

**Review by juherr — APPROVED** [review]
