### PR TITLE
Problem of combination dependsOnMethods & RetryAnalyzer

### LINKED ISSUE #1538: Problem of combination dependsOnMethods and RetryAnalyzer
Hi guys,

when a test failed and passed after retry using IRetryAnalyzer implementation, all dependent tests are skipped. This seems to be a bug. Have a look at my simple example below.

### TestNG Version
latest (6.12)

### Expected behavior
1. a() failed //i==0
2. a() passed //i==1
3. b() passed //i==2

### Actual behavior
1. a() failed //i==0
2. a() passed //i==1
3. **b() skipped** // this is the problem

### Is the issue reproductible on runner?
yes
- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```java
public class Example {
    int i = 0;

    public static class Retry implements IRetryAnalyzer {
        @Override
        public boolean retry(ITestResult result) {
            return true;
        }
    }

    @Test(retryAnalyzer = Retry.class)
    public void a() {
        Assert.assertTrue(i++ == 1);
    }

    @Test(dependsOnMethods = "a", retryAnalyzer = Retry.class)
    public void b() {
        Assert.assertTrue(i++ == 2);
    }
}
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1538

Un-related change:
Updated the Invoker class to start using some
of the JDK8 features

Fixes #1538  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/Invoker.java [hunk 1]
```diff
@@ -736,7 +732,7 @@ private void invokeBeforeGroupsConfigurations(ITestNGMethod currentTestMethod,
       }
     }
 
-    ITestNGMethod[] beforeMethodsArray = filteredMethods.toArray(new ITestNGMethod[filteredMethods.size()]);
+    ITestNGMethod[] beforeMethodsArray = filteredMethods.toArray(new ITestNGMethod[0]);
```
Comment (juherr) [inline src/main/java/org/testng/internal/Invoker.java]: Why this change? It has lower performance.

File: src/test/java/test/dataprovider/DataProviderTest.java [hunk 2]
```diff
@@ -95,8 +95,7 @@ public void allMethodsShouldBeInvoked() {
   public void failedDataProviderShouldCauseSkip() {
     InvokedMethodNameListener listener = run(DependentSample.class);
 
-    assertThat(listener.getSucceedMethodNames()).containsExactly("method1(ok)");
-    assertThat(listener.getSkippedMethodNames()).containsExactly("method2");
+    assertThat(listener.getSucceedMethodNames()).containsExactly("method1(ok)", "method2");
```
Comment (juherr) [inline src/test/java/test/dataprovider/DataProviderTest.java]: Does this change expected? The sample has no retry analyzer and the `method2` should not be executed if I understand the sample well

File: src/test/java/test/retryAnalyzer/issue1538/TestClassSampleWithTestMethodDependencies.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
+package test.retryAnalyzer.issue1538;
+
+import org.testng.Assert;
+import org.testng.annotations.Test;
+
+public class TestClassSampleWithTestMethodDependencies {
+    private int i = 0;
+    @Test(retryAnalyzer = RetryForIssue1538.class)
+    public void a() {
+        Assert.assertEquals(i++,1 );
```
Comment (juherr) [inline src/test/java/test/retryAnalyzer/issue1538/TestClassSampleWithTestMethodDependencies.java]: style (spaces)

File: src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java [hunk 4]
```diff
@@ -90,6 +89,17 @@ public void testIfRetryIsInvokedWhenTestMethodHas(Class<?> clazz, int size, Map<
...
 
+    @Test(description = "GITHUB-1538")
+    public void testIfDependentMethodsAreInvokedWhenRetrySucceeds() {
+        TestNG testng = create(TestClassSampleWithTestMethodDependencies.class);
+        InvokedMethodNameListener listener = new InvokedMethodNameListener();
+        testng.addListener(listener);
+        testng.run();
+        assertThat(listener.getSucceedMethodNames()).containsExactly("a", "b");
+        assertThat(listener.getFailedMethodNames()).containsExactly("a");
+        assertThat(listener.getSkippedMethodNames()).containsExactly("a");
```
Comment (juherr) [inline src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: I wonder if the skipped methods should not be: `"b", "a", "b"`

**Review by juherr — CHANGES_REQUESTED** [review]

File: src/main/java/org/testng/internal/Invoker.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/Invoker.java]: @juherr - No not on JDK8. From what I read, this was a problem on JDK6. This part has been optimized in the newer JDKs.
As per IntelliJ documentation, working with predefined array sizes can cause data races. That is why I changed this.

File: src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java (hunk 4 above)
Comment (krmahadevan) [reply src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: I didn't quite get you there @juherr. Since there's a retry analyzer involved , the method `a()` would have an entry only in passed and skipped list (it having an entry in failed list is due to how our `InvokedMethodNameListener` is built. I got rid of using it and instead fell back to using `TestListenerAdapter`. So skipped would never have `b` in it, because `b()` passes in the very first attempt.

File: src/test/java/test/dataprovider/DataProviderTest.java (hunk 2 above)
Comment (krmahadevan) [reply src/test/java/test/dataprovider/DataProviderTest.java]: @juherr - Thanks. This was a bug in the code. I didn't realize that there was no retry involved, but it was a data provider. I have fixed this by differentiating between methods which get executed repeatedly (via a data provider or invocation count) and methods get retried.

**Comment by krmahadevan** [comment]
@juherr - I have fixed your review comments. Please  take a look.

**Comment by krmahadevan** [comment]
ping @juherr

File: src/main/java/org/testng/internal/Invoker.java (hunk 1 above)
Comment (juherr) [reply src/main/java/org/testng/internal/Invoker.java]: Ok, I've never heard about it! 👍

File: src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java (hunk 4 above)
Comment (juherr) [reply src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: My remark is maybe out of the scope of this pull request, but I'm not understanding the [maybe current] behavior:

I don't understand what is the method called flow. Could you detail it?

File: src/main/java/org/testng/internal/Invoker.java (hunk 1 above)
Comment (cbeust) [reply src/main/java/org/testng/internal/Invoker.java]: Ditto, didn't know about that. Thanks @krmahadevan!

File: src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java (hunk 4 above)
Comment (krmahadevan) [reply src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: Current behavior : 

Method `b()` has a dependency on `a()`
Method `a()` has a retry analyzer associated with it.

`a()` initially fails, and then passes eventually due to `retry analyzer`
`b()` is expected to run, but does not run, because its only considering the `skipped`/`failed` status of `a()`  and not the eventual `pass` status.

I fixed this, by having TestNG check if `a()` also had a `pass` and if yes, allow it to run `b()`

Please let me know if that adds clarity @juherr

Comment (juherr) [reply src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java]: But what is the flow?
Is it: `a` (failed/skip), `a` (pass), `b` (pass)? 
=> the `a` from failed or skipped method should be removed.

IMO, a more natural flow could be:
`a` (failed/skip), `b` (skip), `a` (pass), `b` (pass).

**Comment by krmahadevan** [comment]
@juherr,
The current Flow (without bug fix) : a(skipped/failed) => a(passed) =>
b(skipped)
Flow (with bug fix) : a(skipped/failed) => a(passed) => b(passed)


The flow that you are suggesting : a (failed/skip), b (skip), a (pass), b
(pass).

will start having methods with the attribute "dependsOnMethods" start
behaving as if it was driven by either invocationCount (or) data driven.
That also will break backward compatibility, since its changing
functionality. At-least that my opinion. Also I think b() should not be
skipped and then executed() because its not directly associated with a
retry analyzer. It getting that behavior via a parent method on which it
depends on, to me seems counter intuitive.

**Comment by juherr** [comment]
Ok! I'm fine if both statuses skipped and failed are expected for "a".

**Review by juherr — APPROVED** [review]

**Comment by krmahadevan** [comment]
@cbeust - Can you please help merge this ?

**Comment by qwikso** [comment]
@krmahadevan @juherr @cbeust 
Great work! I've tested the snapshot and all scenarios are working properly now. Guys, when are you going to release out 7.0.0 version? It's question of days, weeks or months?
Q.

**Comment by juherr** [comment]
> Guys, when are you going to release out 7.0.0 version? It's question of days, weeks or months?

Months, but we can release some beta versions if needed.

**Comment by qwikso** [comment]
That's would be nice. This pull request solves many problems with retrying in our tests so we are pushed to use it as a snapshot. We need to have it deployed to maven central repository as a release. So if you are ok with beta, let's go! At least we can report identified issues;)
