### PR TITLE
Fix and unit tests for issue 1297 - Passed configuration methods appear in testng-failed.xml, when failure was after passed test

### LINKED ISSUE #1297: testng-failed.xml includes setup and tearDown (before and after annotations) of passed tests
### TestNG Version
6.10

### Expected behavior
testng-failed.xml should only include before and after annotation and `@test` of failed test class

### Actual behavior
testng-failed.xml includes setup and tearDown (before and after annotations) of passed tests

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
public class FailedReporterTest1 {
	@BeforeTest
	public void setup() {
	}
	@Test
	public void newTest1() {
		System.out.println("In the first test.....");
	}
	@AfterTest
	public void tearDown() {
		System.out.println("Done...1");
	}
}
```

```java
public class FailedReporterTest2 {

	@BeforeTest
	public void setup() {
	}
	@Test
	public void newTest2() {
		System.out.println("In the second test.....");
		Assert.fail();
	}
	@AfterTest
	public void tearDown() {
		System.out.println("Done...2");
	}

}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="failedReporterTestSuite">
	<test name="failedReporterTest">
		<classes>
			<class name="com.testng.playground.tests.FailedReporterTest1" />
			<class name="com.testng.playground.tests.FailedReporterTest2" />
		</classes>
	</test>
</suite>
```

**Generated testng-failed.xml :** 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" name="Failed suite [failedReporterTestSuite]">
  <test name="failedReporterTest(failed)">
    <classes>
      <class name="com.testng.playground.tests.FailedReporterTest1">
        <methods>
          <include name="tearDown"/>
          <include name="setup"/>
        </methods>
      </class> <!-- com.testng.playground.tests.FailedReporterTest1 -->
      <class name="com.testng.playground.tests.FailedReporterTest2">
        <methods>
          <include name="setup"/>
          <include name="newTest2"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- com.testng.playground.tests.FailedReporterTest2 -->
    </classes>
  </test> <!-- failedReporterTest(failed) -->
</suite> <!-- Failed suite [failedReporterTestSuite] -->
```

### PR DESCRIPTION
**Pull request by dsankouski**
Fixes #1297.

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

### CODE REVIEW

**Comment by juherr** [comment]
In order to all cover the feature, could you add more test cases from https://github.com/cbeust/testng/issues/1297#issuecomment-892673297 ?

**Comment by dsankouski** [comment]
Yes, I'll add those

**Comment by juherr** [comment]
@krmahadevan Do you think it is covering all cases of the feature?

@dsankouski Feel free to propose a fix ;)

**Comment by dsankouski** [comment]
@juherr , I feel I found [another issue](https://stackoverflow.com/questions/9312513/method-depends-on-nonexistent-group-testng), affecting those tests, so I'll do fix after more tests.

**Comment by dsankouski** [comment]
@juherr , @krmahadevan  guys, please have a look

File: testng-core/src/test/java/test/failedreporter/FailedReporterTest.java [hunk 1]
```diff
@@ -67,38 +73,108 @@ public void testExclusionOfPassedConfigsAmidstInheritance() {
...
+          "newTest2", "baseBeforeTest", "baseAfterClass", "baseBeforeClass", "baseBeforeMethod"
+        };
+    runAssertions(mTempDirectory, substitutions, "<include name=\"%s\"/>", 1);
+  }
+
   @Test(description = "github-1297")
   public void testExclusionOfPassedConfigsInvolvingGroupsAtTestLevel() {
-    triggerTest(GroupsSampleBase.class.getPackage().getName(), true);
-    String[] substitutions = new String[] {GroupsPassSample.class.getName()};
+    triggerTest(GroupsSampleBase.class.getPackage().getName(), true, "run");
```
Comment (juherr) [inline testng-core/src/test/java/test/failedreporter/FailedReporterTest.java:90]: `DEPENDENT_GROUP` instead of `"run"`

File: testng-core/src/test/java/test/failedreporter/FailedReporterTest.java [hunk 2]
```diff
@@ -67,38 +73,108 @@ public void testExclusionOfPassedConfigsAmidstInheritance() {
...
     runAssertions(mTempDirectory, substitutions, "<include name=\"%s\"/>", 1);
   }
 
   @Test(description = "github-1297")
   public void testExclusionOfPassedConfigsInvolvingGroupsAtSuiteLevel() {
-    triggerTest(GroupsSampleBase.class.getPackage().getName(), false);
-    String[] substitutions = new String[] {GroupsPassSample.class.getName()};
+    triggerTest(GroupsSampleBase.class.getPackage().getName(), false, "run");
+    String[] substitutions =
+        new String[] {GroupsPassSample.class.getName(), GroupsSampleBase.class.getName()};
```
Comment (juherr) [inline testng-core/src/test/java/test/failedreporter/FailedReporterTest.java:102]: Could you explain this change? Why do you add `GroupsSampleBase`?

Comment (dsankouski) [reply testng-core/src/test/java/test/failedreporter/FailedReporterTest.java:102]: We're testing `ExclusionOfPassedConfigsInvolvingGroupsAtSuiteLevel` here, and there's no failed config methods in `GroupsSampleBase` class. Also, `GroupsFailureSample` has all config methods inherited from base class. Thus `GroupsSampleBase` class shouldn't be included in rerun report.

File: testng-core/src/test/java/test/failedreporter/FailedReporterTest.java (hunk 1 above)
Comment (dsankouski) [reply testng-core/src/test/java/test/failedreporter/FailedReporterTest.java]: done

**Review by juherr — APPROVED** [review]

**Comment by juherr** [comment]
@dsankouski Please resolve the merge conflict

@krmahadevan LGTM, could you have a look at it too?

**Review by krmahadevan — APPROVED** [review]
