### PR TITLE
Fixed NPE when suite does not contain started tests.

### LINKED ISSUE #1931: [NPE] Reporter org.testng.reporters.jq.Main failed
### TestNG Version
7.0.0-beta1
Test class contains a single test method with executionCount = 0

### Expected behavior
NPE missing

### Actual behavior
```
Total tests >>>> 5
===============================================
DEFAULT TIGRA API suite
Total tests run: 4, Passes: 4, Failures: 0, Skips: 0
===============================================

[TestNG] Reporter org.testng.reporters.jq.Main@2892d68 failed
java.lang.NullPointerException
	at org.testng.reporters.jq.TimesPanel.maxTime(TimesPanel.java:124)
	at org.testng.reporters.jq.TimesPanel.getContent(TimesPanel.java:89)
	at org.testng.reporters.jq.BaseMultiSuitePanel.generate(BaseMultiSuitePanel.java:25)
	at org.testng.reporters.jq.Main.generateReport(Main.java:74)
	at org.testng.TestNG.generateReports(TestNG.java:1027)
	at org.testng.TestNG.run(TestNG.java:970)
	at org.touchbit.buggy.core.Buggy.run(Buggy.java:138)
	at org.touchbit.buggy.core.Buggy.main(Buggy.java:78)
	at com.ibclabs.aqa.latex.integration.ILatex.main(ILatex.java:9)

```
### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans
- [x] Jar

### PR DESCRIPTION
**Pull request by shaburov**
The error of converting a Long object to a long primitive if the Map does not contain an object.
Fixes #1931
Closes #1931

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

Fix bugs in TestNG

### CODE REVIEW

**Comment by shaburov** [comment]
@juherr  review please.

File: src/test/java/org/testng/reporters/jq/TimesPanelTest.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+import org.testng.xml.XmlTest;
+
+import java.util.ArrayList;
+import java.util.List;
+
+import static org.hamcrest.CoreMatchers.containsString;
+import static org.hamcrest.MatcherAssert.assertThat;
+
+/**
+ * Created by Oleg Shaburov on 28.10.2018
```
Comment (juherr) [inline src/test/java/org/testng/reporters/jq/TimesPanelTest.java]: Please, remove. We don't use such kind of comments.

File: src/test/java/org/testng/reporters/jq/TimesPanelTest.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+ * shaburov.o.a@gmail.com
+ */
+public class TimesPanelTest {
+
+    private static final String GITHUB_1931 = "GITHUB-1931 [NPE] TimesPanel.maxTime(ISuite suite)";
+
+    @Test(description = GITHUB_1931)
+    public void generateReportTimesPanelContentForSuiteWithoutStartedTests() {
+        XmlSuite xmlSuite = new XmlSuite();
```
Comment (juherr) [inline src/test/java/org/testng/reporters/jq/TimesPanelTest.java]: If you extends SimpleBaseTest, you'll find some util methods for xml objects creation.

File: src/test/java/org/testng/reporters/jq/TimesPanelTest.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+import org.testng.reporters.XMLStringBuffer;
+import org.testng.xml.XmlClass;
+import org.testng.xml.XmlSuite;
+import org.testng.xml.XmlTest;
+
+import java.util.ArrayList;
+import java.util.List;
+
+import static org.hamcrest.CoreMatchers.containsString;
+import static org.hamcrest.MatcherAssert.assertThat;
```
Comment (juherr) [inline src/test/java/org/testng/reporters/jq/TimesPanelTest.java]: We don't use assertions from hamcrest but the TestNG ones or from AssertJ.

**Review by juherr — COMMENTED** [review]
Just some style remarks.

File: CHANGES.txt [hunk 4]
```diff
@@ -1,4 +1,5 @@
 Current
+Fixed: GITHUB-1931: [NPE] Reporter org.testng.reporters.jq.Main failed (Oleg Shaburov)
```
Comment (juherr) [inline CHANGES.txt]: Maybe you can just add your name 2 lines below

**Review by juherr — APPROVED** [review]
