### PR TITLE
Fix Files.copy() such that parent dirs are created

### LINKED ISSUE #2761: Exception: ERROR java.nio.file.NoSuchFileException: /tmp/testngXmlPathInJar-15086412835569336174
### TestNG Version
7.6.0

I have some bad news with last release 7.6.0, We tested a snapshot last week from master and that was working. But there seems to be a new commit in-between that affects us badly. non of the executions passed.

I expect it is related to this commit: [d190ade](https://github.com/cbeust/testng/commit/d190ade58a58e20ced922d47a9114958a5a05e8a)

Seems that some tmp path is added infront of the path

argument: -xmlpathinjar suites/postrelease/emulator_wrat_postrelease.xml

Exception: 2022-05-18T08:44:26,315 ERROR java.nio.file.NoSuchFileException: /tmp/testngXmlPathInJar-15086412835569336174/suites/old_action_test_suites/rnc_action_regression_with_configurationdata.xml

### Sample Test
```
package org.testng.sample;
import org.testng.annotations.Test;
public class XmlPathInJarTest {
		@Test
		public void test() {
			System.out.println("Test");
		}
}
```

### Sample Suite
```
<suite name="MJE PostRelease test on G2Rbs" verbose="1">
    <test name="XmlPathInJarTest" preserve-order="true">
        <classes>
            <class name="org.testng.sample.XmlPathInJarTest" />
        </classes>
    </test>
</suite>
```

### Command
java -classpath target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.testng.TestNG -testjar target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar -xmlpathinjar suites/xmlpathinjarSuite.xml

### TestNG 7.5 Output
```
Test

===============================================
MJE PostRelease test on G2Rbs
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================
```

### TestNg 7.6.0 Output
```
bash-3.2$ java -classpath target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.testng.TestNG -testjar target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar -xmlpathinjar suites/xmlpathinjarSuite.xml
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
13:10:47.078 [main] ERROR org.testng.TestNG - java.nio.file.NoSuchFileException: /var/folders/3l/qqzzwt655k16_hjq1gk_grl40000gp/T/testngXmlPathInJar-16857375091475056093/META-INF/maven/com.google.code.findbugs/jsr305/pom.xml
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2761

Also toggled the version back to a bug fix version

Fixes #2761  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

File: gradle.properties [hunk 1]
```diff
@@ -5,7 +5,7 @@ kotlin.code.style=official
 # Note: testng.kotlin-library.gradle.kts adds kotlin-stdlib for testImplementation
 kotlin.stdlib.default.dependency=false
 
-testng.version=7.7.0
+testng.version=7.6.1
```
Comment (juherr) [inline gradle.properties:8]: Why not the latest version or the next one?

File: testng-core/src/test/java/testhelper/JarCreator.java [hunk 2]
```diff
@@ -1,4 +1,4 @@
-package org.testng.jarfileutils;
+package testhelper;
```
Comment (juherr) [inline testng-core/src/test/java/testhelper/JarCreator.java:1]: What was the issue with the previous package?

File: testng-core/src/test/java/testhelper/TestClassGenerator.java [hunk 3]
```diff
@@ -0,0 +1,39 @@
+package testhelper;
```
Comment (juherr) [inline testng-core/src/test/java/testhelper/TestClassGenerator.java:1]: Please, use full package name (org.testng) for new classes

File: gradle.properties (hunk 1 above)
Comment (krmahadevan) [reply gradle.properties:8]: The last released version was `7.6.0`. Am guessing that this qualifies to be a bugfix release. Hence the version as `7.6.1`

`7.7.0` - Will be the version for the next release (I have already moved the milestones etc., Dont want to go through that ritual once again)

File: testng-core/src/test/java/testhelper/JarCreator.java (hunk 2 above)
Comment (krmahadevan) [reply testng-core/src/test/java/testhelper/JarCreator.java:1]: I found that some of the helpers resided here and some there. Just trying to unify all these helpers in one place so that they are easy to find ( I had to search through the code to find them 😄 )

File: testng-core/src/test/java/testhelper/TestClassGenerator.java (hunk 3 above)
Comment (krmahadevan) [reply testng-core/src/test/java/testhelper/TestClassGenerator.java:1]: I can refactor this package name to `org.testng.testhelper`. Is that what you are hinting at ?

File: testng-core/src/main/java/org/testng/JarFileUtils.java [hunk 4]
```diff
@@ -76,6 +76,10 @@ private boolean testngXmlExistsInJar(File jarFile, List<String> classes) throws
         if (Parser.canParse(jeName.toLowerCase())) {
           InputStream inputStream = jf.getInputStream(je);
           File copyFile = new File(file, jeName);
+          File parent = copyFile.getParentFile();
+          if (!parent.exists()) {
```
Comment (martinaldrin) [inline testng-core/src/main/java/org/testng/JarFileUtils.java:80]: Hi, I think my solution is better. mkdirs already check if directory exists so there is no need to check it. 
file.mkdirs()

File: testng-core/src/main/java/org/testng/JarFileUtils.java [hunk 5]
```diff
@@ -76,6 +76,10 @@ private boolean testngXmlExistsInJar(File jarFile, List<String> classes) throws
         if (Parser.canParse(jeName.toLowerCase())) {
           InputStream inputStream = jf.getInputStream(je);
           File copyFile = new File(file, jeName);
```
Comment (martinaldrin) [inline testng-core/src/main/java/org/testng/JarFileUtils.java:78]: put file.mkdirs(); here instead

File: testng-core/src/main/java/org/testng/reporters/jq/Main.java [hunk 6]
```diff
@@ -90,7 +90,12 @@ public void generateReport(
             if (is == null) {
               throw new AssertionError("Couldn't find resource: " + fileName);
             }
-            java.nio.file.Files.copy(is, new File(outputDirectory, fileName).toPath());
+            File fileToCopy = new File(outputDirectory, fileName);
+            File parentDir = fileToCopy.getParentFile();
+            if (!parentDir.exists()) {
```
Comment (martinaldrin) [inline testng-core/src/main/java/org/testng/reporters/jq/Main.java:95]: No need to check if dir exists.

**Review by martinaldrin — CHANGES_REQUESTED** [review]

File: testng-core/src/main/java/org/testng/JarFileUtils.java (hunk 4 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/JarFileUtils.java]: Fixed

File: testng-core/src/main/java/org/testng/reporters/jq/Main.java (hunk 6 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/reporters/jq/Main.java]: Fixed

File: testng-core/src/main/java/org/testng/JarFileUtils.java (hunk 5 above)
Comment (krmahadevan) [reply testng-core/src/main/java/org/testng/JarFileUtils.java:78]: Fixed

File: testng-core/src/test/java/testhelper/JarCreator.java (hunk 2 above)
Comment (martinaldrin) [reply testng-core/src/test/java/testhelper/JarCreator.java:1]: Feels wrong to not have all code under package org.testng.x
wouldn't it be better to but them directly under org.testng or org.testng.testhelper?

File: gradle.properties (hunk 1 above)
Comment (martinaldrin) [reply gradle.properties:8]: It would be nice if we release 7.6.x during this year and maybe once per year lift the major version to allow smaller releases from time to time.

File: testng-core/src/test/java/testhelper/TestClassGenerator.java (hunk 3 above)
Comment (juherr) [reply testng-core/src/test/java/testhelper/TestClassGenerator.java:1]: Yes, please :)

File: testng-core/src/test/java/testhelper/JarCreator.java (hunk 2 above)
Comment (krmahadevan) [reply testng-core/src/test/java/testhelper/JarCreator.java]: @juherr fixed

File: testng-core/src/test/java/testhelper/TestClassGenerator.java (hunk 3 above)
Comment (krmahadevan) [reply testng-core/src/test/java/testhelper/TestClassGenerator.java]: @juherr fixed

**Review by martinaldrin — APPROVED** [review]

**Review by juherr — APPROVED** [review]
