### PR TITLE
GitHub 2913

### LINKED ISSUE #2913: Maps containing nulls can be incorrectly considered equal
All known (confirmed in 7.3.0 and in master branch as at 25 May 2023)

### Expected behavior

If two maps contain different keys, they should never be reported as equal.

### Actual behavior

If two maps contain different keys, if the values for all such keys in the LHS map are null, they *are* reported as equal.

### Is the issue reproducible on runner?

Everywhere I believe.

```
    Map<String,Object> map1 = new LinkedHashMap<>();
    map1.put("a", 1);
    map1.put("b", null);
    Map<String,Object> map2 = new LinkedHashMap<>();
    map2.put("a", 1);
    map2.put("c", null);

    Assert.assertEquals(map1, map2);
```

The above assertion passes, but clearly it shouldn't.

### Contribution guidelines

> Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

I will open a fix shortly.

### PR DESCRIPTION
**Pull request by ahgittin**
Fixes #2913  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

### CODE REVIEW

**Comment by ahgittin** [comment]
Test case `checkMapNotEqualsWithNull` added failing in 7a4394b00af74e878035016a70311ba3300094c2 passing once fixed applied in 4216a3d7a3d64e605a8a570c9e5dbaf7eea1b3db .

File: testng-asserts/src/test/java/test/asserttests/AssertTest.java [hunk 1]
```diff
@@ -563,4 +563,92 @@ public void checkArrayNotEqualsFailsWhenDifferentOrder() {
...
+
+    boolean succeeded = false;
+    try {
+      assertNotEquals((Object) m1, (Object) m2);
+      succeeded = true;
+    } catch (AssertionError e) {
+      /* expected */
+    }
+    if (succeeded) {
+      Assert.fail("Maps reported as not equal when equal: " + m1 + " / " + m2);
```
Comment (juherr) [inline testng-asserts/src/test/java/test/asserttests/AssertTest.java:615]: Could be replaced but assertFalse

**Review by juherr — CHANGES_REQUESTED** [review]

File: testng-asserts/src/test/java/test/asserttests/AssertTest.java [hunk 2]
```diff
@@ -563,4 +563,92 @@ public void checkArrayNotEqualsFailsWhenDifferentOrder() {
...
+
+    assertMapsNotEqual(map1, map2);
+  }
+
+  protected void assertMapsEqual(Map m1, Map m2) {
+    assertEquals((Object) m1, (Object) m2);
+    assertEquals(m1, m2);
+
+    boolean succeeded = false;
+    try {
```
Comment (krmahadevan) [inline testng-asserts/src/test/java/test/asserttests/AssertTest.java:608]: can we refactor this to 

```
try {
     assertNotEquals((Object) m1, (Object) m2);
    Assert.fail("Maps reported as not equal when equal: " + m1 + " / " + m2);
} catch (AssertionError ignored) {}
```
This will do away with the extra variable `succeeded`

File: CHANGES.txt [hunk 3]
```diff
@@ -1,5 +1,7 @@
 Current
 
+Fixed: GITHUB-2913: Maps containing nulls can be incorrectly considered equal
```
Comment (krmahadevan) [inline CHANGES.txt:3]: @ahgittin It would be good if you could please help add your ID/name at the end of this line, so that we can call out your contribution in the release notes of this version (when it goes out). Its our small way of thanking you for helping TestNG become better.

File: testng-asserts/src/test/java/test/asserttests/AssertTest.java (hunk 2 above)
Comment (ahgittin) [reply testng-asserts/src/test/java/test/asserttests/AssertTest.java:608]: I like the var name instead of the comment -- I've called it `expected`.

However putting the `Assert.fail` call inside the `try` will cause the `AssertionError` that _it_ throws to be ignored, won't it?, and that defeats the point of the test.  I don't know of a simple way to avoid the ugly `succeeded`, apart from introducing lambdas or splitting up the test and using `expectedExceptions` or checking the body of the failure message -- all of which I think are worse.  (But I don't feel at strongly and this is your codebase so LMK if you prefer something different!)

Comment (ahgittin) [reply testng-asserts/src/test/java/test/asserttests/AssertTest.java:608]: (gradle insists on putting a newline between the `{}` but it saves a bit of bloat)

**Comment by ahgittin** [comment]
All applied - TY

File: testng-asserts/src/test/java/test/asserttests/AssertTest.java (hunk 2 above)
Comment (juherr) [reply testng-asserts/src/test/java/test/asserttests/AssertTest.java:608]: You can try `{} //`

Comment (krmahadevan) [reply testng-asserts/src/test/java/test/asserttests/AssertTest.java:608]: @ahgittin - Sigh! my bad. Yes you are correct.

**Review by krmahadevan — APPROVED** [review]

**Review by juherr — APPROVED** [review]
