### PR TITLE
Exception in DataProvider doesn't fail test run

### LINKED ISSUE #217: exception in DataProvider doesn't fail test run
If my @DataProvider method throws an exception, the TestNG report correctly shows that exception. However, the exit status from TestNG execution is zero, indicating that all tests passed. If a DataProvider fails, the build should fail as well.

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #217

Following is the gist of changes done:
* Deprecated the nested ExitCodeListener and added a new one.
* Added null checks to ensure that an ITestResult object created based on a Description object is not
null. Description Object is typically seen to be null when JUnit encounters problems in parsing a method  as a test method.
* The new ExitCodeListener now considers pass/fail/skip methods through-out the entire suite of suites to determine the effective return code (or) status. So altered some tests to now assert on the new status
* Removed an invalid JUnit @Test (annotation on a  static method is not valid in JUnit world)
* Since new ExitCodeListener is a reporter backed listener, altered a test that asserts on the reporter count. (UniqueReporterInjectionTest.java)

Fixes #217.

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/ExitCodeListener.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+import org.testng.ISuiteResult;
+import org.testng.ITestContext;
+import org.testng.ITestListener;
+import org.testng.ITestResult;
+import org.testng.xml.XmlSuite;
+
+import java.util.BitSet;
+import java.util.List;
+
+public class ExitCodeListener implements ITestListener, IReporter {
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCodeListener.java]: Is it possible to not implement a reporter for that and have only one or more listeners?

File: src/main/java/org/testng/internal/ExitCodeListener.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+
+            }
+        }
+        status = convert(initial);
+    }
+
+    private static int convert(BitSet set) {
+        int size = set.length() - 1;
+        int value = 0;
+        for (int i= size;i >=0;i--) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCodeListener.java]: typo: space missing after `;`

File: src/main/java/org/testng/internal/ExitCodeListener.java [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+                prefix = 1;
+            }
+            value += Math.pow(2, i) * prefix;
+        }
+        return transform(value);
+    }
+
+
+    private static int transform(int value) {
+        if (value ==0 || value == 1) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCodeListener.java]: Typo: space missing after `==`

File: src/main/java/org/testng/junit/JUnit4TestRunner.java [hunk 4]
```diff
@@ -222,6 +227,16 @@ private void  runAfterInvocationListeners(ITestResult tr) {
                 l.afterInvocation(im, tr);
             }
         }
+
+        private void validate(ITestResult tr, Description description) {
```
Comment (juherr) [inline src/main/java/org/testng/junit/JUnit4TestRunner.java]: can be static

File: src/main/java/org/testng/junit/JUnit4TestRunner.java [hunk 5]
```diff
@@ -222,6 +227,16 @@ private void  runAfterInvocationListeners(ITestResult tr) {
...
+            if (tr == null) {
+                throw new TestNGException(stringify(description));
+            }
+        }
+
+        private String stringify(Description description) {
```
Comment (juherr) [inline src/main/java/org/testng/junit/JUnit4TestRunner.java]: can be static

File: src/test/java/test/github1405/JUnitTestClassSample.java [hunk 6]
```diff
@@ -5,8 +5,4 @@
 public class JUnitTestClassSample {
     @Test
     public void testMethod() {}
-    @Test
-    public static void main(String[] args) {
```
Comment (juherr) [inline src/test/java/test/github1405/JUnitTestClassSample.java]: You must not remove the main method because it is part of the test case. Check #1405.

File: src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java [hunk 7]
```diff
@@ -18,9 +18,9 @@ public void testMethod(Class<?> clazz, int expectedStatus) {
     @DataProvider
     public Object[][] getData() {
         return new Object[][]{
-                {TestClassWithConfigFailureSample.class, 3},
-                {TestClassWithConfigSkipSample.class, 2},
-                {TestClassWithConfigSkipAndFailureSample.class, 3},
+                {TestClassWithConfigFailureSample.class, 6},
```
Comment (juherr) [inline src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java]: Why do you need to change the values?

`TestClassWithConfigSkipAndFailureSample` was 3 => `HAS_SKIPPED + HAS_FAILURE` and is now 6 => `HAS_SKIPPED + HAS_FSP`. Is it expected?

File: src/test/java/test/retryAnalyzer/ExitCodeTest.java [hunk 8]
```diff
@@ -25,7 +26,23 @@ public void exitsWithNonzeroOnFailure() {
...
+    tng.addListener((ITestNGListener) new TestResultPruner());
     tng.run();
     assertEquals(tng.getStatus(), 0);
   }
+
+  @Test(description = "GITHUB-217")
+  public void exitWithNonzeroOnSkips() {
+    TestNG tng = create(Issue217TestClassSample.class);
+    tng.run();
+    assertEquals(tng.getStatus(), 5);
```
Comment (juherr) [inline src/test/java/test/retryAnalyzer/ExitCodeTest.java]: 5 means HAS_FAILURE and HAS_FSP, right?

Comment (juherr) [reply src/test/java/test/retryAnalyzer/ExitCodeTest.java]: Because `tng. hasFailureWithinSuccessPercentage()` and `tng. hasFailure()` will be both `true`.

**Review by juherr — CHANGES_REQUESTED** [review]
I think it is not yet good.

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: Why do you ask? I chose the reporter path, because that would allow people to prune through their failed/skipped tests and remove the ones that shouldn't be there (typically done when working with a retry analyzer). In those cases, the status of the test would not 0, if we did this via any other listener.

File: src/main/java/org/testng/junit/JUnit4TestRunner.java (hunk 4 above)
Comment (krmahadevan) [reply src/main/java/org/testng/junit/JUnit4TestRunner.java]: Inner class methods cannot be static.

File: src/main/java/org/testng/junit/JUnit4TestRunner.java (hunk 5 above)
Comment (krmahadevan) [reply src/main/java/org/testng/junit/JUnit4TestRunner.java]: Inner class methods cannot be static.

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 1 above)
Comment (juherr) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: Because of #584. But I didn't realize the retry analyzer effect :/

File: src/main/java/org/testng/junit/JUnit4TestRunner.java (hunk 4 above)
Comment (juherr) [reply src/main/java/org/testng/junit/JUnit4TestRunner.java]: Ok, I didn't know

File: src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java (hunk 7 above)
Comment (krmahadevan) [reply src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java]: The logic is now different. The below table should summarize it.

| Skipped Bit | Failed Bit | Success Bit | Actual Value | Remarks                          |
|-------------|------------|-------------|--------------|----------------------------------|
| 0           | 0          | 1           | 1            | Test contains only success tests |
| 0           | 1          | 0           | 2            | Test contains only failures      |
| 1           | 0          | 0           | 4            | Only skipped tests               |
| 0           | 1          | 1           | 3            | Passed + Failed tests            |
| 1           | 0          | 1           | 5            | Passed + Skipped tests           |
| 1           | 1          | 1           | 7            | Passed + Failed + Skipped tests  |

Comment (juherr) [reply src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java]: In that case, you assume the api changes and you need to remove current constants and modify `hasXxx` methods.

File: src/test/java/test/github1405/JUnitTestClassSample.java (hunk 6 above)
Comment (krmahadevan) [reply src/test/java/test/github1405/JUnitTestClassSample.java]: #1405 is not related to this. That issue talks about `main()` method and `@Test` TestNG annotation. We shouldn't have added that test for JUnit. Because of the improper status, we were always getting a 0. Only when I was debugging this issue, I got to know about the exception. JUnit doesn't even move forward but crashes with an initialization error. For some reason that doesn't properly bubble up as well. This issue also causes statements such as below

```java
ITestResult tr = m_findedMethods.get(description);
```
to return `null` values for `ITestResult` (That explains why I had to add null checks as well in this delivery to ensure that we don't land in those kind of situations)

Currently a user can never annotate a `main()` method with `@Test` JUnit annotation. It will (unlike TestNG) fail with the below error

```
java.lang.Exception: Method main() should not be static
java.lang.Exception: Method main should have no parameters
```

Here's the full stack trace 

```
java.lang.Exception: Method main() should not be static

	at org.junit.runners.model.FrameworkMethod.validatePublicVoid(FrameworkMethod.java:93)
	at org.junit.runners.model.FrameworkMethod.validatePublicVoidNoArg(FrameworkMethod.java:74)
	at org.junit.runners.ParentRunner.validatePublicVoidNoArgMethods(ParentRunner.java:155)
	at org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(BlockJUnit4ClassRunner.java:208)
	at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:188)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


java.lang.Exception: Method main should have no parameters

	at org.junit.runners.model.FrameworkMethod.validatePublicVoidNoArg(FrameworkMethod.java:76)
	at org.junit.runners.ParentRunner.validatePublicVoidNoArgMethods(ParentRunner.java:155)
	at org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(BlockJUnit4ClassRunner.java:208)
	at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:188)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255

```

File: src/test/java/test/retryAnalyzer/ExitCodeTest.java (hunk 8 above)
Comment (krmahadevan) [reply src/test/java/test/retryAnalyzer/ExitCodeTest.java]: Please see this table : https://github.com/cbeust/testng/pull/1579#discussion_r145679187

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: Ah ok! So you are saying that there can be a situation wherein a person might remove off the mandatory reporters. Understood. But this new listener doesn't care about the boolean `m_useDefaultListeners`. It gets added all the time.

Here's the snippet.
```java
private void initializeDefaultListeners() {
  this.m_exitCode = new org.testng.internal.ExitCodeListener();
  addListener((ITestNGListener) this.m_exitCode);
  if (m_useDefaultListeners) {
    addReporter(SuiteHTMLReporter.class);
    addReporter(Main.class);
    addReporter(FailedReporter.class);
    addReporter(XMLReporter.class);
    if (System.getProperty("oldTestngEmailableReporter") != null) {
      addReporter(EmailableReporter.class);
    } else if (System.getProperty("noEmailableReporter") == null) {
      addReporter(EmailableReporter2.class);
    }
    addReporter(JUnitReportReporter.class);
    if (m_verbose != null && m_verbose > 4) {
      addListener(new VerboseReporter("[TestNG] "));
    }
  }
}
```

File: src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java (hunk 7 above)
Comment (krmahadevan) [reply src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java]: Sure I will fix it.

File: src/main/java/org/testng/junit/JUnit4TestRunner.java (hunk 4 above)
Comment (krmahadevan) [reply src/main/java/org/testng/junit/JUnit4TestRunner.java]: I also didn't know that until IntelliJ complained :)

File: src/test/java/test/github1405/JUnitTestClassSample.java (hunk 6 above)
Comment (juherr) [reply src/test/java/test/github1405/JUnitTestClassSample.java]: Ok, it makes sense 👍

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 1 above)
Comment (juherr) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: If we want to fix #584, one option is to be able to remove all reporters. If the core business code uses reporters, we will be stuck to go in that way.

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: Fixed.

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 3 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: Fixed.

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: @juherr - IMO `ExitCodeListener` shouldn't fall into this list, because it doesn't cause of any delays. It only works on the sizes of passed/failed/skipped tests per `ITestContext`. But the other `IReporter` implementations can perhaps cause this.

**Comment by krmahadevan** [comment]
ping @juherr - I have addressed the review comments. Please help take a look.

File: src/main/java/org/testng/TestNG.java [hunk 9]
```diff
@@ -215,7 +214,7 @@ public int getStatus() {
   }
 
   private void setStatus(int status) {
-    m_status |= status;
+    m_status = status;
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: I think we can remove `m_status` and use `m_exitCode.getStatus()` instead.

File: src/main/java/org/testng/internal/ExitCode.java [hunk 10]
```diff
@@ -0,0 +1,148 @@
...
+            case PASSED_FAILED:
+            case SKIPPED_FAILED:
+            case SKIPPED_FAILED_PASSED:
+                return true;
+            default:
+                return false;
+        }
+    }
+
+    private BitSet initial = new BitSet(4);
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCode.java]: could be final

File: src/main/java/org/testng/internal/ExitCodeListener.java [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+
+public class ExitCodeListener implements ITestListener, IReporter {
+    private boolean hasTests = false;
+    private int status;
+
+    public int getStatus() {
+        return status;
+    }
+
+    public boolean isHasTests() {
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCodeListener.java]: just `hasTests()`?

File: src/main/java/org/testng/internal/ExitCode.java (hunk 10 above)
Comment (juherr) [reply src/main/java/org/testng/internal/ExitCode.java]: WDYT if `ExitCode` has status methods? It will be really easy to implement with the bitset and no need to have enum.

File: src/main/java/org/testng/internal/ExitCode.java [hunk 12]
```diff
@@ -0,0 +1,148 @@
...
+                (context.getSkippedConfigurations().size() != 0);
+        initial.set(2, skipped);
+        boolean failedWithinSuccessPercentage = (context.getFailedButWithinSuccessPercentageTests().size() != 0);
+        initial.set(3, failedWithinSuccessPercentage);
+    }
+
+    int getExitCode() {
+        int size = initial.length() - 1;
+        int value = 0;
+        for (int i = size; i >= 0; i--) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCode.java]: this implementation looks easier: https://stackoverflow.com/a/4874090/4234729

File: src/main/java/org/testng/internal/ExitCodeListener.java [hunk 13]
```diff
@@ -0,0 +1,71 @@
...
+import org.testng.xml.XmlSuite;
+
+import java.util.List;
+
+public class ExitCodeListener implements ITestListener, IReporter {
+    private boolean hasTests = false;
+    private int status;
+
+    public int getStatus() {
+        return status;
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCodeListener.java]: you may return the `ExitCode` instead

File: src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java (hunk 7 above)
Comment (juherr) [reply src/test/java/test/cli/github1517/ExitCodeListenerBehaviorTest.java]: In fact, we can still keep the previous behavior if we remove the success bit.

**Review by juherr — CHANGES_REQUESTED** [review]

File: src/main/java/org/testng/internal/ExitCode.java (hunk 12 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCode.java]: I did see it. But I wasn't comfortable adopting it, because I didn't understand what the code was doing. I think the last line viz., `result &= Integer.MAX_VALUE;` is not required. I will go ahead and adopt it.

**Comment by krmahadevan** [comment]
@juherr - Thanks for helping with that feedback. I have addressed all of it and pushed it back after amending the commit. Please help take a look and let me know if its fine.

File: src/main/java/org/testng/TestNG.java [hunk 14]
```diff
@@ -142,14 +143,10 @@
...
 
-  protected static final int HAS_FAILURE = 1;
-  protected static final int HAS_SKIPPED = 2;
-  protected static final int HAS_FSP = 4;
   protected static final int HAS_NO_TEST = 8;
 
   public static final Integer DEFAULT_VERBOSE = 1;
 
-  private int m_status;
   private boolean m_hasTests= false;
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: can be removed and replaced by direct usage of `exitCodeListener`

File: src/main/java/org/testng/TestNG.java [hunk 15]
```diff
@@ -211,11 +210,10 @@ private void init(boolean useDefaultListeners) {
   }
 
   public int getStatus() {
-    return m_status;
-  }
-
-  private void setStatus(int status) {
-    m_status |= status;
+    if (m_hasTests) {
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: I prefer:

```java
if (!m_hasTests) {
   return HAS_NO_TEST;
}
return exitCode.getExitCode();
```

because getStatus return the exit code, except in a specific case.

File: src/main/java/org/testng/internal/ExitCode.java [hunk 16]
```diff
@@ -0,0 +1,93 @@
...
+public class ExitCode {
+
+    private final BitSet exitCodeBits;
+
+    ExitCode() {
+        this(new BitSet(3));
+    }
+
+    public static boolean hasFailureWithinSuccessPercentage(int returnCode) {
+        return (returnCode >= 4 && returnCode <= 7);
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCode.java]: what about 
```java
return (returnCode & 4) == 4;
```

Comment (juherr) [reply src/main/java/org/testng/internal/ExitCode.java]: where 4 will be a constant

Comment (juherr) [reply src/main/java/org/testng/internal/ExitCode.java]: same below with skip = 2 and failure = 1

File: src/main/java/org/testng/TestNG.java [hunk 17]
```diff
@@ -1243,7 +1243,7 @@ private void generateReports(List<ISuite> suiteRunners) {
    */
   public List<ISuite> runSuitesLocally() {
     if (m_suites.isEmpty()) {
-      setStatus(HAS_NO_TEST);
+      this.m_hasTests = false;
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Don't need it because it is false by default.

File: src/main/java/org/testng/TestNG.java [hunk 18]
```diff
@@ -1490,7 +1490,7 @@ public static TestNG privateMain(String[] argv, ITestListener listener) {
       else {
         error(ex.getMessage());
       }
-      result.setStatus(HAS_FAILURE);
+      result.exitCode = ExitCode.newExitCodeRepresentingFailure();
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Why not `result.exitCode.setFailure()`?

**Review by juherr — COMMENTED** [review]
Much better 👍

File: src/main/java/org/testng/TestNG.java (hunk 18 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: I don't think it makes sense to expose setters into `ExitCode`. What would be wrong in having a factory method produce `ExitCode` instance that represents failure ?

File: src/main/java/org/testng/internal/ExitCode.java (hunk 16 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCode.java]: `(returnCode & 4) == 4;` would be true only for `4` no ? But the code has to be true for all values between 4 and 7. So I don't think we can use that. Same goes for skip and failure as well, because we now would say an execution had failures, even if it had failures+skips as well.

File: src/main/java/org/testng/TestNG.java [hunk 19]
```diff
@@ -142,14 +143,10 @@
   private final Map<Class<? extends IReporter>, IReporter> m_reporters = Maps.newHashMap();
   private final Map<Class<? extends IDataProviderListener>, IDataProviderListener> m_dataProviderListeners = Maps.newHashMap();
 
-  protected static final int HAS_FAILURE = 1;
-  protected static final int HAS_SKIPPED = 2;
-  protected static final int HAS_FSP = 4;
   protected static final int HAS_NO_TEST = 8;
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: Fixed.

File: src/main/java/org/testng/TestNG.java (hunk 14 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: Fixed.

File: src/main/java/org/testng/TestNG.java (hunk 15 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: Now that I have started reading `Clean Code` by `Robert Martin`, I can understand what you are saying. Intent.. its the intent that matters :) Fixed.

File: src/main/java/org/testng/TestNG.java (hunk 17 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: Agreed. Fixed.

File: src/main/java/org/testng/internal/ExitCode.java (hunk 16 above)
Comment (juherr) [reply src/main/java/org/testng/internal/ExitCode.java]: It is a bit mask, so it will return true when the bit is set. It should match with 4, 5, 6, 7.

Same thing for the others.

**Comment by krmahadevan** [comment]
@juherr - This time, added a new additional commit to fix some of the observations. For the rest I have replied back with my comments.

File: src/main/java/org/testng/TestNG.java (hunk 18 above)
Comment (juherr) [reply src/main/java/org/testng/TestNG.java]: ok

File: src/main/java/org/testng/internal/ExitCode.java (hunk 16 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCode.java]: @juherr - I am sorry. I didn't understand that. Can you please explain a bit more in detail perhaps with an example ?

File: src/main/java/org/testng/internal/ExitCodeListener.java [hunk 20]
```diff
@@ -0,0 +1,69 @@
...
+import org.testng.ITestContext;
+import org.testng.ITestListener;
+import org.testng.ITestResult;
+import org.testng.xml.XmlSuite;
+
+import java.util.List;
+
+public class ExitCodeListener implements ITestListener, IReporter {
+    private boolean hasTests = false;
+    private ExitCode status = new ExitCode();
```
Comment (juherr) [inline src/main/java/org/testng/internal/ExitCodeListener.java]: can be final

File: src/main/java/org/testng/internal/ExitCode.java (hunk 16 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCode.java]: Ok scratch that. Now I understood what you were hinting at.

`7 & 4` would be equal to `111 & 100` and the answer would still be `100`. Got it. Will fix it.

**Comment by krmahadevan** [comment]
@juherr  - Amended and pushed in fixes for all the comments.

File: src/main/java/org/testng/internal/ExitCodeListener.java (hunk 20 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ExitCodeListener.java]: Fixed. Don't know how that one slipped :)

File: src/main/java/org/testng/TestNGAntTask.java [hunk 21]
```diff
@@ -721,10 +722,10 @@ private void ppp(String string) {
   protected void actOnResult(int exitValue, boolean wasKilled) {
     if(exitValue == -1) {
       executeHaltTarget(exitValue);
-      throw new BuildException("an error occured when running TestNG tests");
+      throw new BuildException("an error occurred when running TestNG tests");
     }
 
-    if((exitValue & TestNG.HAS_NO_TEST) == TestNG.HAS_NO_TEST) {
+    if((exitValue & ExitCode.HAS_NO_TEST) == ExitCode.HAS_NO_TEST) {
```
Comment (juherr) [inline src/main/java/org/testng/TestNGAntTask.java]: Maybe add `ExitCode.hasNoTest(exitValue)`

**Review by juherr — APPROVED** [review]
