### PR TITLE
Streamline error reporting for missing types

### LINKED ISSUE #1976: TypeNotPresentExceptionProxy
### TestNG Version

6.10

### Expected behavior

Tests complete as expected in Jenkins

### Actual behavior

Tests run fine locally, but with Jenkins after the tests are run a `TypeNotPresentExceptionProxy` is thrown for some reason.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven on Jenkins
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

No test case. But here's a Jenkins run where it happens. https://builds.apache.org/job/Curator/63/console

Here's the stacktrace:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project curator-test-zk34: ExecutionException There was an error in the forked process
[ERROR] java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
[ERROR] at java.lang.reflect.Executable.declaredAnnotations(Executable.java:599)
[ERROR] at java.lang.reflect.Executable.declaredAnnotations(Executable.java:597)
[ERROR] at java.lang.reflect.Executable.getAnnotation(Executable.java:570)
[ERROR] at java.lang.reflect.Method.getAnnotation(Method.java:622)
[ERROR] at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:111)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:77)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:40)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:403)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:252)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:222)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:163)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:585)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:189)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:136)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1375)
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1976

Fixes #1976 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/annotations/AnnotationHelper.java [hunk 1]
```diff
@@ -345,4 +346,35 @@ private static String createMethodKey(Method m) {
 
     return result.toString();
   }
-}
+
+  static <A extends Annotation> A getAnnotationFromClass(Class<?> clazz, Class<A> a) {
+    try {
+      return clazz.getAnnotation(a);
+    } catch (Throwable t) {
+      String msg = "Encountered problems when parsing the annotation on class " + clazz.getCanonicalName() + ". ";
```
Comment (juherr) [inline src/main/java/org/testng/internal/annotations/AnnotationHelper.java]: Just check if `a` is not null because getAnnotation will throw an NPE which is not related to types.

**Review by juherr — APPROVED** [review]
Just fix the NPE case and good to merge then :)

File: src/main/java/org/testng/internal/annotations/AnnotationHelper.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/annotations/AnnotationHelper.java]: Fixed. Added null checks for both parameters of all the 3 new methods that were added.
