### PR TITLE
Skip considering synthetic methods for execution

### LINKED ISSUE #765: Test invoked twice when implements abstract method from parameterized parent.
Expected behavior: test should execute once

Actual behavior: test is executed twice

Code sample to duplicate:

https://github.com/sixtysecond/testng-bug

``` java
package foo;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class DuplicateCallsTest extends TestTemplate<Integer> {

    int i = 0;

    @Test(dataProvider = "testParameters")
    public void callExecuteTest(Integer testParameters)
            throws Exception {

        System.out.println(i);
        i++;
        System.out.println(testParameters);
    }



    @DataProvider(name = "testParameters")
    public Object[][] getOnboardingTestParameters() {
        return new Object[][] {
                { new Integer(4) }

        };
    }
}
```

``` java
package foo;


public abstract class TestTemplate<T> {

    public abstract void callExecuteTest(T testParameters) throws Exception;

}
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #765

Fixes #765 

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@cbeust / @juherr - Please help with review and merge of this PR.

File: src/test/java/test/ReflectionHelperTest.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+        methods = prune(ReflectionHelper.getLocalMethods(Dinosaur.class));
+        Assert.assertEquals(methods.length, 0);
+        methods = prune(ReflectionHelper.getLocalMethods(Dragon.class));
+        Assert.assertEquals(methods.length, 1);
+    }
+
+    private static Method[] prune(Method[] methods) {
+        List<Method> pruned = Lists.newArrayList(methods.length);
+        for (Method method : methods) {
+            if (! method.getName().contains("jacocoInit")) {
```
Comment (juherr) [inline src/test/java/test/ReflectionHelperTest.java]: Could you add a comment about what is this `javacocoInit`  method?

File: src/test/java/test/ReflectionHelperTest.java [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+import org.testng.internal.reflect.ReflectionHelper;
+import test.github765.DuplicateCallsSample;
+
+import java.lang.reflect.Method;
+import java.util.List;
+
+public class ReflectionHelperTest {
+
+    @Test
+    public void testMethodCount() {
```
Comment (juherr) [inline src/test/java/test/ReflectionHelperTest.java]: Could you add test case with bridge methods? http://stackoverflow.com/questions/5007357/java-generics-bridge-method#5007394

File: src/test/java/test/abstractmethods/CRUDTest.java [hunk 3]
```diff
@@ -2,11 +2,10 @@
 
 import org.testng.annotations.Test;
 
+@Test
 abstract public class CRUDTest {
 
-  @Test
   public abstract void create();
 
-  @Test(dependsOnMethods = "create")
```
Comment (juherr) [inline src/test/java/test/abstractmethods/CRUDTest.java]: Why do you remove `dependsOnMethods`?

File: src/test/java/test/ReflectionHelperTest.java [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+        Method[] methods = prune(ReflectionHelper.getLocalMethods(DuplicateCallsSample.class));
```
Comment (juherr) [inline src/test/java/test/ReflectionHelperTest.java]: Maybe you can add a quick comment to describe which case you are testing.

File: src/test/java/test/github765/DuplicateCallsSample.java [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+
+    private int i = 0;
+    static List<String> messages = Lists.newLinkedList();
+
+    @Test(dataProvider = "testParameters")
+    public void callExecuteTest(Integer testParameters) throws Exception {
+        messages.add("Iteration [" + i++ + "], Test Parameter [" + testParameters + "]");
+    }
+
+
```
Comment (juherr) [inline src/test/java/test/github765/DuplicateCallsSample.java]: Too many blank lines

File: src/test/java/test/github765/ExcludeAbstractMethodsFromTemplateCallsTest.java [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+import test.SimpleBaseTest;
+
+
+public class ExcludeAbstractMethodsFromTemplateCallsTest extends SimpleBaseTest {
+
+    @Test
+    public void testMethod() {
+        TestNG testng = create(DuplicateCallsSample.class);
+        testng.run();
+        Assert.assertFalse(DuplicateCallsSample.messages.isEmpty(), "Method invocation log should not be empty.");
```
Comment (juherr) [inline src/test/java/test/github765/ExcludeAbstractMethodsFromTemplateCallsTest.java]: The `InvokedMethodNameListener` should work too. Maybe it is not the best way to test (I'm open to any improvements) but I'd like to keep the same pattern for every tests if possible.

**Review by juherr — CHANGES_REQUESTED** [review]

File: src/test/java/test/ReflectionHelperTest.java (hunk 2 above)
Comment (krmahadevan) [inline src/test/java/test/ReflectionHelperTest.java]: The test 
```
        Method[] methods = prune(ReflectionHelper.getLocalMethods(DuplicateCallsSample.class));
Assert.assertEquals(methods.length, 2);
```
already is doing that.

Comment (krmahadevan) [inline src/test/java/test/ReflectionHelperTest.java]: Done

File: src/test/java/test/ReflectionHelperTest.java (hunk 4 above)
Comment (krmahadevan) [inline src/test/java/test/ReflectionHelperTest.java]: Done

File: src/test/java/test/ReflectionHelperTest.java (hunk 1 above)
Comment (krmahadevan) [inline src/test/java/test/ReflectionHelperTest.java]: added javadocs on top of the `jacocoInit` explaining what is going on in this method.

File: src/test/java/test/abstractmethods/CRUDTest.java (hunk 3 above)
Comment (krmahadevan) [inline src/test/java/test/abstractmethods/CRUDTest.java]: Fixed this. Realised that this was intentionally introduced by @cbeust as part of [this](https://github.com/cbeust/testng/commit/bb4cfdadd903ebefb0510bc8586b7b353cf29d17) commit. Since my PR is dealing with only `bridged` methods, I reverted my change of excluding `abstract methods`.

File: src/test/java/test/github765/DuplicateCallsSample.java (hunk 5 above)
Comment (krmahadevan) [inline src/test/java/test/github765/DuplicateCallsSample.java]: :) ok... taken care.

File: src/test/java/test/github765/ExcludeAbstractMethodsFromTemplateCallsTest.java (hunk 6 above)
Comment (krmahadevan) [inline src/test/java/test/github765/ExcludeAbstractMethodsFromTemplateCallsTest.java]: Fixed.

**Comment by krmahadevan** [comment]
@juherr - I have fixed all your review comments. Please check

File: src/test/java/test/ReflectionHelperTest.java (hunk 2 above)
Comment (juherr) [inline src/test/java/test/ReflectionHelperTest.java]: Ok! I don't know if it has sense but could you just add a test case with bridge methods without inheritance?

Comment (krmahadevan) [inline src/test/java/test/ReflectionHelperTest.java]: @juherr - a method from a generics class gets regarded as a bridged method only when there is inheritance involved. So no point in adding a test case for bridge methods without inheritance.

**Comment by krmahadevan** [comment]
ping @juherr - Please advise if this can be merged.

**Review by juherr — APPROVED** [review]

**Comment by juherr** [comment]
LGTM :+1: 

Ping @cbeust

**Comment by cbeust** [comment]
Nice catch @krmahadevan!

**Comment by krmahadevan** [comment]
Thank you @cbeust  :)
