### PR TITLE
Prevent ConcurrentModificationException

### LINKED ISSUE #2000: ThreadPoolExecutor ConcurrentModificationException
### TestNG Version
7.0.0-beta1

### Actual behavior
Exception in thread "TestNG-test=default-1" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:118)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

### Is the issue reproductible on runner?
Jar

### Test case sample
no test case

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2000

Fixes #2000  .

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - I wasn't able to create a sample that reproduces this issue, but skimming through the codebase I found that we are having a shared data structure as `Map` which is going to be accessed concurrently and as such there's a possibility of the exception.

File: src/main/java/org/testng/ClassMethodMap.java [hunk 1]
```diff
@@ -20,8 +20,8 @@
   private Map<Object, Collection<ITestNGMethod>> classMap = Maps.newConcurrentMap();
   // These two variables are used throughout the workers to keep track
   // of what beforeClass/afterClass methods have been invoked
-  private Map<ITestClass, Set<Object>> beforeClassMethods = Maps.newHashMap();
-  private Map<ITestClass, Set<Object>> afterClassMethods = Maps.newHashMap();
+  private Map<ITestClass, Set<Object>> beforeClassMethods = Maps.newConcurrentMap();
```
Comment (juherr) [inline src/main/java/org/testng/ClassMethodMap.java]: `final` is possible.

**Review by juherr — APPROVED** [review]

File: src/main/java/org/testng/ClassMethodMap.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/ClassMethodMap.java]: fixed
