### PR TITLE
IInvokedMethodListener implementation called for skipped methods

### LINKED ISSUE #1465: Version 6.11 - Failure policy CONTINUE handling is broken for tests that are skipped in @BeforeMethod method
With TestNG 6.11, execution of a test is completely aborted if SkipException is thrown by a `@BeforeMethod` method. Even the afterInvocation() method of active IInvokedMethodListener listeners are skipped, although the simple example shown below doesn't demonstrate this.

### TestNG Version:
6.11

### Expected behavior
Execution should continue if failure policy is set to CONTINUE.

### Actual behavior
Execution aborts if `@BeforeMethod` method throws SkipException.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [?] Gradle
- [?] Ant
- [X] Eclipse
- [?] IntelliJ
- [?] NetBeans

### Test case sample
```java
package com.nordstrom.automation.testng;

import static org.testng.Assert.assertTrue;

import java.lang.reflect.Method;

import org.testng.SkipException;
import org.testng.TestNG;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.xml.XmlSuite.FailurePolicy;

class IssueTest {
    
    @Test
    public void testExample() {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{ExampleClass.class});
        testNG.setConfigFailurePolicy(FailurePolicy.CONTINUE);
        testNG.run();
    }
    
    static class ExampleClass {
    
        @BeforeMethod
        public void beforeMethod(Method method) {
            System.out.println("beforeMethod: " + method.getName());
            if ("test1".equals(method.getName())) {
                throw new SkipException("Skip from [before]");
            }
        }
        
        @Test
        public void test1() {
            System.out.println("test1");
            assertTrue(true);
        }
        
        @Test
        public void test2() {
            System.out.println("test2");
            assertTrue(true);
        }
        
        @AfterMethod
        public void afterMethod(Method method) {
            System.out.println("afterMethod: " + method.getName());
        }
    }
}
```

Expected output:
> beforeMethod: test1
> afterMethod: test1
> beforeMethod: test2
> test2
> afterMethod: test2

Actual output:
> beforeMethod: test1
> beforeMethod: test2
> test2
> afterMethod: test2

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1465

Ensure that IInvokedMethodListener’s before and 
afterInvocation() are always invoked (Even for 
skipped methods as well)

Fixes #1465 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr - please help take a look.

File: src/test/java/test/listeners/github1465/IssueTest.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+    @Test(dataProvider = "dp")
+    public void reproduceIssue(XmlSuite.FailurePolicy policy, String[] expectedMsgs) {
+        TestNG testNG = create(ExampleClassSample.class);
+        testNG.setConfigFailurePolicy(policy);
+        ExampleClassListener listener = new ExampleClassListener();
+        testNG.addListener((ITestNGListener) listener);
+        testNG.run();
+        assertThat(listener.messages.size()).isEqualTo(4);
+        String[] expected = new String[]{
```
Comment (juherr) [inline src/test/java/test/listeners/github1465/IssueTest.java]: Or you can directly pass strings in the varargs.

File: src/test/java/test/listeners/github1465/ExampleClassListener.java [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+        }
+        if (tm.isAfterMethodConfiguration()) {
+            return "after_method: ";
+        }
+        return "test_method: ";
+    }
+
+    private static String parameters(ITestResult testResult) {
+        Object[] parameters = testResult.getParameters();
+        if (parameters != null) {
```
Comment (juherr) [inline src/test/java/test/listeners/github1465/ExampleClassListener.java]: I think quick return helps to highlight the important code vs check code:

```java
if (parameters == null) {
  return "";
}

// ...

File: src/test/java/test/listeners/github1465/ExampleClassListener.java [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+import org.testng.IInvokedMethodListener;
+import org.testng.ITestNGMethod;
+import org.testng.ITestResult;
+
+import java.lang.reflect.Method;
+import java.util.LinkedList;
+import java.util.List;
+
+public class ExampleClassListener implements IInvokedMethodListener {
+    List<String> messages = new LinkedList<>();
```
Comment (juherr) [inline src/test/java/test/listeners/github1465/ExampleClassListener.java]: could be `final`

File: src/test/java/test/listeners/github1465/IssueTest.java (hunk 1 above)
Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/IssueTest.java]: In either case, it's still going to be the same right since varargs are internally just arrays

File: src/test/java/test/listeners/github1465/IssueTest.java [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+                "beforeInvocation:_test_method: test1", "afterInvocation:_test_method: test1",
+                "beforeInvocation:_test_method: test2", "afterInvocation:_test_method: test2"
+        };
+        assertThat(listener.messages).containsExactly(expected);
+        assertThat(listener.configMsgs.size()).isEqualTo(expectedMsgs.length);
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/IssueTest.java]: Fixed.

File: src/test/java/test/listeners/github1465/ExampleClassListener.java (hunk 3 above)
Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/ExampleClassListener.java]: Fixed.

File: src/test/java/test/listeners/github1465/ExampleClassListener.java (hunk 2 above)
Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/ExampleClassListener.java]: Was trying to avoid having to introduce multiple exits in this method, especially when its branching construct is pretty small and fits a page when viewed in an IDE. Anyways.. will change it.

**Comment by krmahadevan** [comment]
@juherr - Review comments addressed.

File: src/test/java/test/listeners/github1465/IssueTest.java (hunk 1 above)
Comment (juherr) [reply src/test/java/test/listeners/github1465/IssueTest.java]: True! I'm just sharing my own code style in order to try to not have too many different styles. But feel free to ignore such kind of comments ;)

File: src/test/java/test/listeners/github1465/ExampleClassListener.java (hunk 2 above)
Comment (juherr) [reply src/test/java/test/listeners/github1465/ExampleClassListener.java]: Again, true. It was clearly debatable here.

File: src/test/java/test/listeners/github1465/ExampleClassListener.java [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+        }
+        return "test_method: ";
+    }
+
+    private static String parameters(ITestResult testResult) {
+        Object[] parameters = testResult.getParameters();
+        if (parameters == null) {
+            return "";
+        }
+        String returnValue = "";
```
Comment (juherr) [inline src/test/java/test/listeners/github1465/ExampleClassListener.java]: This variable is optional

**Review by juherr — APPROVED** [review]
LGTM :+1: 
Ping @cbeust

File: src/test/java/test/listeners/github1465/IssueTest.java (hunk 1 above)
Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/IssueTest.java]: @juherr - Yes I kind of realized that part. But then again, I guess it would be good if we could not force the coding style on contributors, because everyone has their own style of coding and its hard to bring consensus on it. It also elongates code reviews and turn around time and thus a PR can perhaps take a longer time. So it would be good if we can avoid/skip those comments which can be branded as coding style.

Comment (juherr) [reply src/test/java/test/listeners/github1465/IssueTest.java]: @krmahadevan I disagree because I think it will be more and more difficult the read the code if we have too many styles (it is already the case IMO), and trying to have a close style will help.
A consensus is not a goal and will be a waste of time, but style comments will just highlight divergences. The final decision is yours and style should not block the merge (except specific cases :p). WDYT?

Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/IssueTest.java]: @juherr - Asking for a PR which adheres to an undocumented coding style only makes it more worse. It deteriorates the enthusiasm in a person to raise a PR. Logging comments in a PR are meant to get addressed, but logging a comment and then leaving the decision to the PR creator adds more confusion (which to fix and which not to). If coding styles (if we are looking at following a common one) are to be followed in PR, then its better to have them documented. That way there's no room for confusion and a person who like to raise a PR would be informed even before the PR is raised about the obvious set of areas wherein flags are going to be raised (if the desired conventions/styles are not followed). 

I am not against having a coding style defined for a project, I just would like to see it documented if its asked to be followed. That way it helps keep things easier and PR reviews/merges are smoother.

Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/IssueTest.java]: ping @cbeust - Cedric, please add your thoughts as well on this, so that we can come to a consensus and start working on building the guidelines. I think it would be helpful to anyone who wants to contribute to TestNG as well, in general, if such guidelines are created.

**Comment by krmahadevan** [comment]
@cbeust - I have resolved the merge conflicts. Please help approve/merge.

File: src/test/java/test/listeners/github1465/IssueTest.java (hunk 1 above)
Comment (juherr) [reply src/test/java/test/listeners/github1465/IssueTest.java]: @krmahadevan 
> It deteriorates the enthusiasm in a person to raise a PR.

I hope it is not your case, it was not a goal.

About the guideline, I've already proposed to follow Google style on new/modified code because it is well documented and it provides IDE files (https://google.github.io/styleguide/javaguide.html / https://github.com/google/styleguide).

But here, in the specific case of array versus varargs, I don't know if we need debate: I find varargs nicer but I'm not sure it is more readable.

Comment (cbeust) [reply src/test/java/test/listeners/github1465/IssueTest.java]: I'm pretty strict on syntactic issues (e.g. indentation, naming) but less so on semantics (what you guys are discussing above).

At the end of the day, I don't think having different styles like this makes it really hard to read the code and minimizing these rules encourages people to submit a PR.

Comment (krmahadevan) [reply src/test/java/test/listeners/github1465/IssueTest.java]: @cbeust - Thanks for your feedback.

@juherr 

> I hope it is not your case, it was not a goal.

Never at all :) TestNG contribution has now turned into too big of an addiction and I would like to keep it that way. I get to learn a lot of stuff in the name of contributing. So I am not going to let anything hinder that.
