### PR TITLE
Prevent NPE when TestNG aborts due to errors

### LINKED ISSUE #1810: Nullpointer exception when running TestNG tests from CMD
Hello,

I face the following situation with TestNG. I have a Maven project which runs normally from within Eclipse. When I try to run the tests from CMD I get java.lang.NullPointerException as shown in screenshot below:

image

The structure of the folders are like this (assuming that current location is within the project's directory):
- ./libs/  contains all the jar files
- ./src/main/java/com/site/tests/  contains the java classes
- ./target/classes/com/site/tests/  contains the .class files

I have tried the following commands but to no avail - the result is the same!
`java -cp libs\* org.testng.TestNG testng.xml` and
`Java -cp .\target\classes\com\site\tests\*;.\libs\* org.testng.TestNG testng.xml`

Do you have any idea why I might be getting a nullPointer? Attached you may find the project's folder and the testng.xml

image

image

### TestNG Version
6.14.2

### Java version
image

Thank you in advance!

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1810

Fixes #1810 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/TestNG.java [hunk 1]
```diff
@@ -176,7 +176,7 @@
 
   private boolean m_isInitialized = false;
   private boolean isSuiteInitialized = false;
-  private org.testng.internal.ExitCodeListener exitCodeListener;
+  private org.testng.internal.ExitCodeListener exitCodeListener = new org.testng.internal.ExitCodeListener();
```
Comment (juherr) [inline src/main/java/org/testng/TestNG.java]: Could be final

**Review by juherr — APPROVED** [review]

File: src/main/java/org/testng/TestNG.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/TestNG.java]: Fixed

**Comment by krmahadevan** [comment]
ping @cbeust - Can you please help approve and merge ?
