### PR TITLE
A failed retry with ITestContext will lose the ITestContext

### LINKED ISSUE #2669: A failed retry with ITestContext  will lose the ITestContext
### Expected behavior
The example will be executed three times

异常抛出：
java.lang.AssertionError: 
Expected :1
Actual   :2

### Actual behavior
`java.lang.IllegalArgumentException: wrong number of arguments`

Found that the ITestContext context parameter is missing during debugging

### Is the issue reproducible on runner?
all
- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="test" parallel="false">
    <parameter name="id" value="1111"/>
    <parameter name="name" value="qa"/>
    <parameter name="age" value="30"/>

    <listeners>
        <!--rerun after failure-->
        <listener class-name="com.xxxx.xxxx.FailedRetryListener"/>
    </listeners>

    <test verbose="1" name="case1" thread-count="1">
        <classes>
            <class name="com.xxxx.xxx.xxxTest">
                <methods>
                    <include name="create"/>
                </methods>
            </class>
        </classes>
    </test>
</suite>
```

```java
@Parameters({"id", "name", "age"})
@Test(retryAnalyzer= FailedRetry.class)
public void create(String id, String name, String age, ITestContext context){
    Assert.assertEquels(1,2)
}
```

```java
public class FailedRetry implements IRetryAnalyzer {
    private int retryCount = 1;
    private static final int maxRetryCount = 3;

    @Override
    public boolean retry(ITestResult iTestResult) {
        //If an exception is thrown, the failure case will be rerun. If it is an assertion error, try again
        if (iTestResult.getThrowable() instanceof AssertionError && retryCount % maxRetryCount != 0) {
            retryCount++;
            return true;
        } else {
            retryCount = 1;
            return false;
        }
    }
}
```

```java
public class FailedRetryListener implements IAnnotationTransformer {

    @Override
    public void transform(ITestAnnotation iTestAnnotation, Class aClass,
                          Constructor constructor, Method method) {
        {
            IRetryAnalyzer retry = null;
            try {
                retry = iTestAnnotation.getRetryAnalyzerClass().newInstance();
            } catch (InstantiationException | IllegalAccessException e) {
                e.printStackTrace();
            }
            if (retry == null) {
                iTestAnnotation.setRetryAnalyzer(FailedRetry.class);
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by bj-9527**
A failed retry with ITestContext will lose the ITestContext

Fixes #2669.

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@bj-9527 Thanks for the PR. CN you please check if there are any formatting failures? It looks like the tests didn't run

File: testng-core/src/test/java/test/retryAnalyzer/github2669/IssueTest.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
+package test.retryAnalyzer.github2669;
+
+import org.testng.Assert;
+import org.testng.TestNG;
+import org.testng.annotations.Test;
+import test.SimpleBaseTest;
+import java.util.Collections;
+
+public class IssueTest extends SimpleBaseTest {
```
Comment (krmahadevan) [inline testng-core/src/test/java/test/retryAnalyzer/github2669/IssueTest.java:9]: Can you please remove this test class and instead add this test method (with a description that refers to the github issue) inside `test.retryAnalyzer.RetryAnalyzerTest` ? We would like to get away from this practise of having all these `IssueTest` but instead have one class that has tests for everything.

File: testng-core/src/test/java/test/retryAnalyzer/github2669/IssueTest.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+  @Test
+  public void testFailedRetryWithParameters() {
+    TestNG testng = create();
+    String testngXmlPath = getPathToResource("xml/github2669.xml");
```
Comment (krmahadevan) [inline testng-core/src/test/java/test/retryAnalyzer/github2669/IssueTest.java:13]: Why not work with the XmlSuite and XmlTest instead? That would be a lot more easier with respect to keeping the details of the test within the confines of this test method itself and not have to worry about all these extra suite files.

File: testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+                        Constructor constructor, Method method) {
+    {
+      IRetryAnalyzer retry = null;
+      try {
+        retry = iTestAnnotation.getRetryAnalyzerClass().newInstance();
+      } catch (InstantiationException | IllegalAccessException e) {
+        e.printStackTrace();
+      }
+      if (retry == null) {
+        iTestAnnotation.setRetryAnalyzer(FailedRetry.class);
```
Comment (krmahadevan) [inline testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java:22]: This can be moved within the `catch` block and the printstacktrace part can be removed

File: testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetry.java [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+  public static int retryCount = 1;
+  private static final int maxRetryCount = 3;
+
+  @Override
+  public boolean retry(ITestResult iTestResult) {
+    //If an exception is thrown, the failure case will be rerun. If it is an assertion error, try again
+    if (iTestResult.getThrowable() instanceof AssertionError && retryCount % maxRetryCount != 0) {
+      retryCount++;
+      return true;
+    } else {
```
Comment (krmahadevan) [inline testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetry.java:16]: else part can be removed and we could just say `retryCount = 1; return false`.

**Comment by bj-9527** [comment]
> @bj-9527 Thanks for the PR. CN you please check if there are any formatting failures? It looks like the tests didn't run
> 
> Please refer to https://github.com/cbeust/testng/blob/master/.github/CONTRIBUTING.md for some detailed instructions

Thanks a lot, it really helps.

File: testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+import org.testng.IRetryAnalyzer;
+import org.testng.annotations.ITestAnnotation;
+
+public class FailedRetryListener implements IAnnotationTransformer {
+  @Override
+  public void transform(
+      ITestAnnotation iTestAnnotation, Class aClass, Constructor constructor, Method method) {
+    IRetryAnalyzer retry = null;
+    try {
+      retry = iTestAnnotation.getRetryAnalyzerClass().newInstance();
```
Comment (juherr) [inline testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java:15]: This line doesn't compile in jdk >8

File: testng-core/src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java [hunk 6]
```diff
@@ -240,6 +243,20 @@ public void ensureRetryDoesntRunEndlesslyForDataDrivenTests() {
...
+    XmlSuite suite = createXmlSuite("GITHUB_2669");
+    Map<String, String> params = new HashMap<>();
+    params.put("id", "1111");
+    params.put("name", "qa");
+    params.put("age", "30");
+    suite.setParameters(params);
+    createXmlTest(suite, "2669_Test", RetryTestSample.class);
+    TestNG testng = create(suite);
+    testng.run();
+    Assert.assertEquals(RetryTestSample.count, 3);
```
Comment (juherr) [inline testng-core/src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java:257]: I prefer you use a test listener and assert on the sequence of method+status.

File: testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java [hunk 7]
```diff
@@ -0,0 +1,20 @@
+package test.retryAnalyzer.github2669;
+
+import java.lang.reflect.Constructor;
+import java.lang.reflect.Method;
+import org.testng.IAnnotationTransformer;
+import org.testng.IRetryAnalyzer;
+import org.testng.annotations.ITestAnnotation;
+
+public class FailedRetryListener implements IAnnotationTransformer {
```
Comment (juherr) [inline testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java:9]: I don't get the purpose of this listener

File: testng-core/src/test/java/test/retryAnalyzer/github2669/RetryTestSample.java [hunk 8]
```diff
@@ -0,0 +1,19 @@
...
+
+import org.testng.Assert;
+import org.testng.ITestContext;
+import org.testng.annotations.Listeners;
+import org.testng.annotations.Parameters;
+import org.testng.annotations.Test;
+
+@Listeners({FailedRetryListener.class})
+public class RetryTestSample {
+  public static int count = 0;
```
Comment (juherr) [inline testng-core/src/test/java/test/retryAnalyzer/github2669/RetryTestSample.java:11]: No need of count if you use assertion on listener

File: testng-core/src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java [hunk 9]
```diff
@@ -240,6 +243,20 @@ public void ensureRetryDoesntRunEndlesslyForDataDrivenTests() {
     assertThat(test.retryAnalyzer.dataprovider.issue2163.RetryAnalyzer.logs).hasSize(21);
   }
 
+  @Test(description = "GITHUB-2669")
+  public void testFailedRetryWithParameters() {
+    XmlSuite suite = createXmlSuite("GITHUB_2669");
```
Comment (juherr) [inline testng-core/src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java:248]: You can add a new helper method `createXmlSuite(String name, Map<String, String> params)`

**Review by juherr — CHANGES_REQUESTED** [review]

**Review by juherr — APPROVED** [review]

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@bj-9527 - Thank you for taking the time to submit this PR. Appreciate it.
