### PR TITLE
Retain test attributes in skipped tests

### LINKED ISSUE #2346: ITestResult attributes are null when retrieved by Listener onTestStart if test fails at BeforeMethod
### TestNG Version
7.1.0

### Expected behavior
Retrieving an ITestResult attribute from onTestStart returns the set value if the test fails during the BeforeMethod

### Actual behavior
Retrieving an ITestResult attribute from onTestStart returns null if the test fails during the BeforeMethod

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

BaseTest
```java
@Listeners(com.test.LocalTestListener.class)
public class BaseTest {
    @BeforeMethod(alwaysRun=true)
    public void setUp(ITestResult result) throws Exception {
    	String session = RandomStringUtils.randomAlphabetic(10);
    	System.out.println("BaseTest - BeforeMethod - Thread: " + Thread.currentThread().getId() + " Generated: " + aw);
    	result.setAttribute("session", session);
    }

    @AfterMethod(alwaysRun=true)
    public void tearDown(ITestResult result) {
    	System.out.println("BaseTest - AfterMethod - Thread: " + Thread.currentThread().getId() + " Ending session: " + result.getAttribute("session"));
    }
}
```
SingleTest
```java
public class SingleTest extends BaseTest {
	@BeforeMethod
	public void start() {
		System.out.println("SingleTest2 - BeforeMethod - Thread: " + Thread.currentThread().getId() + " asserting failure");
		assertTrue(false);
	}
	@Test
	public void test() throws Exception {
		System.out.println("SingleTest2 - Test - Thread: " + Thread.currentThread().getId());
	}
}
```
Listener methods
```java
public void onTestStart(ITestResult iTestResult) {
    	String testMethodName = getTestMethodName(iTestResult);
    	System.out.println("Listener - Thread: " + Thread.currentThread().getId() + " STARTING TEST - " + testMethodName + " session: " + iTestResult.getAttribute("session"));
    }
    public void onTestSuccess(ITestResult iTestResult) {
    	String testMethodName = getTestMethodName(iTestResult);
    	System.out.println("Listener - Thread: " + Thread.currentThread().getId() + " TEST PASSED - " + testMethodName + " session: " + iTestResult.getAttribute("session"));
    }

    public void onTestFailure(ITestResult iTestResult) {
    	String testMethodName = getTestMethodName(iTestResult);
    	System.out.println("Listener - Thread: " + Thread.currentThread().getId() + " TEST FAILED - " + testMethodName + " session: " + iTestResult.getAttribute("session"));
    }

    public void onTestSkipped(ITestResult iTestResult) {
    	String testMethodName = getTestMethodName(iTestResult);
    	System.out.println("Listener - Thread: " + Thread.currentThread().getId() + " TEST SKIPPED - " + testMethodName + " session: " + iTestResult.getAttribute("session"));
    }
```
Output
```
BaseTest - BeforeMethod - Thread: 10 Generated: PumcZjXSoV
SingleTest - BeforeMethod - Thread: 10 asserting failure
Listener - Thread: 10 STARTING TEST - test session: **null**
Listener - Thread: 10 TEST SKIPPED - test session: PumcZjXSoV
BaseTest - AfterMethod - Thread: 10 Ending session: PumcZjXSoV
```

The `result.getAttribute("session")` call in onTestStart returns null if there is a failure in the BeforeTest. If the failure occurs within the @Test method, it returns the correct value

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2346

Fixes #2346  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@cbeust @juherr - Can you please help take a look.

File: src/main/java/org/testng/internal/ITestInvoker.java [hunk 1]
```diff
@@ -35,6 +35,9 @@ FailureContext retryFailed(
 
   ITestResult registerSkippedTestResult(ITestNGMethod testMethod, long start, Throwable throwable);
```
Comment (juherr) [inline src/main/java/org/testng/internal/ITestInvoker.java:36]: Is it possible to remove this one?

Comment (krmahadevan) [reply src/main/java/org/testng/internal/ITestInvoker.java:36]: @juherr - Sure we can. But there are invocations which will not involve a `ITestResult` object. If we remove this method then those calls would need to unnecessarily pass a spurious `null` object, which I was trying to avoid and have it taken care of internally.

File: src/main/java/org/testng/internal/TestInvoker.java [hunk 2]
```diff
@@ -703,13 +703,21 @@ private void runConfigMethods(TestMethodArguments arguments,
 
   public ITestResult registerSkippedTestResult(
       ITestNGMethod testMethod, long start, Throwable throwable) {
```
Comment (juherr) [inline src/main/java/org/testng/internal/TestInvoker.java:705]: You can implement it into a default method from the interface

**Review by juherr — APPROVED** [review]

File: src/main/java/org/testng/internal/TestInvoker.java (hunk 2 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/TestInvoker.java]: Fixed
