### PR TITLE
Skip considering main() method

### LINKED ISSUE #1405: Cannot inject @Test annotated Method [main] with [class [Ljava.lang.String;].
```java
@Test(singleThreaded = true)
public class MainTest {

  @Test public void foo() {}

  public static void main(String[] args) {}
}
```

```
[Utils] [ERROR] [Error] org.testng.TestNGException: 
Cannot inject @Test annotated Method [main] with [class [Ljava.lang.String;].
```

While understandable, I'd argue that the class annotation shouldn't apply to static methods or, at least, to the `main` method. It is easy to work around by configuring each method, but was surprising.

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #1405
Closes #1405

Fixes #1405 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr

File: src/main/java/org/testng/internal/reflect/ReflectionHelper.java [hunk 1]
```diff
@@ -38,6 +38,36 @@
...
+  public static Method[] excludingMain(Class<?> clazz) {
+    Method[] declaredMethods = clazz.getDeclaredMethods();
+    List<Method> pruned = new LinkedList<>();
+    for (Method declaredMethod :declaredMethods) {
+      if ("main".equals(declaredMethod.getName()) && isStaticVoid(declaredMethod) && acceptsStringArray(declaredMethod)) {
+        continue;
+      }
+      pruned.add(declaredMethod);
+    }
+    return pruned.toArray(new Method[0]);
```
Comment (juherr) [inline src/main/java/org/testng/internal/reflect/ReflectionHelper.java]: Use `size` of `pruned` for the array.

File: src/main/java/org/testng/internal/reflect/ReflectionHelper.java [hunk 2]
```diff
@@ -38,6 +38,36 @@
...
+   * @return An array of all locally declared methods or equivalent thereof
+   * (such as default methods on Java 8 based interfaces that the given class
+   * implements) but excludes the <code>main()</code> method alone.
+   */
+  public static Method[] excludingMain(Class<?> clazz) {
+    Method[] declaredMethods = clazz.getDeclaredMethods();
+    List<Method> pruned = new LinkedList<>();
+    for (Method declaredMethod :declaredMethods) {
+      if ("main".equals(declaredMethod.getName()) && isStaticVoid(declaredMethod) && acceptsStringArray(declaredMethod)) {
+        continue;
```
Comment (juherr) [inline src/main/java/org/testng/internal/reflect/ReflectionHelper.java]: I think we should warn the user that we have skipped its test.

File: src/test/java/test/github1405/TestExclusionOfMainMethod.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+        tng.run();
+        Assert.assertEquals(tng.getStatus(), 0);
+    }
+
+    @Test
+    public void testMainMethodExclusionForJunit() {
+        XmlSuite xmlSuite = createXmlSuite("suite");
+        xmlSuite.setJunit(true);
+        createXmlTest(xmlSuite, "test", JUnitTestClassSample.class);
+        TestNG tng = create();
```
Comment (juherr) [inline src/test/java/test/github1405/TestExclusionOfMainMethod.java]: Use `create(xmlSuite)`

**Review by juherr — CHANGES_REQUESTED** [review]
Only few changes :+1:

File: src/main/java/org/testng/internal/reflect/ReflectionHelper.java (hunk 2 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/reflect/ReflectionHelper.java]: @juherr - I think Earlier it was never possible to include a `main()` method as part of the execution chain. So this warning is not going to add any value.

File: src/main/java/org/testng/internal/reflect/ReflectionHelper.java (hunk 1 above)
Comment (krmahadevan) [inline src/main/java/org/testng/internal/reflect/ReflectionHelper.java]: I didn't realize that the implementation of `toArray()` in `LinkedList` involved reflection. I thought it would be the same that is being used by `ArrayList`

File: src/test/java/test/github1405/TestExclusionOfMainMethod.java (hunk 3 above)
Comment (krmahadevan) [inline src/test/java/test/github1405/TestExclusionOfMainMethod.java]: fixed.

**Comment by krmahadevan** [comment]
ping @juherr Please let me know if this is good to be merged

File: src/main/java/org/testng/internal/reflect/ReflectionHelper.java (hunk 2 above)
Comment (juherr) [inline src/main/java/org/testng/internal/reflect/ReflectionHelper.java]: ok ! :)

**Review by juherr — APPROVED** [review]
LGTM 👍 
Ping @cbeust
