### PR TITLE
Fix for 1077 and 1081 properly rebased

### LINKED ISSUE #1077: TestNG cannot handle load
Hi,

I tried to run regression for almost 1000 suites. The performance with testng is fine till I ran 500-600 suites, but when the load increases, testng is getting stuck at topologicalsort in MethodHelper.class. 

Please let me know if anyone faced this issue or if there is any way to resolve this. 

Regards,
Udaya

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #1077 #1081.

Closes #1077 #1081.

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
This PR is a continuation of what @Aheiss delivered as part of PR #1703 . I have just squashed the commits, rebased it off of master, and added fix for some failing tests.

File: src/main/java/org/testng/internal/MethodHelper.java [hunk 1]
```diff
@@ -265,6 +295,35 @@ public int compare(Node<ITestNGMethod> o1, Node<ITestNGMethod> o2) {
...
+      if (methodInstance == null) {
+        continue;
+      }
+      //Look for method instance in list and update associated methods
+      List<ITestNGMethod> methodList = result.get(methodInstance);
+      if (methodList == null) {
+        methodList = new ArrayList<>();
+      }
+      methodList.add(method);
+      result.put(methodInstance, methodList);
```
Comment (juherr) [inline src/main/java/org/testng/internal/MethodHelper.java]: This line should be in the if statement

File: src/main/java/org/testng/internal/MethodHelper.java [hunk 2]
```diff
@@ -237,8 +252,23 @@ public int compare(Node<ITestNGMethod> o1, Node<ITestNGMethod> o2) {
       String[] methodsDependedUpon = m.getMethodsDependedUpon();
       String[] groupsDependedUpon = m.getGroupsDependedUpon();
       if (methodsDependedUpon.length > 0) {
-        ITestNGMethod[] methodsNamed =
-          MethodHelper.findDependedUponMethods(m, methods);
+        ITestNGMethod[] methodsNamed = null;
```
Comment (juherr) [inline src/main/java/org/testng/internal/MethodHelper.java]: Useless null init

**Review by juherr — APPROVED** [review]
LGTM thanks @krmahadevan and @Aheiss

File: src/main/java/org/testng/internal/MethodHelper.java [hunk 3]
```diff
@@ -237,8 +252,23 @@ public int compare(Node<ITestNGMethod> o1, Node<ITestNGMethod> o2) {
...
+            // Search for other methods that depends upon with the same instance
+            methodsNamed = MethodHelper.findDependedUponMethods(m, instanceMethods);
+          } catch (TestNGException e) {
+            //Maybe this method has a dependency on a method that resides in a different instance.
+            //Lets try searching for all methods now
+            methodsNamed = MethodHelper.findDependedUponMethods(m, methods);
+          }
+        } else {
+          // Search all methods
+          methodsNamed = MethodHelper.findDependedUponMethods(m, methods);
```
Comment (cbeust) [inline src/main/java/org/testng/internal/MethodHelper.java]: I was trying to find a way to avoid the duplication of this line with line 266 but because of the exception, I don't really see an elegant refactoring.

**Review by cbeust — APPROVED** [review]
It would be nice to have a test for this but since it's a performance optimization, not really easy. As long as all the tests pass, we're good.

**Comment by Aheiss** [comment]
Thanks for your help @juherr and @krmahadevan ! Should I close my other pull request?

**Comment by krmahadevan** [comment]
@cbeust - Shall I go ahead and merge this pull request ?

**Comment by cbeust** [comment]
Yup, I approved.
