### PR TITLE
Fixing class param injection with @BeforeClass

### LINKED ISSUE #1417: Class param injection is not working with @BeforeClass
### TestNG Version
Current master

### Test case sample
From http://stackoverflow.com/q/43293894/4234729

```xml
  ...
  <class name="com.pac.base.BaseSetup">
     <parameter name="browsername" value="FireFox"> </parameter>     
   </class>
   ...
```

```java
@Parameters({"browsername"})
@BeforeClass
public  void LaunchBrowser(String browsername){
}
```

### Expected behavior
We expect `FireFox` as browsername value

### Actual behavior
The configuration is skipped

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1417

Unrelated Change:
Fixed a sonar violation in Parameters class
(which got introduced from my previous delivery)

Fixes #1417 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - Can you please help take a look at this one ?

File: src/main/java/org/testng/xml/XmlTest.java [hunk 1]
```diff
@@ -935,4 +935,19 @@ public void setXmlSuite(XmlSuite suite) {
...
+   * @return - {@link XmlClass} if {@link Class} is part of the current {@link XmlTest} (or) <code>null</code>
+   * if not found.
+   */
+  public XmlClass getXmlClass(Class<?> clazz) {
+    for (XmlClass xmlClass : this.m_xmlClasses) {
+      if (xmlClass.getSupportClass().equals(clazz)) {
+        return xmlClass;
+      }
+    }
+    return null;
```
Comment (juherr) [inline src/main/java/org/testng/xml/XmlTest.java]: I prefer to return a new `XmlClass` or to throw an exception.

File: src/test/java/test/github1417/AnotherTestClassSample.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Parameters;
+import org.testng.annotations.Test;
+
+public class AnotherTestClassSample {
+    private String browsername;
+
+    @Parameters({"browsername"})
+    @BeforeClass
+    public void LaunchBrowser(String browsername) {
```
Comment (juherr) [inline src/test/java/test/github1417/AnotherTestClassSample.java]: lower case for the start of the method name

File: src/test/java/test/github1417/TestClass.java [hunk 3]
```diff
@@ -0,0 +1,21 @@
+package test.github1417;
+
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Parameters;
+import org.testng.annotations.Test;
+
+public class TestClass {
```
Comment (juherr) [inline src/test/java/test/github1417/TestClass.java]: Naming convention: *Sample

File: src/test/resources/testng.xml [hunk 4]
```diff
@@ -23,6 +23,17 @@
     </classes>
   </test>
 
+  <test name="1417_test">
+    <classes>
+      <class name="test.github1417.TestClass">
+        <parameter name="browsername" value="firefox"/>
```
Comment (juherr) [inline src/test/resources/testng.xml]: I prefer to have a test that constructs or use its own suite file because it is easier to run alone.

File: src/main/java/org/testng/TestRunner.java [hunk 5]
```diff
@@ -862,6 +866,16 @@ private void privateRun(XmlTest xmlTest) {
     return result;
   }
 
+  private Map<String, String> getParameters(IMethodInstance im) {
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java]: Could be static if the `XmlTest` comes from `im.getMethod().getXmlTest()`.

And what about `im.getMethod().findMethodParameters(im.getMethod().getXmlTest())`?

File: src/main/java/org/testng/xml/XmlTest.java (hunk 1 above)
Comment (krmahadevan) [inline src/main/java/org/testng/xml/XmlTest.java]: Got rid of this method itself. Its not needed.

File: src/test/java/test/github1417/AnotherTestClassSample.java (hunk 2 above)
Comment (krmahadevan) [inline src/test/java/test/github1417/AnotherTestClassSample.java]: fixed.

File: src/test/java/test/github1417/TestClass.java (hunk 3 above)
Comment (krmahadevan) [inline src/test/java/test/github1417/TestClass.java]: fixed.

File: src/test/resources/testng.xml (hunk 4 above)
Comment (krmahadevan) [inline src/test/resources/testng.xml]: Agreed. Fixed.

File: src/main/java/org/testng/TestRunner.java (hunk 5 above)
Comment (krmahadevan) [inline src/main/java/org/testng/TestRunner.java]: Fixed this. Made the method static and resorted to using `findMethodParameters()` (That was a good one.. I wasn't aware of that. Thanks for pointing it out)

**Comment by krmahadevan** [comment]
@juherr - Fixed all the review comments.

File: src/main/java/org/testng/TestRunner.java [hunk 6]
```diff
@@ -862,6 +866,13 @@ private void privateRun(XmlTest xmlTest) {
     return result;
   }
 
+  private static Map<String, String> getParameters(IMethodInstance im) {
+    XmlTest xmlTest = im.getMethod().getXmlTest();
+    Map<String, String> params = xmlTest.getAllParameters();
```
Comment (juherr) [inline src/main/java/org/testng/TestRunner.java]: findMethodParameters is already doing it: https://github.com/cbeust/testng/blob/8d1c11bc267ea52157e20ebf6781d1ca9fe7ed1c/src/main/java/org/testng/internal/BaseTestMethod.java#L780

File: src/test/java/test/github1417/TestParamsInjectionInBeforeClass.java [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+
+import org.testng.Assert;
+import org.testng.TestNG;
+import org.testng.annotations.Test;
+
+import java.util.Collections;
+
+public class TestParamsInjectionInBeforeClass {
+    @Test
+    public void testMethod() {
```
Comment (juherr) [inline src/test/java/test/github1417/TestParamsInjectionInBeforeClass.java]: A test with `@AfterClass` may help to improve the coverage.

**Comment by krmahadevan** [comment]
@juherr - FYR... btw.. the failure is not related to my changes.

**Review by juherr — APPROVED** [review]
LGTM 👍 
Ping @cbeust
