### PR TITLE
Streamline test-class instantiation

### LINKED ISSUE #1924: Unable to run testcases with testng 7.0.0-beta1 in eclipse / maven test
I am using latest testng 7.0.0-beta1 version to show factory parameters in custom report. Below is the dependency in pom.xml

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.0.0-beta1</version>
			<scope>test</scope>
		</dependency>

Eclipse plugin details 

- TestNG	7.0.0.201809110942	org.testng.eclipse.feature.group	Cedric Beust
-   TestNG M2E (Maven) Integration (Optional)	7.0.0.201809110942	org.testng.eclipse.maven.feature.feature.group	TestNG Team
-   TestNG P2 Feature	7.0.0.b201809110940	org.testng.p2.feature.feature.group	TestNG Team

Test case execution is failing in both eclipse and command line. 
In eclipse when running from a testng xml I am getting this exception:

[RemoteTestNG] failed to get TestNG version from class: java.lang.IllegalArgumentException: invalid version "7.0.0-": non-numeric "0-"
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] now trying to parse the version from MANIFEST.MF
Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.0.0) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:121)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:49)

When I am running using mvn test from command line I am getting the below exception:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project PaymentPageUITests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException: 
[ERROR] 
[ERROR] An error occurred while instantiating class com.nttdhktest.DummyTests. Check to make sure it can be instantiated
[ERROR] 	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:388)
[ERROR] 	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
[ERROR] 	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:110)
[ERROR] 	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:188)
[ERROR] 	at org.testng.TestClass.getInstances(TestClass.java:94)
[ERROR] 	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:79)
[ERROR] 	at org.testng.TestClass.init(TestClass.java:71)
[ERROR] 	at org.testng.TestClass.<init>(TestClass.java:36)
[ERROR] 	at org.testng.TestRunner.initMethods(TestRunner.java:461)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:340)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:293)
[ERROR] 	at org.testng.TestRunner.<init>(TestRunner.java:178)
[ERROR] 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:603)
[ERROR] 	at org.testng.SuiteRunner.init(SuiteRunner.java:194)
[ERROR] 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:125)
[ERROR] 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1230)
[ERROR] 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1209)
[ERROR] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1058)
[ERROR] 	at org.testng.TestNG.runSuites(TestNG.java:997)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:965)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] 

Please help!

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1924

Ensure test class gets instantiated even when 
there is both a factory method and a non default 
constructor is present.

Fixes #1924  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

File: src/main/java/org/testng/internal/ClassImpl.java [hunk 1]
```diff
@@ -184,15 +184,15 @@ private Module newModule(Class<Module> module) {
                   create)
```
Comment (juherr) [inline src/main/java/org/testng/internal/ClassImpl.java]: Could you refactor the method? It looks that `if (m_testContext.getCurrentXmlTest().isJUnit())` is useless or not a the best place.

Comment (krmahadevan) [reply src/main/java/org/testng/internal/ClassImpl.java]: @juherr - That would need regression (`junit=true` attribute in `<suite>` tag) and it is not related to this bug. So I would not want to include that in this changes and would like to keep the changes as close to fixing the bug as possible.

File: src/main/java/org/testng/internal/ClassImpl.java [hunk 2]
```diff
@@ -184,15 +184,15 @@ private Module newModule(Class<Module> module) {
...
             };
       }
+    }
+    if (m_instances.size() > 0) {
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ClassImpl.java]: @juherr - In this situation I believe `size()` method is fine because if I were to be using `isEmpty()` but without the negation (`!`), then I would have flip the conditions. I dont have an issue doing that. But I would like to understand what are we gaining by doing that. The code as it stands IMO is readable and understandable as well.

**Comment by krmahadevan** [comment]
@juherr - I have responded to your comments. If there are no further questions can we please have this merged ?

File: src/main/java/org/testng/internal/ClassImpl.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (juherr) [reply src/main/java/org/testng/internal/ClassImpl.java]: ok

File: src/main/java/org/testng/internal/ClassImpl.java (hunk 1 above)
Comment (juherr) [reply src/main/java/org/testng/internal/ClassImpl.java]: Right, it's outside the goal of fixing bugs but I like to boy scout rule too :p http://www.informit.com/articles/article.aspx?p=1235624&seqNum=6

In fact, I don't understand the logic of the `isJUnit` condition because `result` is overriden later, except in a not obvious case I don't catch.

**Review by juherr — APPROVED** [review]
I'd prefer to not forget the smelling code but it must not block the bug fixing.

File: src/main/java/org/testng/internal/ClassImpl.java (hunk 1 above)
Comment (krmahadevan) [reply src/main/java/org/testng/internal/ClassImpl.java]: @juherr - Yes I agree with you on the `boy scout rule` and I try to do it as and when time permits. But I generally resist that urge only when the change involves some other functionality wherein I would need to spend time to understand that before making changes, so that I dont break anything. The `isJunit` part is one such area because I have never used TestNG to run any JUnit tests at all.
